{{- if .Values.kafka.enabled -}}
{{- with .Values.kafka -}}
{{- $replicas := .replicas | default 1 -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" $ "component" "kafka") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" $ "component" "kafka") | nindent 4 }}
  annotations:
    {{- toYaml .podAnnotations | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      {{- include "mimir.selectorLabels" (dict "ctx" $ "component" "kafka") | nindent 6 }}
  serviceName: {{ include "mimir.resourceName" (dict "ctx" $ "component" "kafka") }}-headless
  template:
    metadata:
      labels:
        {{- include "mimir.podLabels" (dict "ctx" $ "component" "kafka") | nindent 8 }}
      annotations:
        {{- include "mimir.podAnnotations" (dict "ctx" $ "component" "kafka") | nindent 8 }}
      namespace: {{ $.Release.Namespace | quote }}
    spec:
      serviceAccountName: {{ template "mimir.serviceAccountName" $ }}
      {{- if .priorityClassName }}
      priorityClassName: {{ .priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .securityContext | nindent 8 }}
      {{- if .image.pullSecrets }}
      imagePullSecrets:
      {{- range .image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
      {{- with .dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kafka
          image: {{ .image.registry }}/{{ .image.repository }}:{{ .image.tag }}
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - containerPort: 9092
              name: kafka
              protocol: TCP
            - containerPort: 9093
              name: controller
              protocol: TCP
          {{- include "mimir.kafka.containerEnv" (dict "ctx" $ "replicas" $replicas) | nindent 10 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          securityContext:
            {{- toYaml .containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka
            - name: kafka-config
              mountPath: /opt/kafka/config
            - name: tmp
              mountPath: /tmp
            {{- with .extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: kafka
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: kafka-config
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        {{- if not .persistence.enabled }}
        - name: kafka-data
          emptyDir:
            {{- toYaml .persistence.emptyDir | nindent 12 }}
        {{- end }}
        {{- with .extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if .persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: kafka-data
      spec:
        {{- if .persistence.storageClassName }}
        {{- if (eq "-" .persistence.storageClassName) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .persistence.storageClassName }}"
        {{- end }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .persistence.size }}"
  {{- end }}
{{- end }}
{{- end }}
