// Provenance-includes-location: https://github.com/cortexproject/cortex/blob/master/pkg/alertmanager/alertmanagerpb/alertmanager.proto
// Provenance-includes-license: Apache-2.0
// Provenance-includes-copyright: The Cortex Authors.
// SPDX-License-Identifier: AGPL-3.0-only

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alertmanager.proto

package alertmanagerpb

import (
	httpgrpc "github.com/grafana/dskit/httpgrpc"
	clusterpb "github.com/prometheus/alertmanager/cluster/clusterpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStateStatus int32

const (
	UpdateStateStatus_OK             UpdateStateStatus = 0
	UpdateStateStatus_MERGE_ERROR    UpdateStateStatus = 2
	UpdateStateStatus_USER_NOT_FOUND UpdateStateStatus = 3
)

// Enum value maps for UpdateStateStatus.
var (
	UpdateStateStatus_name = map[int32]string{
		0: "OK",
		2: "MERGE_ERROR",
		3: "USER_NOT_FOUND",
	}
	UpdateStateStatus_value = map[string]int32{
		"OK":             0,
		"MERGE_ERROR":    2,
		"USER_NOT_FOUND": 3,
	}
)

func (x UpdateStateStatus) Enum() *UpdateStateStatus {
	p := new(UpdateStateStatus)
	*p = x
	return p
}

func (x UpdateStateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_alertmanager_proto_enumTypes[0].Descriptor()
}

func (UpdateStateStatus) Type() protoreflect.EnumType {
	return &file_alertmanager_proto_enumTypes[0]
}

func (x UpdateStateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStateStatus.Descriptor instead.
func (UpdateStateStatus) EnumDescriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{0}
}

type ReadStateStatus int32

const (
	ReadStateStatus_READ_UNSPECIFIED    ReadStateStatus = 0
	ReadStateStatus_READ_OK             ReadStateStatus = 1
	ReadStateStatus_READ_ERROR          ReadStateStatus = 2
	ReadStateStatus_READ_USER_NOT_FOUND ReadStateStatus = 3
)

// Enum value maps for ReadStateStatus.
var (
	ReadStateStatus_name = map[int32]string{
		0: "READ_UNSPECIFIED",
		1: "READ_OK",
		2: "READ_ERROR",
		3: "READ_USER_NOT_FOUND",
	}
	ReadStateStatus_value = map[string]int32{
		"READ_UNSPECIFIED":    0,
		"READ_OK":             1,
		"READ_ERROR":          2,
		"READ_USER_NOT_FOUND": 3,
	}
)

func (x ReadStateStatus) Enum() *ReadStateStatus {
	p := new(ReadStateStatus)
	*p = x
	return p
}

func (x ReadStateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadStateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_alertmanager_proto_enumTypes[1].Descriptor()
}

func (ReadStateStatus) Type() protoreflect.EnumType {
	return &file_alertmanager_proto_enumTypes[1]
}

func (x ReadStateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadStateStatus.Descriptor instead.
func (ReadStateStatus) EnumDescriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{1}
}

type DigestType int32

const (
	DigestType_DIGEST_TYPE_UNSPECIFIED DigestType = 0
	DigestType_DIGEST_TYPE_SILENCES    DigestType = 1
)

// Enum value maps for DigestType.
var (
	DigestType_name = map[int32]string{
		0: "DIGEST_TYPE_UNSPECIFIED",
		1: "DIGEST_TYPE_SILENCES",
	}
	DigestType_value = map[string]int32{
		"DIGEST_TYPE_UNSPECIFIED": 0,
		"DIGEST_TYPE_SILENCES":    1,
	}
)

func (x DigestType) Enum() *DigestType {
	p := new(DigestType)
	*p = x
	return p
}

func (x DigestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DigestType) Descriptor() protoreflect.EnumDescriptor {
	return file_alertmanager_proto_enumTypes[2].Descriptor()
}

func (DigestType) Type() protoreflect.EnumType {
	return &file_alertmanager_proto_enumTypes[2]
}

func (x DigestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DigestType.Descriptor instead.
func (DigestType) EnumDescriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{2}
}

type UpdateStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        UpdateStateStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=alertmanagerpb.UpdateStateStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStateResponse) Reset() {
	*x = UpdateStateResponse{}
	mi := &file_alertmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStateResponse) ProtoMessage() {}

func (x *UpdateStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alertmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateStateResponse) Descriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateStateResponse) GetStatus() UpdateStateStatus {
	if x != nil {
		return x.Status
	}
	return UpdateStateStatus_OK
}

func (x *UpdateStateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// If only_silences is false, every part is returned, which is what the initial sync uses.
type ReadStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlySilences  bool                   `protobuf:"varint,1,opt,name=only_silences,json=onlySilences,proto3" json:"only_silences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStateRequest) Reset() {
	*x = ReadStateRequest{}
	mi := &file_alertmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStateRequest) ProtoMessage() {}

func (x *ReadStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alertmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStateRequest.ProtoReflect.Descriptor instead.
func (*ReadStateRequest) Descriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{1}
}

func (x *ReadStateRequest) GetOnlySilences() bool {
	if x != nil {
		return x.OnlySilences
	}
	return false
}

type ReadStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ReadStateStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=alertmanagerpb.ReadStateStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	State         *clusterpb.FullState   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStateResponse) Reset() {
	*x = ReadStateResponse{}
	mi := &file_alertmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStateResponse) ProtoMessage() {}

func (x *ReadStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alertmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStateResponse.ProtoReflect.Descriptor instead.
func (*ReadStateResponse) Descriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{2}
}

func (x *ReadStateResponse) GetStatus() ReadStateStatus {
	if x != nil {
		return x.Status
	}
	return ReadStateStatus_READ_UNSPECIFIED
}

func (x *ReadStateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadStateResponse) GetState() *clusterpb.FullState {
	if x != nil {
		return x.State
	}
	return nil
}

type TenantDigestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDigestsRequest) Reset() {
	*x = TenantDigestsRequest{}
	mi := &file_alertmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDigestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDigestsRequest) ProtoMessage() {}

func (x *TenantDigestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alertmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDigestsRequest.ProtoReflect.Descriptor instead.
func (*TenantDigestsRequest) Descriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{3}
}

func (x *TenantDigestsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Digest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          DigestType             `protobuf:"varint,1,opt,name=type,proto3,enum=alertmanagerpb.DigestType" json:"type,omitempty"`
	Value         uint64                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Digest) Reset() {
	*x = Digest{}
	mi := &file_alertmanager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Digest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digest) ProtoMessage() {}

func (x *Digest) ProtoReflect() protoreflect.Message {
	mi := &file_alertmanager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digest.ProtoReflect.Descriptor instead.
func (*Digest) Descriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{4}
}

func (x *Digest) GetType() DigestType {
	if x != nil {
		return x.Type
	}
	return DigestType_DIGEST_TYPE_UNSPECIFIED
}

func (x *Digest) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// TenantDigest lets a peer cheaply check whether its own view of a tenant matches this replica's.
// A part missing from digests means "no authoritative data", not zero.
type TenantDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Digests       []*Digest              `protobuf:"bytes,3,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDigest) Reset() {
	*x = TenantDigest{}
	mi := &file_alertmanager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDigest) ProtoMessage() {}

func (x *TenantDigest) ProtoReflect() protoreflect.Message {
	mi := &file_alertmanager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDigest.ProtoReflect.Descriptor instead.
func (*TenantDigest) Descriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{5}
}

func (x *TenantDigest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TenantDigest) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *TenantDigest) GetDigests() []*Digest {
	if x != nil {
		return x.Digests
	}
	return nil
}

type TenantDigestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digests       []*TenantDigest        `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDigestsResponse) Reset() {
	*x = TenantDigestsResponse{}
	mi := &file_alertmanager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDigestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDigestsResponse) ProtoMessage() {}

func (x *TenantDigestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alertmanager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDigestsResponse.ProtoReflect.Descriptor instead.
func (*TenantDigestsResponse) Descriptor() ([]byte, []int) {
	return file_alertmanager_proto_rawDescGZIP(), []int{6}
}

func (x *TenantDigestsResponse) GetDigests() []*TenantDigest {
	if x != nil {
		return x.Digests
	}
	return nil
}

var File_alertmanager_proto protoreflect.FileDescriptor

const file_alertmanager_proto_rawDesc = "" +
	"\n" +
	"\x12alertmanager.proto\x12\x0ealertmanagerpb\x1a0github.com/grafana/dskit/httpgrpc/httpgrpc.proto\x1aBgithub.com/prometheus/alertmanager/cluster/clusterpb/cluster.proto\"f\n" +
	"\x13UpdateStateResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.alertmanagerpb.UpdateStateStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\x10ReadStateRequest\x12#\n" +
	"\ronly_silences\x18\x01 \x01(\bR\fonlySilences\"\x8e\x01\n" +
	"\x11ReadStateResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.alertmanagerpb.ReadStateStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12*\n" +
	"\x05state\x18\x03 \x01(\v2\x14.clusterpb.FullStateR\x05state\"1\n" +
	"\x14TenantDigestsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"N\n" +
	"\x06Digest\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.alertmanagerpb.DigestTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value\"o\n" +
	"\fTenantDigest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x120\n" +
	"\adigests\x18\x03 \x03(\v2\x16.alertmanagerpb.DigestR\adigests\"O\n" +
	"\x15TenantDigestsResponse\x126\n" +
	"\adigests\x18\x01 \x03(\v2\x1c.alertmanagerpb.TenantDigestR\adigests*@\n" +
	"\x11UpdateStateStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x0f\n" +
	"\vMERGE_ERROR\x10\x02\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x03*]\n" +
	"\x0fReadStateStatus\x12\x14\n" +
	"\x10READ_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aREAD_OK\x10\x01\x12\x0e\n" +
	"\n" +
	"READ_ERROR\x10\x02\x12\x17\n" +
	"\x13READ_USER_NOT_FOUND\x10\x03*C\n" +
	"\n" +
	"DigestType\x12\x1b\n" +
	"\x17DIGEST_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DIGEST_TYPE_SILENCES\x10\x012\xcf\x02\n" +
	"\fAlertmanager\x12@\n" +
	"\rHandleRequest\x12\x15.httpgrpc.HTTPRequest\x1a\x16.httpgrpc.HTTPResponse\"\x00\x12E\n" +
	"\vUpdateState\x12\x0f.clusterpb.Part\x1a#.alertmanagerpb.UpdateStateResponse\"\x00\x12R\n" +
	"\tReadState\x12 .alertmanagerpb.ReadStateRequest\x1a!.alertmanagerpb.ReadStateResponse\"\x00\x12b\n" +
	"\x11ReadTenantDigests\x12$.alertmanagerpb.TenantDigestsRequest\x1a%.alertmanagerpb.TenantDigestsResponse\"\x00BIZGgithub.com/grafana/mimir/pkg/alertmanager/alertmanagerpb;alertmanagerpbb\x06proto3"

var (
	file_alertmanager_proto_rawDescOnce sync.Once
	file_alertmanager_proto_rawDescData []byte
)

func file_alertmanager_proto_rawDescGZIP() []byte {
	file_alertmanager_proto_rawDescOnce.Do(func() {
		file_alertmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alertmanager_proto_rawDesc), len(file_alertmanager_proto_rawDesc)))
	})
	return file_alertmanager_proto_rawDescData
}

var file_alertmanager_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_alertmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_alertmanager_proto_goTypes = []any{
	(UpdateStateStatus)(0),        // 0: alertmanagerpb.UpdateStateStatus
	(ReadStateStatus)(0),          // 1: alertmanagerpb.ReadStateStatus
	(DigestType)(0),               // 2: alertmanagerpb.DigestType
	(*UpdateStateResponse)(nil),   // 3: alertmanagerpb.UpdateStateResponse
	(*ReadStateRequest)(nil),      // 4: alertmanagerpb.ReadStateRequest
	(*ReadStateResponse)(nil),     // 5: alertmanagerpb.ReadStateResponse
	(*TenantDigestsRequest)(nil),  // 6: alertmanagerpb.TenantDigestsRequest
	(*Digest)(nil),                // 7: alertmanagerpb.Digest
	(*TenantDigest)(nil),          // 8: alertmanagerpb.TenantDigest
	(*TenantDigestsResponse)(nil), // 9: alertmanagerpb.TenantDigestsResponse
	(*clusterpb.FullState)(nil),   // 10: clusterpb.FullState
	(*httpgrpc.HTTPRequest)(nil),  // 11: httpgrpc.HTTPRequest
	(*clusterpb.Part)(nil),        // 12: clusterpb.Part
	(*httpgrpc.HTTPResponse)(nil), // 13: httpgrpc.HTTPResponse
}
var file_alertmanager_proto_depIdxs = []int32{
	0,  // 0: alertmanagerpb.UpdateStateResponse.status:type_name -> alertmanagerpb.UpdateStateStatus
	1,  // 1: alertmanagerpb.ReadStateResponse.status:type_name -> alertmanagerpb.ReadStateStatus
	10, // 2: alertmanagerpb.ReadStateResponse.state:type_name -> clusterpb.FullState
	2,  // 3: alertmanagerpb.Digest.type:type_name -> alertmanagerpb.DigestType
	7,  // 4: alertmanagerpb.TenantDigest.digests:type_name -> alertmanagerpb.Digest
	8,  // 5: alertmanagerpb.TenantDigestsResponse.digests:type_name -> alertmanagerpb.TenantDigest
	11, // 6: alertmanagerpb.Alertmanager.HandleRequest:input_type -> httpgrpc.HTTPRequest
	12, // 7: alertmanagerpb.Alertmanager.UpdateState:input_type -> clusterpb.Part
	4,  // 8: alertmanagerpb.Alertmanager.ReadState:input_type -> alertmanagerpb.ReadStateRequest
	6,  // 9: alertmanagerpb.Alertmanager.ReadTenantDigests:input_type -> alertmanagerpb.TenantDigestsRequest
	13, // 10: alertmanagerpb.Alertmanager.HandleRequest:output_type -> httpgrpc.HTTPResponse
	3,  // 11: alertmanagerpb.Alertmanager.UpdateState:output_type -> alertmanagerpb.UpdateStateResponse
	5,  // 12: alertmanagerpb.Alertmanager.ReadState:output_type -> alertmanagerpb.ReadStateResponse
	9,  // 13: alertmanagerpb.Alertmanager.ReadTenantDigests:output_type -> alertmanagerpb.TenantDigestsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_alertmanager_proto_init() }
func file_alertmanager_proto_init() {
	if File_alertmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alertmanager_proto_rawDesc), len(file_alertmanager_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alertmanager_proto_goTypes,
		DependencyIndexes: file_alertmanager_proto_depIdxs,
		EnumInfos:         file_alertmanager_proto_enumTypes,
		MessageInfos:      file_alertmanager_proto_msgTypes,
	}.Build()
	File_alertmanager_proto = out.File
	file_alertmanager_proto_goTypes = nil
	file_alertmanager_proto_depIdxs = nil
}
