// SPDX-License-Identifier: AGPL-3.0-only

syntax = "proto3";

package compactorschedulerpb;

import "gogoproto/gogo.proto";

option go_package = "compactorschedulerpb";
option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;

message JobKey {
  string id = 1;
  int64 epoch = 2;
}

enum JobType {
  JOB_TYPE_UNKNOWN = 0;
  JOB_TYPE_COMPACTION = 1;
  JOB_TYPE_PLANNING = 2;
  JOB_TYPE_BACKFILL_PHASE_PLANNING = 3;
  JOB_TYPE_BACKFILL_CLEANUP = 4;
  JOB_TYPE_BACKFILL_VALIDATE = 5;
  JOB_TYPE_BACKFILL_COPY = 6;
}

message JobSpec {
  string tenant = 1;
  CompactionJob job = 2;
  JobType job_type = 3;
  BackfillPhasePlanningJob backfill_phase_planning = 4;
  BackfillCleanupJob backfill_cleanup = 5;
  BackfillBlockJob backfill_block = 6;
}

message BackfillBlockJob {
  string backfill_id = 1;
  bytes block_id = 2;
}

message BackfillPhasePlanningJob {
  bool has_outstanding_jobs = 1;
}

message BackfillCleanupJob {
  string backfill_id = 1;
}

message CompactionJob {
  repeated bytes block_ids = 1;
  bool split = 2;
  uint64 total_blocks_bytes = 3;
}

service CompactorScheduler {
  rpc LeaseJob(LeaseJobRequest) returns (LeaseJobResponse);
  rpc PlannedJobs(PlannedJobsRequest) returns (PlannedJobsResponse);
  rpc UpdatePlanJob(UpdatePlanJobRequest) returns (UpdateJobResponse);
  rpc UpdateCompactionJob(UpdateCompactionJobRequest) returns (UpdateJobResponse);
  rpc UpdateBackfillJob(UpdateBackfillJobRequest) returns (UpdateJobResponse);
}

message LaneRequest {
  JobType job_type = 1;
}

message LeaseJobRequest {
  string worker_id = 1;
  repeated LaneRequest lane_requests = 2;
}

message LeaseJobResponse {
  JobKey key = 1;
  JobSpec spec = 2;
}

message PlannedJob {
  string id = 1;
  oneof job {
    CompactionJob compaction = 2;
    BackfillCleanupJob backfill_cleanup = 3;
    BackfillBlockJob backfill_validate = 4;
    BackfillBlockJob backfill_copy = 5;
  }
}

message PlannedJobsRequest {
  JobKey key = 1;
  string tenant = 2;
  repeated PlannedJob jobs = 3;
  bool unchanged = 4;
}

message PlannedJobsResponse {}

enum UpdateType {
  UPDATE_TYPE_UNKNOWN = 0;
  UPDATE_TYPE_IN_PROGRESS = 1;
  UPDATE_TYPE_COMPLETE = 2;
  UPDATE_TYPE_REASSIGN = 3;
  UPDATE_TYPE_ABANDON = 4;
  UPDATE_TYPE_INTERRUPTED_REASSIGN = 5;
}

message UpdatePlanJobRequest {
  JobKey key = 1;
  string tenant = 2;
  UpdateType update = 3;
}

message UpdateCompactionJobRequest {
  JobKey key = 1;
  string tenant = 2;
  UpdateType update = 3;
}

message UpdateBackfillJobRequest {
  JobKey key = 1;
  string tenant = 2;
  UpdateType update = 3;
}

message UpdateJobResponse {}

enum StoredJobStatus {
  STORED_JOB_STATUS_UNKNOWN = 0;
  STORED_JOB_STATUS_AVAILABLE = 1;
  STORED_JOB_STATUS_LEASED = 2;
  STORED_JOB_STATUS_COMPLETE = 3;
}

message StoredJobInfo {
  int64 creation_time = 1;
  StoredJobStatus status = 2;
  int64 status_time = 3;
  int32 num_leases = 4;
  int64 epoch = 5;
}

message StoredCompactionJob {
  StoredJobInfo info = 1;
  CompactionJob job = 2;
  uint32 order = 3;
}

message StoredBackfillCleanupJob {
  StoredJobInfo info = 1;
  string backfill_id = 2;
}

message StoredBackfillBlockJob {
  StoredJobInfo info = 1;
  BackfillBlockJob job = 2;
  uint32 order = 3;
}

message PersistenceMetadata {
  uint32 shard_count = 1;
  int64 creation_time = 2;
  bool backfill_mode = 3;
}
