// Code generated by node-gen. DO NOT EDIT.
// SPDX-License-Identifier: AGPL-3.0-only

package core

import (
	"fmt"

	"github.com/grafana/mimir/pkg/streamingpromql/planning"
)

func (a *AggregateExpression) Child(idx int) planning.Node {
	switch idx {
	case 0:
		return a.Inner
	case 1:
		if a.Param == nil {
			panic("cannot get AggregateExpression child at index 1 if Param is nil")
		}
		return a.Param
	default:
		panic(fmt.Sprintf("node of type AggregateExpression supports 2 children, but attempted to get child at index %d", idx))
	}
}

func (a *AggregateExpression) ChildCount() int {
	if a.Param == nil {
		return 1
	}
	return 2
}

func (b *BinaryExpression) Child(idx int) planning.Node {
	switch idx {
	case 0:
		return b.LHS
	case 1:
		return b.RHS
	default:
		panic(fmt.Sprintf("node of type BinaryExpression supports 2 children, but attempted to get child at index %d", idx))
	}
}

func (b *BinaryExpression) ChildCount() int {
	return 2
}

func (d *DataLabelSelector) Child(idx int) planning.Node {
	panic(fmt.Sprintf("node of type DataLabelSelector has no children, but attempted to get child at index %d", idx))
}

func (d *DataLabelSelector) ChildCount() int {
	return 0
}

func (d *DeduplicateAndMerge) Child(idx int) planning.Node {
	if idx != 0 {
		panic(fmt.Sprintf("node of type DeduplicateAndMerge supports 1 child, but attempted to get child at index %d", idx))
	}
	return d.Inner
}

func (d *DeduplicateAndMerge) ChildCount() int {
	return 1
}

func (d *DropName) Child(idx int) planning.Node {
	if idx != 0 {
		panic(fmt.Sprintf("node of type DropName supports 1 child, but attempted to get child at index %d", idx))
	}
	return d.Inner
}

func (d *DropName) ChildCount() int {
	return 1
}

func (f *FunctionCall) Child(idx int) planning.Node {
	if idx >= len(f.Args) {
		panic(fmt.Sprintf("this FunctionCall node has %d children, but attempted to get child at index %d", len(f.Args), idx))
	}
	return f.Args[idx]
}

func (f *FunctionCall) ChildCount() int {
	return len(f.Args)
}

func (m *MatrixSelector) Child(idx int) planning.Node {
	panic(fmt.Sprintf("node of type MatrixSelector has no children, but attempted to get child at index %d", idx))
}

func (m *MatrixSelector) ChildCount() int {
	return 0
}

func (n *NoOp) Child(idx int) planning.Node {
	panic(fmt.Sprintf("node of type NoOp has no children, but attempted to get child at index %d", idx))
}

func (n *NoOp) ChildCount() int {
	return 0
}

func (n *NumberLiteral) Child(idx int) planning.Node {
	panic(fmt.Sprintf("node of type NumberLiteral has no children, but attempted to get child at index %d", idx))
}

func (n *NumberLiteral) ChildCount() int {
	return 0
}

func (s *StepInvariantExpression) Child(idx int) planning.Node {
	if idx != 0 {
		panic(fmt.Sprintf("node of type StepInvariantExpression supports 1 child, but attempted to get child at index %d", idx))
	}
	return s.Inner
}

func (s *StepInvariantExpression) ChildCount() int {
	return 1
}

func (s *StringLiteral) Child(idx int) planning.Node {
	panic(fmt.Sprintf("node of type StringLiteral has no children, but attempted to get child at index %d", idx))
}

func (s *StringLiteral) ChildCount() int {
	return 0
}

func (s *Subquery) Child(idx int) planning.Node {
	if idx != 0 {
		panic(fmt.Sprintf("node of type Subquery supports 1 child, but attempted to get child at index %d", idx))
	}
	return s.Inner
}

func (s *Subquery) ChildCount() int {
	return 1
}

func (u *UnaryExpression) Child(idx int) planning.Node {
	if idx != 0 {
		panic(fmt.Sprintf("node of type UnaryExpression supports 1 child, but attempted to get child at index %d", idx))
	}
	return u.Inner
}

func (u *UnaryExpression) ChildCount() int {
	return 1
}

func (v *VectorSelector) Child(idx int) planning.Node {
	panic(fmt.Sprintf("node of type VectorSelector has no children, but attempted to get child at index %d", idx))
}

func (v *VectorSelector) ChildCount() int {
	return 0
}
