#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

IMAGE_TAG=${IMAGE_TAG:-$(./tools/image-tag)}
KO_DOCKER_REPO=grafana

usage() {
    echo "$0"
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        *)
            usage
            exit 2
            ;;
    esac
done

if [[ -z "${IMAGES}" ]]; then
    echo '$IMAGES must be set'
    exit 2
fi

# Push images
for image in ${IMAGES}; do
    IMAGE_TAGS=${IMAGE_TAG}
    echo "Pushing ${KO_DOCKER_REPO}/${image}:${IMAGE_TAG}"

    # If image is the latest stable git tag, update the latest docker image tag.
    # Do not tag with latest any release candidate (tag ends with "-rc.*").
    if [[ "$(git tag | grep -E '^mimir-[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)" == "mimir-${IMAGE_TAG}" ]]; then
        echo "Pushing also ${KO_DOCKER_REPO}/${image}:latest"
        IMAGE_TAGS="${IMAGE_TAG},latest"
    fi

    export KO_DOCKER_REPO
    ko publish-layout -B --tags ${IMAGE_TAGS} ${image} ${image}-oci-layout
done
