#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Filter images to only push query-tee for now
# TODO: Remove once mimir is becoming a public project
IMAGES=$(make DOCKER_IMAGE_DIRS=./cmd/query-tee images)
IMAGE_TAG=${IMAGE_TAG:-$(./tools/image-tag)}

usage() {
    echo "$0"
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        *)
            usage
            exit 2
            ;;
    esac
done

push_image() {
    local image="$1"
    echo "Pushing ${image}:${IMAGE_TAG}"
    docker push ${image}:${IMAGE_TAG}
}

for image in ${IMAGES}; do
    if [[ "$image" == *"build"* ]]; then
        continue
    fi
    push_image "${image}"
done
