#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

IMAGE_TAG=${IMAGE_TAG:-$(./tools/image-tag)}

usage() {
    echo "$0"
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        *)
            usage
            exit 2
            ;;
    esac
done

push_image() {
    local image="$1"
    echo "Pushing ${image}:${IMAGE_TAG}"
    docker push "${image}:${IMAGE_TAG}"

    # If image is the latest stable git tag, update the latest docker image tag.
    # Do not tag with latest any release candidate (tag ends with "-rc.*").
    if [[ "$(git tag | grep -E '^mimir-[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)" == "${IMAGE_TAG}" ]]; then
      docker tag "${image}:${IMAGE_TAG}" "${image}:latest"
      docker push "${image}:latest"
    fi
}

# Push images
for image in $(make images); do
    image_name=$(basename "$image")
    case "$image_name" in
        mimir-build-image)
            # skip mimir-build-image
            continue
            ;;
    esac

    push_image "${image}"
done
