// SPDX-License-Identifier: AGPL-3.0-only

package limitstest

import (
	"fmt"
	"maps"
	"math/rand" //#nosec G404 -- Test-only random generator, no need for a CSPRNG -- nosemgrep: math-random-used
	"net"
	"reflect"
	"strings"
	"testing/quick"
	"time"
	"unsafe"

	"github.com/grafana/dskit/flagext"
	"github.com/prometheus/common/model"
	"github.com/prometheus/otlptranslator"
	"go.yaml.in/yaml/v3"

	"github.com/grafana/mimir/pkg/costattribution/costattributionmodel"
	"github.com/grafana/mimir/pkg/querier/api"
	"github.com/grafana/mimir/pkg/util/validation"
)

// Generator produces random validation.Limits, encoded as map[string]any to
// be passed to a runtimeconfig MapLoader.
type Generator struct {
	// ValueFuncs maps a reflect.Type to a generator for that type. It is
	// consulted first, before the testing/quick.Generator interface and before
	// the generic reflection-based generation. Downstream callers can add
	// entries for their own field or extension types.
	ValueFuncs map[reflect.Type]ValueFunc

	// FieldValueFuncs maps validation.Limits field names to generators for that
	// field. It is consulted before ValueFuncs. It is meant for fields that are
	// only valid with a few specific values, or specific combinations with
	// other fields, so that valid values are generated by construction. See
	// FieldValueFunc.
	FieldValueFuncs map[string]FieldValueFunc

	// SkipFields is the set of validation.Limits field names that are left at
	// their default value instead of being randomized.
	SkipFields map[string]bool

	// Temperature controls how many random perturbances to introduce in the
	// generated limits, from 0 (nothing) to 2 (maximum).
	Temperature float64
}

// ValueFunc returns a random reflect.Value of a specific type.
type ValueFunc func(*rand.Rand) reflect.Value

// GenerateLimits produces a random validation.Limits, encoded as a
// map[string]any to be passed to a runtimeconfig MapLoader.
func GenerateLimits(r *rand.Rand, defaults validation.Limits) map[string]any {
	return NewGenerator().Limits(r, defaults)
}

// NewGenerator returns a Generator preconfigured for the standard Mimir
// validation.Limits field types. The returned Generator may be customized
// before use.
func NewGenerator() *Generator {
	return &Generator{
		ValueFuncs:      defaultValueFuncs(),
		FieldValueFuncs: defaultFieldValueFuncs(),
		SkipFields: map[string]bool{
			// Decoded by the mapstructure loader through a full YAML round-trip
			// (mapDecodeAsYAML), so they are equivalent to the YAML loader by
			// construction, and generating valid random instances is awkward.
			// They are still exercised at their default value.
			"MetricRelabelConfigs":          true,
			"RulerAlertmanagerClientConfig": true,
		},
		Temperature: 1,
	}
}

const (
	weightFieldPerturb     = 40
	weightExtensionPerturb = 60
	weightDurationAsInt    = 30
	weightTimeAsString     = 30
)

// Generator produces a random validation.Limits, encoded as a map[string]any to
// be passed to a runtimeconfig MapLoader.
func (g *Generator) Limits(r *rand.Rand, defaults validation.Limits) map[string]any {
	l := g.limits(r, defaults)
	m := marshalToMap(&l)

	// Convert to a type with custom encodings and merge that into m. We need to
	// merge rather than replace because mapToStructWithCustomEncoding doesn't
	// map unexported fields, such as extensions.
	encType := g.mapToStructWithCustomEncoding(reflect.TypeFor[validation.Limits](), r)
	encoded := deepConvert(reflect.ValueOf(l), encType)
	maps.Copy(m, marshalToMap(encoded.Interface()))

	return m
}

func (g *Generator) limits(r *rand.Rand, defaults validation.Limits) validation.Limits {
	l := defaults
	l.RegisterExtensionsDefaults()
	if err := validate(l); err != nil {
		panic("limitstest: the default limits are invalid: " + err.Error())
	}

	// The limits are valid before and after perturbing each field.
	v := reflect.ValueOf(&l).Elem()
	tp := v.Type()
	for i := range v.NumField() {
		fv := v.Field(i)
		if !fv.CanSet() {
			continue
		}
		name := tp.Field(i).Name
		if g.SkipFields[name] {
			continue
		}
		if !g.coin(r, weightFieldPerturb) {
			continue
		}

		previous := reflect.New(fv.Type()).Elem()
		previous.Set(fv)

		if fn, ok := g.FieldValueFuncs[name]; ok {
			// Valid by construction. Validating is to catch bugs.
			fv.Set(fn(r, &l))
			if err := validate(l); err != nil {
				panic(fmt.Sprintf("limitstest: the value generated for field %s is invalid: %v", name, err))
			}
			continue
		}

		// Valid limits are generated by construction for the rules known to the generator. Other fields are only
		// valid with some values (e.g. the rules of downstream extensions), so keep a new value only if it is.
		fv.Set(g.Value(fv.Type(), r))
		if err := validate(l); err != nil {
			fv.Set(previous)
		}
	}

	g.perturbExtensions(&l, r)
	return l
}

func (g *Generator) chance(weight int) int {
	c := int(float64(weight)*g.Temperature + 0.5)
	if c > 100 {
		return 100
	}
	if c < 0 {
		return 0
	}
	return c
}

func (g *Generator) coin(r *rand.Rand, weight int) bool {
	return r.Intn(100) < g.chance(weight)
}

var generatorType = reflect.TypeFor[quick.Generator]()

// Value returns a random reflect.Value of the given type. It consults
// ValueFuncs, then the testing/quick.Generator interface, then falls back to
// generic reflection-based generation. Structs only have their exported fields
// populated (unexported fields are left zero, which is also what
// YAML/mapstructure decoding leaves them as). Any type it doesn't know how to
// build panics, so new, unhandled types are caught rather than silently zeroed.
func (g *Generator) Value(t reflect.Type, r *rand.Rand) reflect.Value {
	if fn, ok := g.ValueFuncs[t]; ok {
		return fn(r)
	}
	if t.Implements(generatorType) {
		if v, ok := quick.Value(t, r); ok {
			return v
		}
		panic("limitstest: quick.Value failed for testing/quick.Generator type " + t.String())
	}
	switch t.Kind() {
	case reflect.Bool:
		v := reflect.New(t).Elem()
		v.SetBool(r.Intn(2) == 0)
		return v
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v := reflect.New(t).Elem()
		v.SetInt(int64(r.Intn(1 << 20)))
		return v
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		v := reflect.New(t).Elem()
		v.SetUint(uint64(r.Intn(1 << 20)))
		return v
	case reflect.Float32, reflect.Float64:
		v := reflect.New(t).Elem()
		v.SetFloat(float64(r.Intn(1 << 20)))
		return v
	case reflect.String:
		v := reflect.New(t).Elem()
		v.SetString(RandString(r))
		return v
	case reflect.Pointer:
		if r.Intn(3) == 0 {
			return reflect.Zero(t)
		}
		p := reflect.New(t.Elem())
		p.Elem().Set(g.Value(t.Elem(), r))
		return p
	case reflect.Slice:
		n := r.Intn(4)
		s := reflect.MakeSlice(t, n, n)
		for i := range n {
			s.Index(i).Set(g.Value(t.Elem(), r))
		}
		return s
	case reflect.Map:
		m := reflect.MakeMap(t)
		for i := r.Intn(4); i > 0; i-- {
			m.SetMapIndex(g.Value(t.Key(), r), g.Value(t.Elem(), r))
		}
		return m
	case reflect.Struct:
		v := reflect.New(t).Elem()
		for i := 0; i < t.NumField(); i++ {
			fv := v.Field(i)
			if !fv.CanSet() {
				continue
			}
			fv.Set(g.Value(t.Field(i).Type, r))
		}
		return v
	default:
		panic("limitstest: don't know how to generate values of type " + t.String())
	}
}

// validate validates a copy of l, because Validate also modifies the limits it validates (e.g. rounding shard counts
// up to powers of two), and generated limits shouldn't be affected by that.
func validate(l validation.Limits) error {
	return l.Validate()
}

// perturbExtensions randomizes a subset of the extension values stored in l.
func (g *Generator) perturbExtensions(l *validation.Limits, r *rand.Rand) {
	ext := limitsExtensions(l)
	for name, val := range ext {
		if g.coin(r, weightExtensionPerturb) {
			ext[name] = g.Value(reflect.TypeOf(val), r).Interface()
		}
	}
}

func limitsExtensions(l *validation.Limits) map[string]any {
	f := reflect.ValueOf(l).Elem().FieldByName("extensions")
	f = reflect.NewAt(f.Type(), unsafe.Pointer(f.UnsafeAddr())).Elem()
	return f.Interface().(map[string]any)
}

// defaultValueFuncs returns generators for the field types used by
// validation.Limits that are owned by other modules (and therefore can't
// implement testing/quick.Generator here) or that carry unexported state.
func defaultValueFuncs() map[reflect.Type]ValueFunc {
	return map[reflect.Type]ValueFunc{
		reflect.TypeFor[model.Duration](): func(r *rand.Rand) reflect.Value {
			return reflect.ValueOf(model.Duration(time.Duration(r.Intn(100000)) * time.Second))
		},
		reflect.TypeFor[time.Duration](): func(r *rand.Rand) reflect.Value {
			return reflect.ValueOf(time.Duration(r.Intn(100000)) * time.Second)
		},
		reflect.TypeFor[time.Time](): func(r *rand.Rand) reflect.Value {
			return reflect.ValueOf(randTime(r))
		},
		reflect.TypeFor[model.ValidationScheme](): func(r *rand.Rand) reflect.Value {
			choices := []model.ValidationScheme{model.UnsetValidation, model.LegacyValidation, model.UTF8Validation}
			return reflect.ValueOf(choices[r.Intn(len(choices))])
		},
		reflect.TypeFor[flagext.LimitsMap[int]](): func(r *rand.Rand) reflect.Value {
			data := map[string]int{}
			for i := r.Intn(3); i > 0; i-- {
				data[RandKey(r)] = r.Intn(1000) + 1
			}
			return reflect.ValueOf(flagext.NewLimitsMapWithData(data, nil))
		},
		reflect.TypeFor[flagext.LimitsMap[float64]](): func(r *rand.Rand) reflect.Value {
			// The only limit of this type is the per-integration notification rate limit, which is
			// validated at decoding time, and only accepts the names of known integrations.
			integrations := []string{"webhook", "email", "pagerduty", "opsgenie", "slack", "victorops", "telegram"}
			data := map[string]float64{}
			for i := r.Intn(3); i > 0; i-- {
				data[integrations[r.Intn(len(integrations))]] = float64(r.Intn(1000) + 1)
			}
			return reflect.ValueOf(flagext.NewLimitsMapWithData(data, nil))
		},
		reflect.TypeFor[flagext.LimitsMap[string]](): func(r *rand.Rand) reflect.Value {
			data := map[string]string{}
			for i := r.Intn(3); i > 0; i-- {
				data[RandKey(r)] = RandKey(r)
			}
			return reflect.ValueOf(flagext.NewLimitsMapWithData(data, nil))
		},
		reflect.TypeFor[costattributionmodel.Labels](): func(r *rand.Rand) reflect.Value {
			return reflect.ValueOf(randCostAttributionLabels(r, 0, 3))
		},
		reflect.TypeFor[costattributionmodel.TrackerConfigs](): func(r *rand.Rand) reflect.Value {
			return reflect.ValueOf(randCostAttributionTrackers(r))
		},
		reflect.TypeFor[flagext.StringSliceCSV](): func(r *rand.Rand) reflect.Value {
			n := r.Intn(4)
			s := make(flagext.StringSliceCSV, n)
			for i := range s {
				s[i] = RandKey(r)
			}
			return reflect.ValueOf(s)
		},
		reflect.TypeFor[flagext.CIDRSliceCSV](): func(r *rand.Rand) reflect.Value {
			var c flagext.CIDRSliceCSV
			for i := r.Intn(3); i > 0; i-- {
				cidr := randCIDR(r)
				if err := c.Set(cidr); err != nil {
					panic(fmt.Sprintf("limitstest: generated invalid CIDR %q: %v", cidr, err))
				}
			}
			return reflect.ValueOf(c)
		},
	}
}

// randTime returns a random time truncated to whole seconds (so it marshals to a
// clean RFC3339 timestamp).
func randTime(r *rand.Rand) time.Time {
	base := time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)
	return base.Add(time.Duration(r.Intn(1_000_000_000)) * time.Second)
}

// randCIDR returns a random, syntactically valid IPv4 or IPv6 CIDR string.
func randCIDR(r *rand.Rand) string {
	if r.Intn(2) == 0 {
		return fmt.Sprintf("%d.%d.%d.%d/%d", r.Intn(256), r.Intn(256), r.Intn(256), r.Intn(256), r.Intn(33))
	}
	b := make([]byte, net.IPv6len)
	for i := range b {
		b[i] = byte(r.Intn(256))
	}
	// Keep the high byte in the global-unicast range so the address always
	// stringifies as IPv6 (never as an IPv4-mapped/compatible address, whose
	// textual form would be incompatible with an IPv6-sized prefix length).
	b[0] = byte(0x20 + r.Intn(0x10))
	return fmt.Sprintf("%s/%d", net.IP(b).String(), r.Intn(129))
}

const alphabet = "abcdefghABCDEFGH0123456789_"

// RandString returns a random (possibly empty) short string. Exported so
// Generator.ValueFunc implementations supplied by callers can reuse it.
func RandString(r *rand.Rand) string {
	b := make([]byte, r.Intn(8))
	for i := range b {
		b[i] = alphabet[r.Intn(len(alphabet))]
	}
	return string(b)
}

// RandKey returns a random non-empty short string, suitable for map keys.
func RandKey(r *rand.Rand) string {
	b := make([]byte, r.Intn(7)+1)
	for i := range b {
		b[i] = alphabet[r.Intn(len(alphabet))]
	}
	return string(b)
}

// durationAsZeroInt encodes a zero duration as the bare integer 0, which is the only integer that is a valid
// duration. Other durations are encoded as usual: encoding them as 0 would change their value, and so make the
// encoded limits different from the (valid) limits that were generated.
type durationAsZeroInt model.Duration

func (d durationAsZeroInt) MarshalYAML() (any, error) {
	if d == 0 {
		return 0, nil
	}
	return model.Duration(d).String(), nil
}

// timeAsString encodes a timestamp as a quoted RFC3339 string instead of a
// native YAML timestamp.
type timeAsString time.Time

func (t timeAsString) MarshalYAML() (any, error) { return time.Time(t).Format(time.RFC3339), nil }
func (t timeAsString) IsZero() bool              { return time.Time(t).IsZero() }

var (
	durationType     = reflect.TypeFor[model.Duration]()
	timeType         = reflect.TypeFor[time.Time]()
	durationAsIntTyp = reflect.TypeFor[durationAsZeroInt]()
	timeAsStringTyp  = reflect.TypeFor[timeAsString]()

	yamlMarshalerType   = reflect.TypeFor[yaml.Marshaler]()
	yamlUnmarshalerType = reflect.TypeFor[yaml.Unmarshaler]()
)

// mapToTypeWithCustomEncoding maps t to a derived type, such that:
//
//   - Unexported fields are dropped (they aren't serialized).
//   - Types with an associated custom encoding are converted to use the custom
//     encoding, with some probability.
func (g *Generator) mapToTypeWithCustomEncoding(t reflect.Type, r *rand.Rand) reflect.Type {
	switch t {
	case durationType:
		if g.coin(r, weightDurationAsInt) {
			return durationAsIntTyp
		}
		return t
	case timeType:
		if g.coin(r, weightTimeAsString) {
			return timeAsStringTyp
		}
		return t
	}
	if isOpaque(t) {
		return t
	}

	switch t.Kind() {
	case reflect.Pointer:
		if e := g.mapToTypeWithCustomEncoding(t.Elem(), r); e != t.Elem() {
			return reflect.PointerTo(e)
		}
	case reflect.Slice:
		if e := g.mapToTypeWithCustomEncoding(t.Elem(), r); e != t.Elem() {
			return reflect.SliceOf(e)
		}
	case reflect.Array:
		if e := g.mapToTypeWithCustomEncoding(t.Elem(), r); e != t.Elem() {
			return reflect.ArrayOf(t.Len(), e)
		}
	case reflect.Map:
		if e := g.mapToTypeWithCustomEncoding(t.Elem(), r); e != t.Elem() {
			return reflect.MapOf(t.Key(), e)
		}
	case reflect.Struct:
		return g.mapToStructWithCustomEncoding(t, r)
	}
	return t
}

func (g *Generator) mapToStructWithCustomEncoding(t reflect.Type, r *rand.Rand) reflect.Type {
	fields := make([]reflect.StructField, 0, t.NumField())
	changed := false
	for f := range t.Fields() {
		f := f
		if f.PkgPath != "" {
			changed = true // dropping an unexported field changes the type
			continue
		}
		ft := g.mapToTypeWithCustomEncoding(f.Type, r)
		if ft != f.Type {
			changed = true
		}
		fields = append(fields, reflect.StructField{
			Name:      f.Name,
			Type:      ft,
			Tag:       f.Tag,
			Anonymous: f.Anonymous,
		})
	}
	if !changed {
		return t
	}
	return reflect.StructOf(fields)
}

func isOpaque(t reflect.Type) bool {
	pt := reflect.PointerTo(t)
	return t.Implements(yamlMarshalerType) || pt.Implements(yamlMarshalerType) ||
		t.Implements(yamlUnmarshalerType) || pt.Implements(yamlUnmarshalerType)
}

func deepConvert(src reflect.Value, dst reflect.Type) reflect.Value {
	switch dst {
	case src.Type(), durationAsIntTyp, timeAsStringTyp:
		return src.Convert(dst)
	}

	switch dst.Kind() {
	case reflect.Pointer:
		if src.IsNil() {
			return reflect.Zero(dst)
		}
		p := reflect.New(dst.Elem())
		p.Elem().Set(deepConvert(src.Elem(), dst.Elem()))
		return p
	case reflect.Slice:
		if src.IsNil() {
			return reflect.Zero(dst)
		}
		out := reflect.MakeSlice(dst, src.Len(), src.Len())
		for i := range src.Len() {
			out.Index(i).Set(deepConvert(src.Index(i), dst.Elem()))
		}
		return out
	case reflect.Array:
		out := reflect.New(dst).Elem()
		for i := range src.Len() {
			out.Index(i).Set(deepConvert(src.Index(i), dst.Elem()))
		}
		return out
	case reflect.Map:
		if src.IsNil() {
			return reflect.Zero(dst)
		}
		out := reflect.MakeMapWithSize(dst, src.Len())
		for iter := src.MapRange(); iter.Next(); {
			out.SetMapIndex(iter.Key(), deepConvert(iter.Value(), dst.Elem()))
		}
		return out
	case reflect.Struct:
		out := reflect.New(dst).Elem()
		for i := range dst.NumField() {
			df := dst.Field(i)
			sf := src.FieldByName(df.Name)
			if !sf.IsValid() {
				continue
			}
			out.Field(i).Set(deepConvert(sf, df.Type))
		}
		return out
	default:
		if src.Type().ConvertibleTo(dst) {
			return src.Convert(dst)
		}
		return src
	}
}

// marshalToMap marshals v to YAML and parses it back into a generic map, exactly
// the shape a runtime-config loader receives.
func marshalToMap(v any) map[string]any {
	b, err := yaml.Marshal(v)
	if err != nil {
		panic(fmt.Sprintf("limitstest: marshaling: %v", err))
	}
	var m map[string]any
	if err := yaml.Unmarshal(b, &m); err != nil {
		panic(fmt.Sprintf("limitstest: unmarshaling into map: %v", err))
	}
	if m == nil {
		m = map[string]any{}
	}
	return m
}

// FieldValueFunc returns a random value for a field of validation.Limits.
//
// current is the state of the limits being generated, which is valid. The returned value must keep it valid when set
// in the field, given the current values of all the other fields. As the current value of the field is always one such
// value, there is always one to return. Fields involved in the same validation rule read each other's values from
// current, so no field is generated before the others, and fields that aren't perturbed in a given run
// keep a value that is compatible with the rest.
//
// Generator.Limits panics if a FieldValueFunc breaks that. It validates the limits after setting the value
// returned by a FieldValueFunc, to catch generation bugs.
type FieldValueFunc func(r *rand.Rand, current *validation.Limits) reflect.Value

// defaultFieldValueFuncs, and the helpers below it, are the generation side of the rules checked by
// validation.Limits.Validate, so that the generated limits are valid by construction. Generator.Limits still calls
// Validate for the rest of the fields, as a safety net for the rules not listed here (e.g. those of downstream
// extensions).
//
// defaultFieldValueFuncs returns generators for the fields of validation.Limits that are only valid with specific
// values, or specific combinations with other fields.
func defaultFieldValueFuncs() map[string]FieldValueFunc {
	return map[string]FieldValueFunc{
		// Fields with a few valid values.
		"IngestStorageReadConsistency": func(r *rand.Rand, _ *validation.Limits) reflect.Value {
			return reflect.ValueOf(api.ReadConsistencies[r.Intn(len(api.ReadConsistencies))])
		},
		"FloatChunkEncoding": func(r *rand.Rand, _ *validation.Limits) reflect.Value {
			choices := append([]string{""}, validation.FloatChunkEncodingValues...)
			return reflect.ValueOf(choices[r.Intn(len(choices))])
		},
		"EarlyHeadCompactionMinEstimatedSeriesReductionPercentage": func(r *rand.Rand, _ *validation.Limits) reflect.Value {
			return reflect.ValueOf(r.Intn(101))
		},

		// HA tracker timeouts: if any of the update or failover timeouts is set, the failover timeout must be at
		// least the update timeout plus its maximum jitter, plus a second.
		"HATrackerUpdateTimeout": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			if l.HATrackerFailoverTimeout <= 0 {
				return reflect.ValueOf(model.Duration(0)) // Any other value would require a failover timeout.
			}
			return reflect.ValueOf(randSeconds(r, l.HATrackerFailoverTimeout-l.HATrackerUpdateTimeoutJitterMax-model.Duration(time.Second)))
		},
		"HATrackerUpdateTimeoutJitterMax": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			if l.HATrackerFailoverTimeout <= 0 && l.HATrackerUpdateTimeout <= 0 {
				return reflect.ValueOf(model.Duration(time.Duration(r.Intn(100000)) * time.Second)) // No rule applies.
			}
			return reflect.ValueOf(randSeconds(r, l.HATrackerFailoverTimeout-l.HATrackerUpdateTimeout-model.Duration(time.Second)))
		},
		"HATrackerFailoverTimeout": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			if l.HATrackerUpdateTimeout <= 0 && r.Intn(4) == 0 {
				return reflect.ValueOf(model.Duration(0)) // Only valid if the update timeout isn't set either.
			}
			minimum := l.HATrackerUpdateTimeout + l.HATrackerUpdateTimeoutJitterMax + model.Duration(time.Second)
			return reflect.ValueOf(minimum + model.Duration(time.Duration(r.Intn(100000))*time.Second))
		},

		// Truncating or dropping label values requires room for the hash that is appended to them.
		"LabelValueLengthOverLimitStrategy": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			choices := []validation.LabelValueLengthOverLimitStrategy{validation.LabelValueLengthOverLimitStrategyError}
			if l.MaxLabelValueLength >= validation.LabelValueHashLen {
				choices = append(choices, validation.LabelValueLengthOverLimitStrategyTruncate, validation.LabelValueLengthOverLimitStrategyDrop)
			}
			return reflect.ValueOf(choices[r.Intn(len(choices))])
		},
		"MaxLabelValueLength": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			length := r.Intn(1 << 20)
			switch l.LabelValueLengthOverLimitStrategy {
			case validation.LabelValueLengthOverLimitStrategyTruncate, validation.LabelValueLengthOverLimitStrategyDrop:
				length += validation.LabelValueHashLen
			}
			return reflect.ValueOf(length)
		},

		// OTLP translation strategies require a name validation scheme, and metric suffixes to be enabled or disabled.
		"OTelTranslationStrategy": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			choices := []validation.OTelTranslationStrategyValue{""} // Always valid.
			for _, s := range otelTranslationStrategies {
				scheme, suffixes := requirementsOfOTelStrategy(s)
				if scheme == effectiveNameValidationScheme(l) && suffixes == otelMetricSuffixesEnabled(l) {
					choices = append(choices, validation.OTelTranslationStrategyValue(s))
				}
			}
			return reflect.ValueOf(choices[r.Intn(len(choices))])
		},
		"NameValidationScheme": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			choices := []model.ValidationScheme{model.UnsetValidation, model.LegacyValidation, model.UTF8Validation}
			if l.OTelTranslationStrategy != "" {
				scheme, _ := requirementsOfOTelStrategy(otlptranslator.TranslationStrategyOption(l.OTelTranslationStrategy))
				// An unset scheme behaves as the legacy one.
				choices = []model.ValidationScheme{scheme}
				if scheme == model.LegacyValidation {
					choices = append(choices, model.UnsetValidation)
				}
			}
			return reflect.ValueOf(choices[r.Intn(len(choices))])
		},
		"OTelMetricSuffixesEnabled": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			choices := []*bool{nil, new(true), new(false)}
			if l.OTelTranslationStrategy != "" {
				_, suffixes := requirementsOfOTelStrategy(otlptranslator.TranslationStrategyOption(l.OTelTranslationStrategy))
				choices = []*bool{new(true)}
				if !suffixes {
					choices = []*bool{nil, new(false)}
				}
			}
			return reflect.ValueOf(choices[r.Intn(len(choices))])
		},

		// The deprecated cost attribution labels and the cost attribution trackers are mutually exclusive.
		"CostAttributionLabelsStructured": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			if len(l.CostAttributionBaseTrackers) > 0 {
				return reflect.ValueOf(costattributionmodel.Labels(nil))
			}
			return reflect.ValueOf(randCostAttributionLabels(r, 0, 3))
		},
		"CostAttributionBaseTrackers": func(r *rand.Rand, l *validation.Limits) reflect.Value {
			if len(l.CostAttributionLabelsStructured) > 0 {
				return reflect.ValueOf(costattributionmodel.TrackerConfigs(nil))
			}
			return reflect.ValueOf(randCostAttributionTrackers(r))
		},
	}
}

// randSeconds returns a random whole number of seconds between 0 and max, as a duration. Whole seconds because
// durations lose precision when marshaled.
func randSeconds(r *rand.Rand, max model.Duration) model.Duration {
	seconds := int64(time.Duration(max) / time.Second)
	if seconds < 0 {
		panic("limitstest: negative maximum duration")
	}
	return model.Duration(time.Duration(r.Int63n(seconds+1)) * time.Second)
}

var otelTranslationStrategies = []otlptranslator.TranslationStrategyOption{
	otlptranslator.UnderscoreEscapingWithoutSuffixes,
	otlptranslator.UnderscoreEscapingWithSuffixes,
	otlptranslator.NoUTF8EscapingWithSuffixes,
	otlptranslator.NoTranslation,
}

// requirementsOfOTelStrategy returns the name validation scheme that an OTLP translation strategy requires, and
// whether it requires metric suffixes to be enabled (or disabled).
func requirementsOfOTelStrategy(s otlptranslator.TranslationStrategyOption) (scheme model.ValidationScheme, suffixes bool) {
	switch s {
	case otlptranslator.UnderscoreEscapingWithoutSuffixes:
		return model.LegacyValidation, false
	case otlptranslator.UnderscoreEscapingWithSuffixes:
		return model.LegacyValidation, true
	case otlptranslator.NoUTF8EscapingWithSuffixes:
		return model.UTF8Validation, true
	case otlptranslator.NoTranslation:
		return model.UTF8Validation, false
	}
	panic("limitstest: unknown OTLP translation strategy " + string(s))
}

// effectiveNameValidationScheme returns the name validation scheme that validation.Limits uses, in which an unset
// scheme is the legacy one.
func effectiveNameValidationScheme(l *validation.Limits) model.ValidationScheme {
	if l.NameValidationScheme == model.UnsetValidation {
		return model.LegacyValidation
	}
	return l.NameValidationScheme
}

func otelMetricSuffixesEnabled(l *validation.Limits) bool {
	return l.OTelMetricSuffixesEnabled != nil && *l.OTelMetricSuffixesEnabled
}

// randCostAttributionLabels returns between min and max valid cost attribution labels.
func randCostAttributionLabels(r *rand.Rand, min, max int) costattributionmodel.Labels {
	n := min + r.Intn(max-min+1)
	if n == 0 {
		return nil
	}
	labels := make(costattributionmodel.Labels, 0, n)
	outputs := map[string]struct{}{}
	for len(labels) < n {
		label := costattributionmodel.Label{Input: RandKey(r)}
		if r.Intn(2) == 0 {
			// Output labels can't have the reserved prefix.
			for label.Output == "" || strings.HasPrefix(label.Output, "__") {
				label.Output = RandKey(r)
			}
		}
		if _, ok := outputs[label.OutputLabel()]; ok {
			continue // Output labels must be unique.
		}
		outputs[label.OutputLabel()] = struct{}{}
		labels = append(labels, label)
	}
	return labels
}

// randCostAttributionTrackers returns valid cost attribution tracker configs: with a name, and at least one label.
//
// It never returns empty trackers. They are omitted when marshaled (omitempty), so they would be decoded as the
// default trackers, which may not be empty, and which can't be combined with the deprecated cost attribution labels.
func randCostAttributionTrackers(r *rand.Rand) costattributionmodel.TrackerConfigs {
	trackers := costattributionmodel.TrackerConfigs{}
	for i := 1 + r.Intn(3); i > 0; i-- {
		trackers[RandKey(r)] = costattributionmodel.TrackerConfig{
			Labels:   randCostAttributionLabels(r, 1, 3),
			Internal: r.Intn(2) == 0,
		}
	}
	return trackers
}
