// SPDX-License-Identifier: AGPL-3.0-only

syntax = "proto3";

package sharding;

import "gogoproto/gogo.proto";

option go_package = "sharding";
option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;

// SelectorCardinalityStatistics is the value stored in the cardinality cache for a single selector
// and time range when splitting and caching run inside the Mimir query engine.
message SelectorCardinalityStatistics {
  // Key is the unhashed form of this entry's key. It is stored unhashed so that
  // hash collisions on the cache key can be detected.
  bytes key = 1;

  // Cardinality is the number of series selected.
  uint64 cardinality = 2;
}
