#!/bin/sh

set -e

# shellcheck disable=1091
[ -f /etc/default/mimir ] && . /etc/default/mimir

case "$1" in
  remove)
    if command -v systemctl 2>/dev/null; then
        systemctl stop mimir.service >/dev/null 2>&1 || :
    fi
    ;;
esac
