// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gateway.proto

package storegatewaypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	storepb "github.com/grafana/mimir/pkg/storegateway/storepb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MetricNameCountsRequest struct {
	// Blocks to count, as ULID strings. Blocks this store-gateway does not hold are left out of the response's block_ids.
	BlockIds []string `protobuf:"bytes,1,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
}

func (m *MetricNameCountsRequest) Reset()      { *m = MetricNameCountsRequest{} }
func (*MetricNameCountsRequest) ProtoMessage() {}
func (*MetricNameCountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}
func (m *MetricNameCountsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetricNameCountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetricNameCountsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetricNameCountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricNameCountsRequest.Merge(m, src)
}
func (m *MetricNameCountsRequest) XXX_Size() int {
	return m.Size()
}
func (m *MetricNameCountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricNameCountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetricNameCountsRequest proto.InternalMessageInfo

func (m *MetricNameCountsRequest) GetBlockIds() []string {
	if m != nil {
		return m.BlockIds
	}
	return nil
}

type MetricNameCount struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *MetricNameCount) Reset()      { *m = MetricNameCount{} }
func (*MetricNameCount) ProtoMessage() {}
func (*MetricNameCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}
func (m *MetricNameCount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetricNameCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetricNameCount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetricNameCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricNameCount.Merge(m, src)
}
func (m *MetricNameCount) XXX_Size() int {
	return m.Size()
}
func (m *MetricNameCount) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricNameCount.DiscardUnknown(m)
}

var xxx_messageInfo_MetricNameCount proto.InternalMessageInfo

func (m *MetricNameCount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricNameCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MetricNameCountsResponse struct {
	// Per-name series counts summed over the counted blocks.
	Counts []*MetricNameCount `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	// Blocks that were counted.
	BlockIds []string `protobuf:"bytes,2,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
}

func (m *MetricNameCountsResponse) Reset()      { *m = MetricNameCountsResponse{} }
func (*MetricNameCountsResponse) ProtoMessage() {}
func (*MetricNameCountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}
func (m *MetricNameCountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MetricNameCountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MetricNameCountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MetricNameCountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricNameCountsResponse.Merge(m, src)
}
func (m *MetricNameCountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MetricNameCountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricNameCountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetricNameCountsResponse proto.InternalMessageInfo

func (m *MetricNameCountsResponse) GetCounts() []*MetricNameCount {
	if m != nil {
		return m.Counts
	}
	return nil
}

func (m *MetricNameCountsResponse) GetBlockIds() []string {
	if m != nil {
		return m.BlockIds
	}
	return nil
}

func init() {
	proto.RegisterType((*MetricNameCountsRequest)(nil), "gatewaypb.MetricNameCountsRequest")
	proto.RegisterType((*MetricNameCount)(nil), "gatewaypb.MetricNameCount")
	proto.RegisterType((*MetricNameCountsResponse)(nil), "gatewaypb.MetricNameCountsResponse")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0x3d, 0x0d, 0x44, 0xe4, 0x96, 0x9f, 0x32, 0xe2, 0xc7, 0x75, 0xa5, 0xc1, 0x32, 0x9b,
	0xac, 0xec, 0x2a, 0x48, 0x48, 0xa8, 0xbb, 0x16, 0x81, 0x90, 0x00, 0x21, 0x47, 0x62, 0x01, 0x0b,
	0x34, 0x76, 0x07, 0xdb, 0x8a, 0xed, 0x31, 0x33, 0x63, 0x21, 0x76, 0x3c, 0x02, 0x8f, 0xc1, 0xa3,
	0xb0, 0xcc, 0xb2, 0xec, 0x88, 0xb3, 0x61, 0xd9, 0x47, 0x40, 0xf1, 0xd8, 0x6d, 0x6c, 0xd2, 0xec,
	0x7c, 0xcf, 0x3d, 0xf7, 0x9b, 0x73, 0x3d, 0x1a, 0xb8, 0x15, 0x51, 0xc5, 0xbe, 0xd2, 0x6f, 0x6e,
	0x21, 0xb8, 0xe2, 0x78, 0xd4, 0x94, 0x45, 0x60, 0x1d, 0x45, 0x89, 0x8a, 0xcb, 0xc0, 0x0d, 0x79,
	0xe6, 0x45, 0x82, 0x7e, 0xa6, 0x39, 0xf5, 0xb2, 0x24, 0x4b, 0x84, 0x57, 0xcc, 0x22, 0x4f, 0x2a,
	0x2e, 0x58, 0x63, 0xd6, 0x45, 0x11, 0x78, 0xa2, 0x08, 0x35, 0xc7, 0x79, 0x0a, 0x0f, 0xdf, 0x30,
	0x25, 0x92, 0xf0, 0x2d, 0xcd, 0xd8, 0x09, 0x2f, 0x73, 0x25, 0x7d, 0xf6, 0xa5, 0x64, 0x52, 0xe1,
	0x03, 0x18, 0x05, 0x29, 0x0f, 0x67, 0x9f, 0x92, 0x53, 0x69, 0x22, 0x7b, 0x30, 0x1e, 0xf9, 0x37,
	0x6a, 0xe1, 0xd5, 0xa9, 0x74, 0x8e, 0xe0, 0x4e, 0x6f, 0x0e, 0x63, 0xb8, 0x96, 0xd3, 0x8c, 0x99,
	0xc8, 0x46, 0xe3, 0x91, 0x5f, 0x7f, 0xe3, 0x7b, 0x70, 0x3d, 0x5c, 0x35, 0xcd, 0x1d, 0x1b, 0x8d,
	0x07, 0xbe, 0x2e, 0x9c, 0x19, 0x98, 0xff, 0x1f, 0x2a, 0x0b, 0x9e, 0x4b, 0x86, 0x27, 0x30, 0xac,
	0x4d, 0xfa, 0xc8, 0xdd, 0x89, 0xe5, 0x5e, 0x6c, 0xea, 0xf6, 0x86, 0xfc, 0xc6, 0xd9, 0x4d, 0xba,
	0xd3, 0x4d, 0x3a, 0xf9, 0x3d, 0x80, 0x9b, 0xd3, 0xd5, 0xde, 0x2f, 0x35, 0x07, 0x3f, 0x83, 0xe1,
	0x94, 0x89, 0x84, 0x49, 0x7c, 0xdf, 0x55, 0x31, 0xcd, 0xb9, 0x74, 0x75, 0xdd, 0x2c, 0x6e, 0x3d,
	0xe8, 0xcb, 0x3a, 0xda, 0x21, 0xc2, 0x27, 0x00, 0xaf, 0x69, 0xc0, 0xd2, 0x55, 0x04, 0x89, 0xf7,
	0x5b, 0xdf, 0xa5, 0xd6, 0x22, 0xac, 0x4d, 0xad, 0x66, 0xc3, 0x17, 0xb0, 0x5b, 0xab, 0xef, 0x69,
	0x5a, 0x32, 0x89, 0xbb, 0x56, 0x2d, 0xb6, 0x98, 0x83, 0x8d, 0xbd, 0x86, 0xf3, 0x0e, 0xf6, 0xa6,
	0x8c, 0x8a, 0x30, 0x5e, 0x8b, 0xf4, 0xe8, 0x32, 0x7a, 0xb7, 0xd3, 0x12, 0xf7, 0xbb, 0x06, 0x9f,
	0xc9, 0x32, 0x55, 0xc7, 0x54, 0x85, 0xf1, 0x21, 0xc2, 0x3e, 0xdc, 0x5d, 0x9b, 0x6b, 0xf2, 0xd9,
	0x1b, 0x90, 0xdd, 0x94, 0x5b, 0x99, 0x1f, 0x61, 0xaf, 0x7f, 0xd7, 0xd8, 0xb9, 0xfa, 0x4e, 0x2f,
	0xa0, 0x8f, 0xb7, 0x7a, 0xf4, 0x2f, 0x38, 0x7e, 0x3e, 0x5f, 0x10, 0xe3, 0x6c, 0x41, 0x8c, 0xf3,
	0x05, 0x41, 0xdf, 0x2b, 0x82, 0x7e, 0x56, 0x04, 0xfd, 0xaa, 0x08, 0x9a, 0x57, 0x04, 0xfd, 0xa9,
	0x08, 0xfa, 0x5b, 0x11, 0xe3, 0xbc, 0x22, 0xe8, 0xc7, 0x92, 0x18, 0xf3, 0x25, 0x31, 0xce, 0x96,
	0xc4, 0xf8, 0x70, 0x7b, 0xfd, 0x4d, 0x14, 0x41, 0x30, 0xac, 0x9f, 0xc2, 0x93, 0x7f, 0x03, 0x00,
	0x41, 0x5b, 0xb3, 0xdd, 0x63, 0x03, 0x00, 0x00,
}

func (this *MetricNameCountsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MetricNameCountsRequest)
	if !ok {
		that2, ok := that.(MetricNameCountsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.BlockIds) != len(that1.BlockIds) {
		return false
	}
	for i := range this.BlockIds {
		if this.BlockIds[i] != that1.BlockIds[i] {
			return false
		}
	}
	return true
}
func (this *MetricNameCount) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MetricNameCount)
	if !ok {
		that2, ok := that.(MetricNameCount)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Count != that1.Count {
		return false
	}
	return true
}
func (this *MetricNameCountsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MetricNameCountsResponse)
	if !ok {
		that2, ok := that.(MetricNameCountsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Counts) != len(that1.Counts) {
		return false
	}
	for i := range this.Counts {
		if !this.Counts[i].Equal(that1.Counts[i]) {
			return false
		}
	}
	if len(this.BlockIds) != len(that1.BlockIds) {
		return false
	}
	for i := range this.BlockIds {
		if this.BlockIds[i] != that1.BlockIds[i] {
			return false
		}
	}
	return true
}
func (this *MetricNameCountsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&storegatewaypb.MetricNameCountsRequest{")
	s = append(s, "BlockIds: "+fmt.Sprintf("%#v", this.BlockIds)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MetricNameCount) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&storegatewaypb.MetricNameCount{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Count: "+fmt.Sprintf("%#v", this.Count)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *MetricNameCountsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&storegatewaypb.MetricNameCountsResponse{")
	if this.Counts != nil {
		s = append(s, "Counts: "+fmt.Sprintf("%#v", this.Counts)+",\n")
	}
	s = append(s, "BlockIds: "+fmt.Sprintf("%#v", this.BlockIds)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringGateway(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StoreGatewayClient is the client API for StoreGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreGatewayClient interface {
	// Series streams each Series for given label matchers and time range.
	//
	// Series should strictly stream full series after series, optionally split by time. This means that a single frame can contain
	// partition of the single series, but once a new series is started to be streamed it means that no more data will
	// be sent for previous one.
	//
	// Series are sorted.
	Series(ctx context.Context, in *storepb.SeriesRequest, opts ...grpc.CallOption) (StoreGateway_SeriesClient, error)
	// LabelNames returns all label names that is available.
	LabelNames(ctx context.Context, in *storepb.LabelNamesRequest, opts ...grpc.CallOption) (*storepb.LabelNamesResponse, error)
	// LabelValues returns all label values for given label name.
	LabelValues(ctx context.Context, in *storepb.LabelValuesRequest, opts ...grpc.CallOption) (*storepb.LabelValuesResponse, error)
	// SearchLabelNames streams label names matching the search filter.
	SearchLabelNames(ctx context.Context, in *storepb.SearchLabelNamesRequest, opts ...grpc.CallOption) (StoreGateway_SearchLabelNamesClient, error)
	// SearchLabelValues streams label values for the given label name matching the search filter.
	SearchLabelValues(ctx context.Context, in *storepb.SearchLabelValuesRequest, opts ...grpc.CallOption) (StoreGateway_SearchLabelValuesClient, error)
	// MetricNameCounts returns every metric name's series count in the given blocks, read from the blocks'
	// index-headers. Experimental: the caller is responsible for asking only for blocks that share no series.
	MetricNameCounts(ctx context.Context, in *MetricNameCountsRequest, opts ...grpc.CallOption) (*MetricNameCountsResponse, error)
}

type storeGatewayClient struct {
	cc *grpc.ClientConn
}

func NewStoreGatewayClient(cc *grpc.ClientConn) StoreGatewayClient {
	return &storeGatewayClient{cc}
}

func (c *storeGatewayClient) Series(ctx context.Context, in *storepb.SeriesRequest, opts ...grpc.CallOption) (StoreGateway_SeriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreGateway_serviceDesc.Streams[0], "/gatewaypb.StoreGateway/Series", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeGatewaySeriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoreGateway_SeriesClient interface {
	Recv() (*storepb.SeriesResponse, error)
	grpc.ClientStream
}

type storeGatewaySeriesClient struct {
	grpc.ClientStream
}

func (x *storeGatewaySeriesClient) Recv() (*storepb.SeriesResponse, error) {
	m := new(storepb.SeriesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeGatewayClient) LabelNames(ctx context.Context, in *storepb.LabelNamesRequest, opts ...grpc.CallOption) (*storepb.LabelNamesResponse, error) {
	out := new(storepb.LabelNamesResponse)
	err := c.cc.Invoke(ctx, "/gatewaypb.StoreGateway/LabelNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeGatewayClient) LabelValues(ctx context.Context, in *storepb.LabelValuesRequest, opts ...grpc.CallOption) (*storepb.LabelValuesResponse, error) {
	out := new(storepb.LabelValuesResponse)
	err := c.cc.Invoke(ctx, "/gatewaypb.StoreGateway/LabelValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeGatewayClient) SearchLabelNames(ctx context.Context, in *storepb.SearchLabelNamesRequest, opts ...grpc.CallOption) (StoreGateway_SearchLabelNamesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreGateway_serviceDesc.Streams[1], "/gatewaypb.StoreGateway/SearchLabelNames", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeGatewaySearchLabelNamesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoreGateway_SearchLabelNamesClient interface {
	Recv() (*storepb.SearchResultBatch, error)
	grpc.ClientStream
}

type storeGatewaySearchLabelNamesClient struct {
	grpc.ClientStream
}

func (x *storeGatewaySearchLabelNamesClient) Recv() (*storepb.SearchResultBatch, error) {
	m := new(storepb.SearchResultBatch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeGatewayClient) SearchLabelValues(ctx context.Context, in *storepb.SearchLabelValuesRequest, opts ...grpc.CallOption) (StoreGateway_SearchLabelValuesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StoreGateway_serviceDesc.Streams[2], "/gatewaypb.StoreGateway/SearchLabelValues", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeGatewaySearchLabelValuesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoreGateway_SearchLabelValuesClient interface {
	Recv() (*storepb.SearchResultBatch, error)
	grpc.ClientStream
}

type storeGatewaySearchLabelValuesClient struct {
	grpc.ClientStream
}

func (x *storeGatewaySearchLabelValuesClient) Recv() (*storepb.SearchResultBatch, error) {
	m := new(storepb.SearchResultBatch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeGatewayClient) MetricNameCounts(ctx context.Context, in *MetricNameCountsRequest, opts ...grpc.CallOption) (*MetricNameCountsResponse, error) {
	out := new(MetricNameCountsResponse)
	err := c.cc.Invoke(ctx, "/gatewaypb.StoreGateway/MetricNameCounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreGatewayServer is the server API for StoreGateway service.
type StoreGatewayServer interface {
	// Series streams each Series for given label matchers and time range.
	//
	// Series should strictly stream full series after series, optionally split by time. This means that a single frame can contain
	// partition of the single series, but once a new series is started to be streamed it means that no more data will
	// be sent for previous one.
	//
	// Series are sorted.
	Series(*storepb.SeriesRequest, StoreGateway_SeriesServer) error
	// LabelNames returns all label names that is available.
	LabelNames(context.Context, *storepb.LabelNamesRequest) (*storepb.LabelNamesResponse, error)
	// LabelValues returns all label values for given label name.
	LabelValues(context.Context, *storepb.LabelValuesRequest) (*storepb.LabelValuesResponse, error)
	// SearchLabelNames streams label names matching the search filter.
	SearchLabelNames(*storepb.SearchLabelNamesRequest, StoreGateway_SearchLabelNamesServer) error
	// SearchLabelValues streams label values for the given label name matching the search filter.
	SearchLabelValues(*storepb.SearchLabelValuesRequest, StoreGateway_SearchLabelValuesServer) error
	// MetricNameCounts returns every metric name's series count in the given blocks, read from the blocks'
	// index-headers. Experimental: the caller is responsible for asking only for blocks that share no series.
	MetricNameCounts(context.Context, *MetricNameCountsRequest) (*MetricNameCountsResponse, error)
}

// UnimplementedStoreGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedStoreGatewayServer struct {
}

func (*UnimplementedStoreGatewayServer) Series(req *storepb.SeriesRequest, srv StoreGateway_SeriesServer) error {
	return status.Errorf(codes.Unimplemented, "method Series not implemented")
}
func (*UnimplementedStoreGatewayServer) LabelNames(ctx context.Context, req *storepb.LabelNamesRequest) (*storepb.LabelNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LabelNames not implemented")
}
func (*UnimplementedStoreGatewayServer) LabelValues(ctx context.Context, req *storepb.LabelValuesRequest) (*storepb.LabelValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LabelValues not implemented")
}
func (*UnimplementedStoreGatewayServer) SearchLabelNames(req *storepb.SearchLabelNamesRequest, srv StoreGateway_SearchLabelNamesServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchLabelNames not implemented")
}
func (*UnimplementedStoreGatewayServer) SearchLabelValues(req *storepb.SearchLabelValuesRequest, srv StoreGateway_SearchLabelValuesServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchLabelValues not implemented")
}
func (*UnimplementedStoreGatewayServer) MetricNameCounts(ctx context.Context, req *MetricNameCountsRequest) (*MetricNameCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MetricNameCounts not implemented")
}

func RegisterStoreGatewayServer(s *grpc.Server, srv StoreGatewayServer) {
	s.RegisterService(&_StoreGateway_serviceDesc, srv)
}

func _StoreGateway_Series_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(storepb.SeriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreGatewayServer).Series(m, &storeGatewaySeriesServer{stream})
}

type StoreGateway_SeriesServer interface {
	Send(*storepb.SeriesResponse) error
	grpc.ServerStream
}

type storeGatewaySeriesServer struct {
	grpc.ServerStream
}

func (x *storeGatewaySeriesServer) Send(m *storepb.SeriesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StoreGateway_LabelNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(storepb.LabelNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreGatewayServer).LabelNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatewaypb.StoreGateway/LabelNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreGatewayServer).LabelNames(ctx, req.(*storepb.LabelNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreGateway_LabelValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(storepb.LabelValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreGatewayServer).LabelValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatewaypb.StoreGateway/LabelValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreGatewayServer).LabelValues(ctx, req.(*storepb.LabelValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreGateway_SearchLabelNames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(storepb.SearchLabelNamesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreGatewayServer).SearchLabelNames(m, &storeGatewaySearchLabelNamesServer{stream})
}

type StoreGateway_SearchLabelNamesServer interface {
	Send(*storepb.SearchResultBatch) error
	grpc.ServerStream
}

type storeGatewaySearchLabelNamesServer struct {
	grpc.ServerStream
}

func (x *storeGatewaySearchLabelNamesServer) Send(m *storepb.SearchResultBatch) error {
	return x.ServerStream.SendMsg(m)
}

func _StoreGateway_SearchLabelValues_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(storepb.SearchLabelValuesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreGatewayServer).SearchLabelValues(m, &storeGatewaySearchLabelValuesServer{stream})
}

type StoreGateway_SearchLabelValuesServer interface {
	Send(*storepb.SearchResultBatch) error
	grpc.ServerStream
}

type storeGatewaySearchLabelValuesServer struct {
	grpc.ServerStream
}

func (x *storeGatewaySearchLabelValuesServer) Send(m *storepb.SearchResultBatch) error {
	return x.ServerStream.SendMsg(m)
}

func _StoreGateway_MetricNameCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricNameCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreGatewayServer).MetricNameCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gatewaypb.StoreGateway/MetricNameCounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreGatewayServer).MetricNameCounts(ctx, req.(*MetricNameCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreGateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gatewaypb.StoreGateway",
	HandlerType: (*StoreGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LabelNames",
			Handler:    _StoreGateway_LabelNames_Handler,
		},
		{
			MethodName: "LabelValues",
			Handler:    _StoreGateway_LabelValues_Handler,
		},
		{
			MethodName: "MetricNameCounts",
			Handler:    _StoreGateway_MetricNameCounts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Series",
			Handler:       _StoreGateway_Series_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchLabelNames",
			Handler:       _StoreGateway_SearchLabelNames_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchLabelValues",
			Handler:       _StoreGateway_SearchLabelValues_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}

func (m *MetricNameCountsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricNameCountsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetricNameCountsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BlockIds) > 0 {
		for iNdEx := len(m.BlockIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockIds[iNdEx])
			copy(dAtA[i:], m.BlockIds[iNdEx])
			i = encodeVarintGateway(dAtA, i, uint64(len(m.BlockIds[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MetricNameCount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricNameCount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetricNameCount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintGateway(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGateway(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MetricNameCountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricNameCountsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MetricNameCountsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BlockIds) > 0 {
		for iNdEx := len(m.BlockIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BlockIds[iNdEx])
			copy(dAtA[i:], m.BlockIds[iNdEx])
			i = encodeVarintGateway(dAtA, i, uint64(len(m.BlockIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Counts) > 0 {
		for iNdEx := len(m.Counts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Counts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGateway(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGateway(dAtA []byte, offset int, v uint64) int {
	offset -= sovGateway(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MetricNameCountsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BlockIds) > 0 {
		for _, s := range m.BlockIds {
			l = len(s)
			n += 1 + l + sovGateway(uint64(l))
		}
	}
	return n
}

func (m *MetricNameCount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGateway(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovGateway(uint64(m.Count))
	}
	return n
}

func (m *MetricNameCountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Counts) > 0 {
		for _, e := range m.Counts {
			l = e.Size()
			n += 1 + l + sovGateway(uint64(l))
		}
	}
	if len(m.BlockIds) > 0 {
		for _, s := range m.BlockIds {
			l = len(s)
			n += 1 + l + sovGateway(uint64(l))
		}
	}
	return n
}

func sovGateway(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGateway(x uint64) (n int) {
	return sovGateway(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *MetricNameCountsRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MetricNameCountsRequest{`,
		`BlockIds:` + fmt.Sprintf("%v", this.BlockIds) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MetricNameCount) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&MetricNameCount{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Count:` + fmt.Sprintf("%v", this.Count) + `,`,
		`}`,
	}, "")
	return s
}
func (this *MetricNameCountsResponse) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForCounts := "[]*MetricNameCount{"
	for _, f := range this.Counts {
		repeatedStringForCounts += strings.Replace(f.String(), "MetricNameCount", "MetricNameCount", 1) + ","
	}
	repeatedStringForCounts += "}"
	s := strings.Join([]string{`&MetricNameCountsResponse{`,
		`Counts:` + repeatedStringForCounts + `,`,
		`BlockIds:` + fmt.Sprintf("%v", this.BlockIds) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGateway(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *MetricNameCountsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricNameCountsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricNameCountsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockIds = append(m.BlockIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricNameCount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricNameCount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricNameCount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricNameCountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricNameCountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricNameCountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Counts = append(m.Counts, &MetricNameCount{})
			if err := m.Counts[len(m.Counts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGateway
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGateway
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockIds = append(m.BlockIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGateway(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGateway
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGateway(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGateway
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGateway
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGateway
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGateway
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGateway
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGateway        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGateway          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGateway = fmt.Errorf("proto: unexpected end of group")
)
