// Code generated by wiresmith. DO NOT EDIT.
// source: github.com/grafana/mimir/pkg/storegateway/storegatewaypb/gateway.proto

package storegatewaypb

import (
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	"reflect"
	"unsafe"
)

// Cold companion utilities for github.com/grafana/mimir/pkg/storegateway/storegatewaypb/gateway.proto.
//
// This file holds two cold concerns merged into one compilation unit:
//
//   - Reflection / registration glue: the per-message ProtoReflect()
//     methods, the per-enum Descriptor()/Type()/Number() methods, the
//     embedded FileDescriptorProto blob, the file_*_msgTypes /
//     file_*_enumTypes arrays, and the init() that registers everything
//     with protoregistry.GlobalFiles and protoregistry.GlobalTypes.
//   - The per-message String() debug dumps (hand-rolled, deterministic,
//     non-reflection — see compiler/generator/emit_string.go).
//
// None of these are called on the marshal / unmarshal / size hot path.
//
// Why a separate file? Putting this code (plus its descriptorpb /
// protoreflect / protoimpl imports — ~64KB of descriptorpb alone, ~377KB
// added to __TEXT overall) next to the hot Marshal/Unmarshal functions
// caused a measured +7–14% regression on otlp benchmarks (UnmarshalProfiles
// regressed by +12.6%) due to icache / iTLB / BTB pressure: the hot
// loops themselves were unchanged, but cold reflection code interleaved
// in the same compilation unit shifted hot functions onto different
// cache sets and pushed them ~131KB further into the binary. Emitting
// the cold half here, in its own .o, lets the linker place it away
// from the hot half and recovers that throughput. reflect and String()
// are both cold and were already split out, so merging them (cold→cold)
// preserves the rationale while halving the companion-file count.
//
// See compiler/generator/emit_registration.go for the full rationale
// and the benchmark methodology. DO NOT inline this file's contents
// back into the main .pb.go without re-measuring.

const file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_rawDesc = "" +
	"\x0a\x46\x67\x69\x74\x68\x75\x62\x2e\x63\x6f\x6d\x2f\x67\x72\x61\x66\x61\x6e\x61\x2f\x6d\x69\x6d\x69\x72\x2f\x70\x6b\x67\x2f\x73\x74\x6f\x72\x65\x67\x61\x74\x65" +
	"\x77\x61\x79\x2f\x73\x74\x6f\x72\x65\x67\x61\x74\x65\x77\x61\x79\x70\x62\x2f\x67\x61\x74\x65\x77\x61\x79\x2e\x70\x72\x6f\x74\x6f\x12\x09\x67\x61\x74\x65\x77\x61" +
	"\x79\x70\x62\x1a\x3b\x67\x69\x74\x68\x75\x62\x2e\x63\x6f\x6d\x2f\x67\x72\x61\x66\x61\x6e\x61\x2f\x6d\x69\x6d\x69\x72\x2f\x70\x6b\x67\x2f\x73\x74\x6f\x72\x65\x67" +
	"\x61\x74\x65\x77\x61\x79\x2f\x73\x74\x6f\x72\x65\x70\x62\x2f\x72\x70\x63\x2e\x70\x72\x6f\x74\x6f\x42\x10\x5a\x0e\x73\x74\x6f\x72\x65\x67\x61\x74\x65\x77\x61\x79" +
	"\x70\x62\x62\x06\x70\x72\x6f\x74\x6f\x33"

var file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_fd protoreflect.FileDescriptor

var file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_goTypes = []any{}

var file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_init() }

func file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_init() {
	if file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_fd != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_rawDesc), len(file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_goTypes,
		DependencyIndexes: file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_depIdxs,
	}.Build()
	file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_fd = out.File
	file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_goTypes = nil
	file_github_com_grafana_mimir_pkg_storegateway_storegatewaypb_gateway_proto_depIdxs = nil
}
