# SPDX-License-Identifier: AGPL-3.0-only

FROM golang:1.17.3-buster
RUN apt-get update && apt-get install -y libpcap-dev

VOLUME /mimir
WORKDIR /mimir/tools/trafficdump

ENV GOOS=linux
ENV GOARCH=amd64

CMD go build -v -o trafficdump.linux .

