// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cache.proto

package cache

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	querierpb "github.com/grafana/mimir/pkg/querier/querierpb"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AnnotationType int32

const (
	WARNING AnnotationType = 0
	INFO    AnnotationType = 1
)

var AnnotationType_name = map[int32]string{
	0: "WARNING",
	1: "INFO",
}

var AnnotationType_value = map[string]int32{
	"WARNING": 0,
	"INFO":    1,
}

func (AnnotationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{0}
}

type Annotation struct {
	Type    AnnotationType `protobuf:"varint,1,opt,name=type,proto3,enum=rangevectorsplittingcache.AnnotationType" json:"type,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Annotation) Reset()      { *m = Annotation{} }
func (*Annotation) ProtoMessage() {}
func (*Annotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{0}
}
func (m *Annotation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Annotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Annotation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Annotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Annotation.Merge(m, src)
}
func (m *Annotation) XXX_Size() int {
	return m.Size()
}
func (m *Annotation) XXX_DiscardUnknown() {
	xxx_messageInfo_Annotation.DiscardUnknown(m)
}

var xxx_messageInfo_Annotation proto.InternalMessageInfo

type CachedSeries struct {
	// cacheKey contains the non-hashed cache key, to detect hash collision.
	CacheKey       string                     `protobuf:"bytes,1,opt,name=cacheKey,proto3" json:"cacheKey,omitempty"`
	Start          int64                      `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End            int64                      `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	SeriesMetadata []querierpb.SeriesMetadata `protobuf:"bytes,4,rep,name=series_metadata,json=seriesMetadata,proto3" json:"series_metadata"`
	Results        []byte                     `protobuf:"bytes,5,opt,name=results,proto3" json:"results,omitempty"`
	Annotations    []Annotation               `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations"`
}

func (m *CachedSeries) Reset()      { *m = CachedSeries{} }
func (*CachedSeries) ProtoMessage() {}
func (*CachedSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{1}
}
func (m *CachedSeries) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CachedSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CachedSeries.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CachedSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CachedSeries.Merge(m, src)
}
func (m *CachedSeries) XXX_Size() int {
	return m.Size()
}
func (m *CachedSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_CachedSeries.DiscardUnknown(m)
}

var xxx_messageInfo_CachedSeries proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("rangevectorsplittingcache.AnnotationType", AnnotationType_name, AnnotationType_value)
	proto.RegisterType((*Annotation)(nil), "rangevectorsplittingcache.Annotation")
	proto.RegisterType((*CachedSeries)(nil), "rangevectorsplittingcache.CachedSeries")
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_5fca3b110c9bbf3a) }

var fileDescriptor_5fca3b110c9bbf3a = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4f, 0x8b, 0xd3, 0x40,
	0x1c, 0x9d, 0xd9, 0xa4, 0xfb, 0x67, 0xb2, 0xd4, 0x32, 0xec, 0x21, 0xdb, 0xc3, 0x18, 0x16, 0xc4,
	0xe8, 0x21, 0x81, 0x7a, 0x55, 0xa4, 0x15, 0xd4, 0x22, 0xad, 0x10, 0x05, 0xc1, 0x8b, 0x4c, 0xd3,
	0x71, 0x1a, 0x6c, 0x32, 0x71, 0x66, 0x2a, 0xf4, 0xe6, 0xc5, 0xbb, 0x1f, 0xc3, 0x8f, 0xd2, 0x63,
	0x8f, 0x3d, 0x89, 0x49, 0x2f, 0x1e, 0xfb, 0x11, 0x24, 0x93, 0xa6, 0xda, 0x83, 0xb0, 0xa7, 0xbc,
	0xf7, 0xe3, 0xf7, 0xde, 0xef, 0xe5, 0x0d, 0x72, 0x62, 0x1a, 0xcf, 0x58, 0x90, 0x4b, 0xa1, 0x05,
	0xbe, 0x96, 0x34, 0xe3, 0xec, 0x0b, 0x8b, 0xb5, 0x90, 0x2a, 0x9f, 0x27, 0x5a, 0x27, 0x19, 0x37,
	0x0b, 0xdd, 0xc7, 0x3c, 0xd1, 0xb3, 0xc5, 0x24, 0x88, 0x45, 0x1a, 0x72, 0x49, 0x3f, 0xd2, 0x8c,
	0x86, 0x69, 0x92, 0x26, 0x32, 0xcc, 0x3f, 0xf1, 0xf0, 0xf3, 0x82, 0xc9, 0x84, 0xc9, 0xe6, 0x9b,
	0x4f, 0x1a, 0x54, 0x1b, 0x77, 0xaf, 0xb8, 0xe0, 0xc2, 0xc0, 0xb0, 0x42, 0xf5, 0xf4, 0x86, 0x21,
	0xd4, 0xcf, 0x32, 0xa1, 0xa9, 0x4e, 0x44, 0x86, 0x9f, 0x20, 0x5b, 0x2f, 0x73, 0xe6, 0x42, 0x0f,
	0xfa, 0xed, 0xde, 0x83, 0xe0, 0xbf, 0x59, 0x82, 0xbf, 0xa2, 0xb7, 0xcb, 0x9c, 0x45, 0x46, 0x86,
	0x5d, 0x74, 0x96, 0x32, 0xa5, 0x28, 0x67, 0xee, 0x89, 0x07, 0xfd, 0x8b, 0xa8, 0xa1, 0x37, 0xdf,
	0x4e, 0xd0, 0xe5, 0xb3, 0x4a, 0x38, 0x7d, 0x53, 0x65, 0x52, 0xb8, 0x8b, 0xce, 0x8d, 0xd1, 0x2b,
	0xb6, 0x34, 0xd7, 0x2e, 0xa2, 0x03, 0xc7, 0x57, 0xa8, 0xa5, 0x34, 0x95, 0xda, 0x98, 0x58, 0x51,
	0x4d, 0x70, 0x07, 0x59, 0x2c, 0x9b, 0xba, 0x96, 0x99, 0x55, 0x10, 0xbf, 0x44, 0x77, 0x94, 0x71,
	0xfb, 0x90, 0x32, 0x4d, 0xa7, 0x54, 0x53, 0xd7, 0xf6, 0x2c, 0xdf, 0xe9, 0x5d, 0x07, 0x87, 0x12,
	0x82, 0xfa, 0xde, 0x68, 0xbf, 0x30, 0xb0, 0x57, 0x3f, 0xef, 0x82, 0xa8, 0xad, 0x8e, 0xa6, 0x55,
	0x70, 0xc9, 0xd4, 0x62, 0xae, 0x95, 0xdb, 0xf2, 0xa0, 0x7f, 0x19, 0x35, 0x14, 0x8f, 0x90, 0x43,
	0x0f, 0xbf, 0xaa, 0xdc, 0x53, 0xe3, 0x7f, 0xef, 0x56, 0xc5, 0xec, 0x6f, 0xfd, 0xab, 0x7f, 0x78,
	0x1f, 0xb5, 0x8f, 0x9b, 0xc3, 0x0e, 0x3a, 0x7b, 0xd7, 0x8f, 0xc6, 0xc3, 0xf1, 0x8b, 0x0e, 0xc0,
	0xe7, 0xc8, 0x1e, 0x8e, 0x9f, 0xbf, 0xee, 0xc0, 0xc1, 0xd3, 0x55, 0x41, 0xc0, 0xba, 0x20, 0x60,
	0x53, 0x10, 0xb0, 0x2b, 0x08, 0xfc, 0x5a, 0x12, 0xf8, 0xa3, 0x24, 0x70, 0x55, 0x12, 0xb8, 0x2e,
	0x09, 0xfc, 0x55, 0x12, 0xf8, 0xbb, 0x24, 0x60, 0x57, 0x12, 0xf8, 0x7d, 0x4b, 0xc0, 0x7a, 0x4b,
	0xc0, 0x66, 0x4b, 0xc0, 0xfb, 0x96, 0xc9, 0x31, 0x39, 0x35, 0xef, 0xfb, 0xe8, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x66, 0x31, 0xe2, 0xad, 0x5d, 0x02, 0x00, 0x00,
}

func (x AnnotationType) String() string {
	s, ok := AnnotationType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Annotation) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Annotation)
	if !ok {
		that2, ok := that.(Annotation)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	return true
}
func (this *CachedSeries) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*CachedSeries)
	if !ok {
		that2, ok := that.(CachedSeries)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CacheKey != that1.CacheKey {
		return false
	}
	if this.Start != that1.Start {
		return false
	}
	if this.End != that1.End {
		return false
	}
	if len(this.SeriesMetadata) != len(that1.SeriesMetadata) {
		return false
	}
	for i := range this.SeriesMetadata {
		if !this.SeriesMetadata[i].Equal(&that1.SeriesMetadata[i]) {
			return false
		}
	}
	if !bytes.Equal(this.Results, that1.Results) {
		return false
	}
	if len(this.Annotations) != len(that1.Annotations) {
		return false
	}
	for i := range this.Annotations {
		if !this.Annotations[i].Equal(&that1.Annotations[i]) {
			return false
		}
	}
	return true
}
func (this *Annotation) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&cache.Annotation{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Message: "+fmt.Sprintf("%#v", this.Message)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *CachedSeries) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&cache.CachedSeries{")
	s = append(s, "CacheKey: "+fmt.Sprintf("%#v", this.CacheKey)+",\n")
	s = append(s, "Start: "+fmt.Sprintf("%#v", this.Start)+",\n")
	s = append(s, "End: "+fmt.Sprintf("%#v", this.End)+",\n")
	if this.SeriesMetadata != nil {
		vs := make([]querierpb.SeriesMetadata, len(this.SeriesMetadata))
		for i := range vs {
			vs[i] = this.SeriesMetadata[i]
		}
		s = append(s, "SeriesMetadata: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "Results: "+fmt.Sprintf("%#v", this.Results)+",\n")
	if this.Annotations != nil {
		vs := make([]Annotation, len(this.Annotations))
		for i := range vs {
			vs[i] = this.Annotations[i]
		}
		s = append(s, "Annotations: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringCache(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Annotation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Annotation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Annotation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintCache(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintCache(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CachedSeries) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CachedSeries) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CachedSeries) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Annotations) > 0 {
		for iNdEx := len(m.Annotations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Annotations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCache(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Results) > 0 {
		i -= len(m.Results)
		copy(dAtA[i:], m.Results)
		i = encodeVarintCache(dAtA, i, uint64(len(m.Results)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SeriesMetadata) > 0 {
		for iNdEx := len(m.SeriesMetadata) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SeriesMetadata[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintCache(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.End != 0 {
		i = encodeVarintCache(dAtA, i, uint64(m.End))
		i--
		dAtA[i] = 0x18
	}
	if m.Start != 0 {
		i = encodeVarintCache(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x10
	}
	if len(m.CacheKey) > 0 {
		i -= len(m.CacheKey)
		copy(dAtA[i:], m.CacheKey)
		i = encodeVarintCache(dAtA, i, uint64(len(m.CacheKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCache(dAtA []byte, offset int, v uint64) int {
	offset -= sovCache(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Annotation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovCache(uint64(m.Type))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovCache(uint64(l))
	}
	return n
}

func (m *CachedSeries) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CacheKey)
	if l > 0 {
		n += 1 + l + sovCache(uint64(l))
	}
	if m.Start != 0 {
		n += 1 + sovCache(uint64(m.Start))
	}
	if m.End != 0 {
		n += 1 + sovCache(uint64(m.End))
	}
	if len(m.SeriesMetadata) > 0 {
		for _, e := range m.SeriesMetadata {
			l = e.Size()
			n += 1 + l + sovCache(uint64(l))
		}
	}
	l = len(m.Results)
	if l > 0 {
		n += 1 + l + sovCache(uint64(l))
	}
	if len(m.Annotations) > 0 {
		for _, e := range m.Annotations {
			l = e.Size()
			n += 1 + l + sovCache(uint64(l))
		}
	}
	return n
}

func sovCache(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCache(x uint64) (n int) {
	return sovCache(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Annotation) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Annotation{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Message:` + fmt.Sprintf("%v", this.Message) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CachedSeries) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForSeriesMetadata := "[]SeriesMetadata{"
	for _, f := range this.SeriesMetadata {
		repeatedStringForSeriesMetadata += fmt.Sprintf("%v", f) + ","
	}
	repeatedStringForSeriesMetadata += "}"
	repeatedStringForAnnotations := "[]Annotation{"
	for _, f := range this.Annotations {
		repeatedStringForAnnotations += strings.Replace(strings.Replace(f.String(), "Annotation", "Annotation", 1), `&`, ``, 1) + ","
	}
	repeatedStringForAnnotations += "}"
	s := strings.Join([]string{`&CachedSeries{`,
		`CacheKey:` + fmt.Sprintf("%v", this.CacheKey) + `,`,
		`Start:` + fmt.Sprintf("%v", this.Start) + `,`,
		`End:` + fmt.Sprintf("%v", this.End) + `,`,
		`SeriesMetadata:` + repeatedStringForSeriesMetadata + `,`,
		`Results:` + fmt.Sprintf("%v", this.Results) + `,`,
		`Annotations:` + repeatedStringForAnnotations + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringCache(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Annotation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCache
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Annotation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Annotation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= AnnotationType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCache
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCache
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCache(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCache
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CachedSeries) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCache
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CachedSeries: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CachedSeries: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CacheKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCache
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCache
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CacheKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			m.End = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.End |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCache
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCache
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SeriesMetadata = append(m.SeriesMetadata, querierpb.SeriesMetadata{})
			if err := m.SeriesMetadata[len(m.SeriesMetadata)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Results", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCache
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCache
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Results = append(m.Results[:0], dAtA[iNdEx:postIndex]...)
			if m.Results == nil {
				m.Results = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Annotations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCache
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCache
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCache
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Annotations = append(m.Annotations, Annotation{})
			if err := m.Annotations[len(m.Annotations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCache(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCache
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCache(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCache
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCache
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCache
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCache
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCache
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCache
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCache        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCache          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCache = fmt.Errorf("proto: unexpected end of group")
)
