// Code generated by wiresmith. DO NOT EDIT.
// source: github.com/grafana/mimir/pkg/usagetracker/usagetrackerpb/usagetracker.proto

package usagetrackerpb

import (
	"bytes"
)

// Per-message value-comparison methods (Equal + Compare) for github.com/grafana/mimir/pkg/usagetracker/usagetrackerpb/usagetracker.proto.
//
// Equal returns bool; Compare returns -1/0/+1 like bytes.Compare with the
// gogoproto.compare nil/wrong-type preamble. Both are emitted on every
// message; callers that don't use one can rely on Go's dead-code
// elimination to drop the body.
//
// Why a separate file? Equal/Compare are never called from Marshal/Unmarshal/
// Size, but emitting them next to those hot functions in the main .pb.go
// pushed them onto different cache sets and produced a measured ~9% geomean
// regression on OTel benchmarks (UnmarshalMap +14%, MarshalSingleSpan +13%)
// purely from icache / iTLB / BTB pressure. Splitting them into their own
// compilation unit gives the linker freedom to place the cold half away
// from the hot half — same trick the _util.pb.go split uses.
//
// See compiler/generator/emit_compare.go / emit_equal.go for the full
// rationale and the benchmark methodology. DO NOT inline this file's
// contents back into the main .pb.go without re-measuring.

func (this *TrackSeriesRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesRequest)
	if !ok {
		that2, ok := that.(TrackSeriesRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UserID != that1.UserID {
		return false
	}
	if this.Partition != that1.Partition {
		return false
	}
	if len(this.SeriesHashes) != len(that1.SeriesHashes) {
		return false
	}
	for i := range this.SeriesHashes {
		if this.SeriesHashes[i] != that1.SeriesHashes[i] {
			return false
		}
	}
	return true
}

func (this *TrackSeriesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesResponse)
	if !ok {
		that2, ok := that.(TrackSeriesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.RejectedSeriesHashes) != len(that1.RejectedSeriesHashes) {
		return false
	}
	for i := range this.RejectedSeriesHashes {
		if this.RejectedSeriesHashes[i] != that1.RejectedSeriesHashes[i] {
			return false
		}
	}
	return true
}

func (this *TrackSeriesBatchUser) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesBatchUser)
	if !ok {
		that2, ok := that.(TrackSeriesBatchUser)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UserID != that1.UserID {
		return false
	}
	if len(this.SeriesHashes) != len(that1.SeriesHashes) {
		return false
	}
	for i := range this.SeriesHashes {
		if this.SeriesHashes[i] != that1.SeriesHashes[i] {
			return false
		}
	}
	return true
}

func (this *TrackSeriesBatchPartition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesBatchPartition)
	if !ok {
		that2, ok := that.(TrackSeriesBatchPartition)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Partition != that1.Partition {
		return false
	}
	if len(this.Users) != len(that1.Users) {
		return false
	}
	for i := range this.Users {
		if (this.Users[i] == nil) != (that1.Users[i] == nil) {
			return false
		}
		if this.Users[i] != nil && !this.Users[i].Equal(that1.Users[i]) {
			return false
		}
	}
	return true
}

func (this *TrackSeriesBatchRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesBatchRequest)
	if !ok {
		that2, ok := that.(TrackSeriesBatchRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Partitions) != len(that1.Partitions) {
		return false
	}
	for i := range this.Partitions {
		if (this.Partitions[i] == nil) != (that1.Partitions[i] == nil) {
			return false
		}
		if this.Partitions[i] != nil && !this.Partitions[i].Equal(that1.Partitions[i]) {
			return false
		}
	}
	return true
}

func (this *TrackSeriesBatchRejectionUser) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesBatchRejectionUser)
	if !ok {
		that2, ok := that.(TrackSeriesBatchRejectionUser)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UserID != that1.UserID {
		return false
	}
	if len(this.RejectedSeriesHashes) != len(that1.RejectedSeriesHashes) {
		return false
	}
	for i := range this.RejectedSeriesHashes {
		if this.RejectedSeriesHashes[i] != that1.RejectedSeriesHashes[i] {
			return false
		}
	}
	return true
}

func (this *TrackSeriesBatchRejection) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesBatchRejection)
	if !ok {
		that2, ok := that.(TrackSeriesBatchRejection)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Partition != that1.Partition {
		return false
	}
	if len(this.Users) != len(that1.Users) {
		return false
	}
	for i := range this.Users {
		if (this.Users[i] == nil) != (that1.Users[i] == nil) {
			return false
		}
		if this.Users[i] != nil && !this.Users[i].Equal(that1.Users[i]) {
			return false
		}
	}
	return true
}

func (this *TrackSeriesBatchResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TrackSeriesBatchResponse)
	if !ok {
		that2, ok := that.(TrackSeriesBatchResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Rejections) != len(that1.Rejections) {
		return false
	}
	for i := range this.Rejections {
		if (this.Rejections[i] == nil) != (that1.Rejections[i] == nil) {
			return false
		}
		if this.Rejections[i] != nil && !this.Rejections[i].Equal(that1.Rejections[i]) {
			return false
		}
	}
	return true
}

func (this *SeriesCreatedEvent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SeriesCreatedEvent)
	if !ok {
		that2, ok := that.(SeriesCreatedEvent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.UserID != that1.UserID {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if len(this.SeriesHashes) != len(that1.SeriesHashes) {
		return false
	}
	for i := range this.SeriesHashes {
		if this.SeriesHashes[i] != that1.SeriesHashes[i] {
			return false
		}
	}
	return true
}

func (this *SnapshotRecord) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SnapshotRecord)
	if !ok {
		that2, ok := that.(SnapshotRecord)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if len(this.Filenames) != len(that1.Filenames) {
		return false
	}
	for i := range this.Filenames {
		if this.Filenames[i] != that1.Filenames[i] {
			return false
		}
	}
	if this.LastEventOffsetPublishedBeforeSnapshot != that1.LastEventOffsetPublishedBeforeSnapshot {
		return false
	}
	if this.LastSnapshotEventOffset != that1.LastSnapshotEventOffset {
		return false
	}
	return true
}

func (this *SnapshotEvent) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SnapshotEvent)
	if !ok {
		that2, ok := that.(SnapshotEvent)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Timestamp != that1.Timestamp {
		return false
	}
	if this.Filename != that1.Filename {
		return false
	}
	return true
}

func (this *SnapshotFile) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SnapshotFile)
	if !ok {
		that2, ok := that.(SnapshotFile)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Data) != len(that1.Data) {
		return false
	}
	for i := range this.Data {
		if !bytes.Equal(this.Data[i], that1.Data[i]) {
			return false
		}
	}
	return true
}

func (this *GetUsersCloseToLimitRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetUsersCloseToLimitRequest)
	if !ok {
		that2, ok := that.(GetUsersCloseToLimitRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Partition != that1.Partition {
		return false
	}
	return true
}

func (this *GetUsersCloseToLimitResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetUsersCloseToLimitResponse)
	if !ok {
		that2, ok := that.(GetUsersCloseToLimitResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.SortedUserIds) != len(that1.SortedUserIds) {
		return false
	}
	for i := range this.SortedUserIds {
		if this.SortedUserIds[i] != that1.SortedUserIds[i] {
			return false
		}
	}
	if this.Partition != that1.Partition {
		return false
	}
	return true
}

func (this *TrackSeriesRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesRequest)
	if !ok {
		that2, ok := that.(TrackSeriesRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.UserID != that1.UserID {
		if this.UserID < that1.UserID {
			return -1
		}
		return 1
	}
	if this.Partition != that1.Partition {
		if this.Partition < that1.Partition {
			return -1
		}
		return 1
	}
	if len(this.SeriesHashes) != len(that1.SeriesHashes) {
		if len(this.SeriesHashes) < len(that1.SeriesHashes) {
			return -1
		}
		return 1
	}
	for i := range this.SeriesHashes {
		if this.SeriesHashes[i] != that1.SeriesHashes[i] {
			if this.SeriesHashes[i] < that1.SeriesHashes[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}

func (this *TrackSeriesResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesResponse)
	if !ok {
		that2, ok := that.(TrackSeriesResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if len(this.RejectedSeriesHashes) != len(that1.RejectedSeriesHashes) {
		if len(this.RejectedSeriesHashes) < len(that1.RejectedSeriesHashes) {
			return -1
		}
		return 1
	}
	for i := range this.RejectedSeriesHashes {
		if this.RejectedSeriesHashes[i] != that1.RejectedSeriesHashes[i] {
			if this.RejectedSeriesHashes[i] < that1.RejectedSeriesHashes[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}

func (this *TrackSeriesBatchUser) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesBatchUser)
	if !ok {
		that2, ok := that.(TrackSeriesBatchUser)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.UserID != that1.UserID {
		if this.UserID < that1.UserID {
			return -1
		}
		return 1
	}
	if len(this.SeriesHashes) != len(that1.SeriesHashes) {
		if len(this.SeriesHashes) < len(that1.SeriesHashes) {
			return -1
		}
		return 1
	}
	for i := range this.SeriesHashes {
		if this.SeriesHashes[i] != that1.SeriesHashes[i] {
			if this.SeriesHashes[i] < that1.SeriesHashes[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}

func (this *TrackSeriesBatchPartition) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesBatchPartition)
	if !ok {
		that2, ok := that.(TrackSeriesBatchPartition)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Partition != that1.Partition {
		if this.Partition < that1.Partition {
			return -1
		}
		return 1
	}
	if len(this.Users) != len(that1.Users) {
		if len(this.Users) < len(that1.Users) {
			return -1
		}
		return 1
	}
	for i := range this.Users {
		if (this.Users[i] == nil) != (that1.Users[i] == nil) {
			if this.Users[i] == nil {
				return -1
			}
			return 1
		}
		if this.Users[i] != nil {
			if c := this.Users[i].Compare(that1.Users[i]); c != 0 {
				return c
			}
		}
	}
	return 0
}

func (this *TrackSeriesBatchRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesBatchRequest)
	if !ok {
		that2, ok := that.(TrackSeriesBatchRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if len(this.Partitions) != len(that1.Partitions) {
		if len(this.Partitions) < len(that1.Partitions) {
			return -1
		}
		return 1
	}
	for i := range this.Partitions {
		if (this.Partitions[i] == nil) != (that1.Partitions[i] == nil) {
			if this.Partitions[i] == nil {
				return -1
			}
			return 1
		}
		if this.Partitions[i] != nil {
			if c := this.Partitions[i].Compare(that1.Partitions[i]); c != 0 {
				return c
			}
		}
	}
	return 0
}

func (this *TrackSeriesBatchRejectionUser) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesBatchRejectionUser)
	if !ok {
		that2, ok := that.(TrackSeriesBatchRejectionUser)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.UserID != that1.UserID {
		if this.UserID < that1.UserID {
			return -1
		}
		return 1
	}
	if len(this.RejectedSeriesHashes) != len(that1.RejectedSeriesHashes) {
		if len(this.RejectedSeriesHashes) < len(that1.RejectedSeriesHashes) {
			return -1
		}
		return 1
	}
	for i := range this.RejectedSeriesHashes {
		if this.RejectedSeriesHashes[i] != that1.RejectedSeriesHashes[i] {
			if this.RejectedSeriesHashes[i] < that1.RejectedSeriesHashes[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}

func (this *TrackSeriesBatchRejection) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesBatchRejection)
	if !ok {
		that2, ok := that.(TrackSeriesBatchRejection)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Partition != that1.Partition {
		if this.Partition < that1.Partition {
			return -1
		}
		return 1
	}
	if len(this.Users) != len(that1.Users) {
		if len(this.Users) < len(that1.Users) {
			return -1
		}
		return 1
	}
	for i := range this.Users {
		if (this.Users[i] == nil) != (that1.Users[i] == nil) {
			if this.Users[i] == nil {
				return -1
			}
			return 1
		}
		if this.Users[i] != nil {
			if c := this.Users[i].Compare(that1.Users[i]); c != 0 {
				return c
			}
		}
	}
	return 0
}

func (this *TrackSeriesBatchResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*TrackSeriesBatchResponse)
	if !ok {
		that2, ok := that.(TrackSeriesBatchResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if len(this.Rejections) != len(that1.Rejections) {
		if len(this.Rejections) < len(that1.Rejections) {
			return -1
		}
		return 1
	}
	for i := range this.Rejections {
		if (this.Rejections[i] == nil) != (that1.Rejections[i] == nil) {
			if this.Rejections[i] == nil {
				return -1
			}
			return 1
		}
		if this.Rejections[i] != nil {
			if c := this.Rejections[i].Compare(that1.Rejections[i]); c != 0 {
				return c
			}
		}
	}
	return 0
}

func (this *SeriesCreatedEvent) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SeriesCreatedEvent)
	if !ok {
		that2, ok := that.(SeriesCreatedEvent)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.UserID != that1.UserID {
		if this.UserID < that1.UserID {
			return -1
		}
		return 1
	}
	if this.Timestamp != that1.Timestamp {
		if this.Timestamp < that1.Timestamp {
			return -1
		}
		return 1
	}
	if len(this.SeriesHashes) != len(that1.SeriesHashes) {
		if len(this.SeriesHashes) < len(that1.SeriesHashes) {
			return -1
		}
		return 1
	}
	for i := range this.SeriesHashes {
		if this.SeriesHashes[i] != that1.SeriesHashes[i] {
			if this.SeriesHashes[i] < that1.SeriesHashes[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}

func (this *SnapshotRecord) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SnapshotRecord)
	if !ok {
		that2, ok := that.(SnapshotRecord)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Timestamp != that1.Timestamp {
		if this.Timestamp < that1.Timestamp {
			return -1
		}
		return 1
	}
	if len(this.Filenames) != len(that1.Filenames) {
		if len(this.Filenames) < len(that1.Filenames) {
			return -1
		}
		return 1
	}
	for i := range this.Filenames {
		if this.Filenames[i] != that1.Filenames[i] {
			if this.Filenames[i] < that1.Filenames[i] {
				return -1
			}
			return 1
		}
	}
	if this.LastEventOffsetPublishedBeforeSnapshot != that1.LastEventOffsetPublishedBeforeSnapshot {
		if this.LastEventOffsetPublishedBeforeSnapshot < that1.LastEventOffsetPublishedBeforeSnapshot {
			return -1
		}
		return 1
	}
	if this.LastSnapshotEventOffset != that1.LastSnapshotEventOffset {
		if this.LastSnapshotEventOffset < that1.LastSnapshotEventOffset {
			return -1
		}
		return 1
	}
	return 0
}

func (this *SnapshotEvent) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SnapshotEvent)
	if !ok {
		that2, ok := that.(SnapshotEvent)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Timestamp != that1.Timestamp {
		if this.Timestamp < that1.Timestamp {
			return -1
		}
		return 1
	}
	if this.Filename != that1.Filename {
		if this.Filename < that1.Filename {
			return -1
		}
		return 1
	}
	return 0
}

func (this *SnapshotFile) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SnapshotFile)
	if !ok {
		that2, ok := that.(SnapshotFile)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if len(this.Data) != len(that1.Data) {
		if len(this.Data) < len(that1.Data) {
			return -1
		}
		return 1
	}
	for i := range this.Data {
		if c := bytes.Compare(this.Data[i], that1.Data[i]); c != 0 {
			return c
		}
	}
	return 0
}

func (this *GetUsersCloseToLimitRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*GetUsersCloseToLimitRequest)
	if !ok {
		that2, ok := that.(GetUsersCloseToLimitRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Partition != that1.Partition {
		if this.Partition < that1.Partition {
			return -1
		}
		return 1
	}
	return 0
}

func (this *GetUsersCloseToLimitResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*GetUsersCloseToLimitResponse)
	if !ok {
		that2, ok := that.(GetUsersCloseToLimitResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if len(this.SortedUserIds) != len(that1.SortedUserIds) {
		if len(this.SortedUserIds) < len(that1.SortedUserIds) {
			return -1
		}
		return 1
	}
	for i := range this.SortedUserIds {
		if this.SortedUserIds[i] != that1.SortedUserIds[i] {
			if this.SortedUserIds[i] < that1.SortedUserIds[i] {
				return -1
			}
			return 1
		}
	}
	if this.Partition != that1.Partition {
		if this.Partition < that1.Partition {
			return -1
		}
		return 1
	}
	return 0
}
