// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: functions.proto

package functions

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
	strconv "strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Function int32

const (
	FUNCTION_UNKNOWN                      Function = 0
	FUNCTION_ABS                          Function = 1
	FUNCTION_ABSENT                       Function = 2
	FUNCTION_ABSENT_OVER_TIME             Function = 3
	FUNCTION_ACOS                         Function = 4
	FUNCTION_ACOSH                        Function = 5
	FUNCTION_ASIN                         Function = 6
	FUNCTION_ASINH                        Function = 7
	FUNCTION_ATAN                         Function = 8
	FUNCTION_ATANH                        Function = 9
	FUNCTION_AVG_OVER_TIME                Function = 10
	FUNCTION_CEIL                         Function = 11
	FUNCTION_CHANGES                      Function = 12
	FUNCTION_CLAMP                        Function = 13
	FUNCTION_CLAMP_MAX                    Function = 14
	FUNCTION_CLAMP_MIN                    Function = 15
	FUNCTION_COS                          Function = 16
	FUNCTION_COSH                         Function = 17
	FUNCTION_COUNT_OVER_TIME              Function = 18
	FUNCTION_DAYS_IN_MONTH                Function = 22
	FUNCTION_DAY_OF_MONTH                 Function = 19
	FUNCTION_DAY_OF_WEEK                  Function = 20
	FUNCTION_DAY_OF_YEAR                  Function = 21
	FUNCTION_DEG                          Function = 23
	FUNCTION_DELTA                        Function = 24
	FUNCTION_DERIV                        Function = 25
	FUNCTION_DOUBLE_EXPONENTIAL_SMOOTHING Function = 26
	FUNCTION_EXP                          Function = 27
	FUNCTION_FIRST_OVER_TIME              Function = 86
	FUNCTION_FLOOR                        Function = 28
	FUNCTION_HISTOGRAM_AVG                Function = 29
	FUNCTION_HISTOGRAM_COUNT              Function = 30
	FUNCTION_HISTOGRAM_FRACTION           Function = 31
	FUNCTION_HISTOGRAM_QUANTILE           Function = 32
	FUNCTION_HISTOGRAM_STDDEV             Function = 33
	FUNCTION_HISTOGRAM_STDVAR             Function = 34
	FUNCTION_HISTOGRAM_SUM                Function = 35
	FUNCTION_HOUR                         Function = 36
	FUNCTION_IDELTA                       Function = 37
	FUNCTION_INCREASE                     Function = 38
	FUNCTION_INFO                         Function = 83
	FUNCTION_IRATE                        Function = 39
	FUNCTION_LABEL_JOIN                   Function = 40
	FUNCTION_LABEL_REPLACE                Function = 41
	FUNCTION_LAST_OVER_TIME               Function = 42
	FUNCTION_LN                           Function = 43
	FUNCTION_LOG10                        Function = 44
	FUNCTION_LOG2                         Function = 45
	FUNCTION_MAD_OVER_TIME                Function = 80
	FUNCTION_MAX_OF                       Function = 89
	FUNCTION_MAX_OVER_TIME                Function = 46
	FUNCTION_MINUTE                       Function = 48
	FUNCTION_MIN_OF                       Function = 90
	FUNCTION_MIN_OVER_TIME                Function = 47
	FUNCTION_MONTH                        Function = 49
	FUNCTION_PREDICT_LINEAR               Function = 50
	FUNCTION_PRESENT_OVER_TIME            Function = 51
	FUNCTION_QUANTILE_OVER_TIME           Function = 52
	FUNCTION_RAD                          Function = 53
	FUNCTION_RATE                         Function = 54
	FUNCTION_RESETS                       Function = 55
	FUNCTION_ROUND                        Function = 56
	FUNCTION_SGN                          Function = 57
	FUNCTION_SIN                          Function = 58
	FUNCTION_SINH                         Function = 59
	FUNCTION_SORT                         Function = 60
	FUNCTION_SORT_BY_LABEL                Function = 76
	FUNCTION_SORT_BY_LABEL_DESC           Function = 77
	FUNCTION_SORT_DESC                    Function = 61
	FUNCTION_SQRT                         Function = 62
	FUNCTION_STDDEV_OVER_TIME             Function = 63
	FUNCTION_STDVAR_OVER_TIME             Function = 64
	FUNCTION_SUM_OVER_TIME                Function = 65
	FUNCTION_TAN                          Function = 66
	FUNCTION_TANH                         Function = 67
	FUNCTION_TIMESTAMP                    Function = 68
	FUNCTION_TS_OF_FIRST_OVER_TIME        Function = 78
	FUNCTION_TS_OF_LAST_OVER_TIME         Function = 79
	FUNCTION_TS_OF_MAX_OVER_TIME          Function = 85
	FUNCTION_TS_OF_MIN_OVER_TIME          Function = 84
	FUNCTION_VECTOR                       Function = 69
	FUNCTION_YEAR                         Function = 70
	FUNCTION_PI                           Function = 71
	FUNCTION_SCALAR                       Function = 72
	FUNCTION_TIME                         Function = 73
	// Used by Adaptive Metrics query rewriting.
	FUNCTION_ADAPTIVE_METRICS_RESERVED_1 Function = 74
	FUNCTION_ADAPTIVE_METRICS_RESERVED_2 Function = 75
	FUNCTION_SHARDING_CONCAT             Function = 87
	FUNCTION_SHARDING_AVG                Function = 88
)

var Function_name = map[int32]string{
	0:  "FUNCTION_UNKNOWN",
	1:  "FUNCTION_ABS",
	2:  "FUNCTION_ABSENT",
	3:  "FUNCTION_ABSENT_OVER_TIME",
	4:  "FUNCTION_ACOS",
	5:  "FUNCTION_ACOSH",
	6:  "FUNCTION_ASIN",
	7:  "FUNCTION_ASINH",
	8:  "FUNCTION_ATAN",
	9:  "FUNCTION_ATANH",
	10: "FUNCTION_AVG_OVER_TIME",
	11: "FUNCTION_CEIL",
	12: "FUNCTION_CHANGES",
	13: "FUNCTION_CLAMP",
	14: "FUNCTION_CLAMP_MAX",
	15: "FUNCTION_CLAMP_MIN",
	16: "FUNCTION_COS",
	17: "FUNCTION_COSH",
	18: "FUNCTION_COUNT_OVER_TIME",
	22: "FUNCTION_DAYS_IN_MONTH",
	19: "FUNCTION_DAY_OF_MONTH",
	20: "FUNCTION_DAY_OF_WEEK",
	21: "FUNCTION_DAY_OF_YEAR",
	23: "FUNCTION_DEG",
	24: "FUNCTION_DELTA",
	25: "FUNCTION_DERIV",
	26: "FUNCTION_DOUBLE_EXPONENTIAL_SMOOTHING",
	27: "FUNCTION_EXP",
	86: "FUNCTION_FIRST_OVER_TIME",
	28: "FUNCTION_FLOOR",
	29: "FUNCTION_HISTOGRAM_AVG",
	30: "FUNCTION_HISTOGRAM_COUNT",
	31: "FUNCTION_HISTOGRAM_FRACTION",
	32: "FUNCTION_HISTOGRAM_QUANTILE",
	33: "FUNCTION_HISTOGRAM_STDDEV",
	34: "FUNCTION_HISTOGRAM_STDVAR",
	35: "FUNCTION_HISTOGRAM_SUM",
	36: "FUNCTION_HOUR",
	37: "FUNCTION_IDELTA",
	38: "FUNCTION_INCREASE",
	83: "FUNCTION_INFO",
	39: "FUNCTION_IRATE",
	40: "FUNCTION_LABEL_JOIN",
	41: "FUNCTION_LABEL_REPLACE",
	42: "FUNCTION_LAST_OVER_TIME",
	43: "FUNCTION_LN",
	44: "FUNCTION_LOG10",
	45: "FUNCTION_LOG2",
	80: "FUNCTION_MAD_OVER_TIME",
	89: "FUNCTION_MAX_OF",
	46: "FUNCTION_MAX_OVER_TIME",
	48: "FUNCTION_MINUTE",
	90: "FUNCTION_MIN_OF",
	47: "FUNCTION_MIN_OVER_TIME",
	49: "FUNCTION_MONTH",
	50: "FUNCTION_PREDICT_LINEAR",
	51: "FUNCTION_PRESENT_OVER_TIME",
	52: "FUNCTION_QUANTILE_OVER_TIME",
	53: "FUNCTION_RAD",
	54: "FUNCTION_RATE",
	55: "FUNCTION_RESETS",
	56: "FUNCTION_ROUND",
	57: "FUNCTION_SGN",
	58: "FUNCTION_SIN",
	59: "FUNCTION_SINH",
	60: "FUNCTION_SORT",
	76: "FUNCTION_SORT_BY_LABEL",
	77: "FUNCTION_SORT_BY_LABEL_DESC",
	61: "FUNCTION_SORT_DESC",
	62: "FUNCTION_SQRT",
	63: "FUNCTION_STDDEV_OVER_TIME",
	64: "FUNCTION_STDVAR_OVER_TIME",
	65: "FUNCTION_SUM_OVER_TIME",
	66: "FUNCTION_TAN",
	67: "FUNCTION_TANH",
	68: "FUNCTION_TIMESTAMP",
	78: "FUNCTION_TS_OF_FIRST_OVER_TIME",
	79: "FUNCTION_TS_OF_LAST_OVER_TIME",
	85: "FUNCTION_TS_OF_MAX_OVER_TIME",
	84: "FUNCTION_TS_OF_MIN_OVER_TIME",
	69: "FUNCTION_VECTOR",
	70: "FUNCTION_YEAR",
	71: "FUNCTION_PI",
	72: "FUNCTION_SCALAR",
	73: "FUNCTION_TIME",
	74: "FUNCTION_ADAPTIVE_METRICS_RESERVED_1",
	75: "FUNCTION_ADAPTIVE_METRICS_RESERVED_2",
	87: "FUNCTION_SHARDING_CONCAT",
	88: "FUNCTION_SHARDING_AVG",
}

var Function_value = map[string]int32{
	"FUNCTION_UNKNOWN":                      0,
	"FUNCTION_ABS":                          1,
	"FUNCTION_ABSENT":                       2,
	"FUNCTION_ABSENT_OVER_TIME":             3,
	"FUNCTION_ACOS":                         4,
	"FUNCTION_ACOSH":                        5,
	"FUNCTION_ASIN":                         6,
	"FUNCTION_ASINH":                        7,
	"FUNCTION_ATAN":                         8,
	"FUNCTION_ATANH":                        9,
	"FUNCTION_AVG_OVER_TIME":                10,
	"FUNCTION_CEIL":                         11,
	"FUNCTION_CHANGES":                      12,
	"FUNCTION_CLAMP":                        13,
	"FUNCTION_CLAMP_MAX":                    14,
	"FUNCTION_CLAMP_MIN":                    15,
	"FUNCTION_COS":                          16,
	"FUNCTION_COSH":                         17,
	"FUNCTION_COUNT_OVER_TIME":              18,
	"FUNCTION_DAYS_IN_MONTH":                22,
	"FUNCTION_DAY_OF_MONTH":                 19,
	"FUNCTION_DAY_OF_WEEK":                  20,
	"FUNCTION_DAY_OF_YEAR":                  21,
	"FUNCTION_DEG":                          23,
	"FUNCTION_DELTA":                        24,
	"FUNCTION_DERIV":                        25,
	"FUNCTION_DOUBLE_EXPONENTIAL_SMOOTHING": 26,
	"FUNCTION_EXP":                          27,
	"FUNCTION_FIRST_OVER_TIME":              86,
	"FUNCTION_FLOOR":                        28,
	"FUNCTION_HISTOGRAM_AVG":                29,
	"FUNCTION_HISTOGRAM_COUNT":              30,
	"FUNCTION_HISTOGRAM_FRACTION":           31,
	"FUNCTION_HISTOGRAM_QUANTILE":           32,
	"FUNCTION_HISTOGRAM_STDDEV":             33,
	"FUNCTION_HISTOGRAM_STDVAR":             34,
	"FUNCTION_HISTOGRAM_SUM":                35,
	"FUNCTION_HOUR":                         36,
	"FUNCTION_IDELTA":                       37,
	"FUNCTION_INCREASE":                     38,
	"FUNCTION_INFO":                         83,
	"FUNCTION_IRATE":                        39,
	"FUNCTION_LABEL_JOIN":                   40,
	"FUNCTION_LABEL_REPLACE":                41,
	"FUNCTION_LAST_OVER_TIME":               42,
	"FUNCTION_LN":                           43,
	"FUNCTION_LOG10":                        44,
	"FUNCTION_LOG2":                         45,
	"FUNCTION_MAD_OVER_TIME":                80,
	"FUNCTION_MAX_OF":                       89,
	"FUNCTION_MAX_OVER_TIME":                46,
	"FUNCTION_MINUTE":                       48,
	"FUNCTION_MIN_OF":                       90,
	"FUNCTION_MIN_OVER_TIME":                47,
	"FUNCTION_MONTH":                        49,
	"FUNCTION_PREDICT_LINEAR":               50,
	"FUNCTION_PRESENT_OVER_TIME":            51,
	"FUNCTION_QUANTILE_OVER_TIME":           52,
	"FUNCTION_RAD":                          53,
	"FUNCTION_RATE":                         54,
	"FUNCTION_RESETS":                       55,
	"FUNCTION_ROUND":                        56,
	"FUNCTION_SGN":                          57,
	"FUNCTION_SIN":                          58,
	"FUNCTION_SINH":                         59,
	"FUNCTION_SORT":                         60,
	"FUNCTION_SORT_BY_LABEL":                76,
	"FUNCTION_SORT_BY_LABEL_DESC":           77,
	"FUNCTION_SORT_DESC":                    61,
	"FUNCTION_SQRT":                         62,
	"FUNCTION_STDDEV_OVER_TIME":             63,
	"FUNCTION_STDVAR_OVER_TIME":             64,
	"FUNCTION_SUM_OVER_TIME":                65,
	"FUNCTION_TAN":                          66,
	"FUNCTION_TANH":                         67,
	"FUNCTION_TIMESTAMP":                    68,
	"FUNCTION_TS_OF_FIRST_OVER_TIME":        78,
	"FUNCTION_TS_OF_LAST_OVER_TIME":         79,
	"FUNCTION_TS_OF_MAX_OVER_TIME":          85,
	"FUNCTION_TS_OF_MIN_OVER_TIME":          84,
	"FUNCTION_VECTOR":                       69,
	"FUNCTION_YEAR":                         70,
	"FUNCTION_PI":                           71,
	"FUNCTION_SCALAR":                       72,
	"FUNCTION_TIME":                         73,
	"FUNCTION_ADAPTIVE_METRICS_RESERVED_1":  74,
	"FUNCTION_ADAPTIVE_METRICS_RESERVED_2":  75,
	"FUNCTION_SHARDING_CONCAT":              87,
	"FUNCTION_SHARDING_AVG":                 88,
}

func (Function) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_83a6426a31b44db4, []int{0}
}

func init() {
	proto.RegisterEnum("functions.Function", Function_name, Function_value)
}

func init() { proto.RegisterFile("functions.proto", fileDescriptor_83a6426a31b44db4) }

var fileDescriptor_83a6426a31b44db4 = []byte{
	// 873 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xc9, 0x92, 0xdc, 0x44,
	0x10, 0x6d, 0xb1, 0x18, 0xbb, 0xbc, 0x4c, 0x76, 0xcd, 0xbe, 0x95, 0x17, 0x6c, 0xb0, 0x0d, 0x18,
	0xcf, 0xd8, 0xec, 0x6b, 0xb5, 0x54, 0x92, 0xca, 0x23, 0x55, 0xc9, 0x55, 0x25, 0x4d, 0x37, 0x97,
	0x8a, 0x80, 0x08, 0x22, 0xb8, 0x78, 0x08, 0x30, 0x77, 0x3e, 0x81, 0x13, 0xdf, 0xc0, 0xa7, 0x70,
	0x9c, 0xa3, 0x8f, 0x4c, 0xcf, 0x85, 0xa3, 0x3f, 0x81, 0x90, 0x7a, 0x68, 0x29, 0x15, 0x3d, 0x11,
	0x3e, 0xf6, 0x7b, 0xb9, 0xbd, 0xac, 0xcc, 0x54, 0x93, 0xa5, 0x1f, 0x7f, 0x7b, 0xf6, 0xc3, 0xf3,
	0x9f, 0x8e, 0x9e, 0xfd, 0xfa, 0xe0, 0xe7, 0x5f, 0x8e, 0x9e, 0x1f, 0xd1, 0x4b, 0x73, 0xe0, 0xfe,
	0x9f, 0x43, 0x72, 0x31, 0x3e, 0xfb, 0x45, 0x57, 0x08, 0xc4, 0xa5, 0x0a, 0x9d, 0xd4, 0xca, 0x97,
	0xea, 0x40, 0xe9, 0x43, 0x05, 0x03, 0x0a, 0xe4, 0xca, 0x1c, 0xe5, 0x23, 0x0b, 0x01, 0x5d, 0x26,
	0x4b, 0x5d, 0x44, 0x28, 0x07, 0xaf, 0xd1, 0x5d, 0xb2, 0xd9, 0x03, 0xbd, 0xae, 0x84, 0xf1, 0x4e,
	0xe6, 0x02, 0x5e, 0xa7, 0x43, 0x72, 0xb5, 0xa5, 0x43, 0x6d, 0xe1, 0x0d, 0x4a, 0xc9, 0x35, 0x04,
	0xa5, 0xf0, 0x26, 0x36, 0xb3, 0x52, 0xc1, 0x05, 0x6c, 0x66, 0xa5, 0x4a, 0xe1, 0x2d, 0x6c, 0xe6,
	0xb8, 0x82, 0x8b, 0xd8, 0xcc, 0x71, 0x95, 0xc2, 0x25, 0xba, 0x45, 0xd6, 0x5a, 0xac, 0x4a, 0x3a,
	0x05, 0x11, 0x14, 0x22, 0x14, 0x32, 0x83, 0xcb, 0x48, 0x7f, 0x98, 0x72, 0x95, 0x08, 0x0b, 0x57,
	0x50, 0xe0, 0x30, 0xe3, 0x79, 0x01, 0x57, 0xe9, 0x1a, 0xa1, 0x18, 0xf3, 0x39, 0x1f, 0xc3, 0xb5,
	0x45, 0xb8, 0x54, 0xb0, 0x84, 0x7a, 0x58, 0x8b, 0x07, 0x9c, 0xbe, 0xd6, 0x3e, 0xa4, 0x3b, 0x64,
	0xa3, 0x03, 0x95, 0xa8, 0x81, 0x14, 0x69, 0x89, 0xf8, 0xc4, 0x7a, 0xa9, 0x7c, 0xae, 0x95, 0x4b,
	0x61, 0x8d, 0x6e, 0x92, 0xd5, 0x2e, 0xe7, 0x75, 0x7c, 0x46, 0x2d, 0xd3, 0x0d, 0xb2, 0xd2, 0xa7,
	0x0e, 0x85, 0x38, 0x80, 0x95, 0x45, 0xcc, 0x44, 0x70, 0x03, 0xab, 0xa8, 0xda, 0x48, 0x24, 0xb0,
	0x8e, 0x7a, 0x10, 0x89, 0xcc, 0x71, 0xd8, 0xe8, 0x61, 0x46, 0x56, 0xb0, 0x49, 0xef, 0x91, 0x3b,
	0x2d, 0xa6, 0xcb, 0x51, 0x26, 0xbc, 0x18, 0x17, 0x5a, 0x09, 0xe5, 0x24, 0xcf, 0xbc, 0xcd, 0xb5,
	0x76, 0xa9, 0x54, 0x09, 0x6c, 0xa1, 0x24, 0x62, 0x5c, 0xc0, 0x36, 0xd2, 0x1f, 0x4b, 0x63, 0xbb,
	0xfa, 0x2b, 0x94, 0x2e, 0xce, 0xb4, 0x36, 0xb0, 0x83, 0x7a, 0x92, 0x4a, 0xeb, 0x74, 0x62, 0x78,
	0x5e, 0xbf, 0x34, 0xec, 0xa2, 0x68, 0x2d, 0xd7, 0xf4, 0x15, 0x18, 0xbd, 0x4e, 0xb6, 0x17, 0xb0,
	0xb1, 0xe1, 0x0d, 0x04, 0xd7, 0xcf, 0x31, 0x78, 0x5a, 0x72, 0xe5, 0x64, 0x26, 0xe0, 0x06, 0x9a,
	0xf7, 0xd6, 0xc0, 0xba, 0x28, 0x12, 0x15, 0xdc, 0x3c, 0x9f, 0xae, 0xb8, 0x81, 0x5b, 0xe7, 0x54,
	0x6e, 0xcb, 0x1c, 0xde, 0x46, 0xa3, 0x91, 0xea, 0xd2, 0xc0, 0x6d, 0xb4, 0x71, 0x72, 0xf6, 0x00,
	0x77, 0xe8, 0x2a, 0x19, 0xb6, 0xa0, 0x0a, 0x8d, 0xe0, 0x56, 0xc0, 0x3b, 0xc8, 0x5d, 0xaa, 0x58,
	0x83, 0x45, 0xbd, 0x93, 0x86, 0x3b, 0x01, 0xef, 0xd2, 0x75, 0xb2, 0x3c, 0xc7, 0x32, 0x3e, 0x12,
	0x99, 0x7f, 0xa2, 0xa5, 0x82, 0xbb, 0xa8, 0xb4, 0x19, 0x61, 0x44, 0x91, 0xf1, 0x50, 0xc0, 0x3d,
	0xba, 0x4d, 0xd6, 0x3b, 0x1c, 0x7a, 0xa1, 0xfb, 0x74, 0x89, 0x5c, 0x6e, 0x49, 0x05, 0xef, 0xa1,
	0xb4, 0x99, 0x4e, 0xf6, 0x1e, 0xc2, 0xfb, 0xa8, 0xba, 0x4c, 0x27, 0xfb, 0xf0, 0x01, 0x4a, 0x98,
	0xf3, 0xa8, 0x13, 0xb3, 0x40, 0xc2, 0x73, 0x3e, 0xf6, 0x3a, 0x86, 0x49, 0xcf, 0x61, 0xdc, 0x71,
	0x78, 0x80, 0x1d, 0xa4, 0x2a, 0x9d, 0x80, 0x87, 0x7d, 0xb0, 0x8e, 0xf2, 0x1d, 0x8e, 0x52, 0x83,
	0xf3, 0x28, 0x1f, 0xa2, 0xca, 0x67, 0x9b, 0xb4, 0x87, 0xb4, 0x17, 0x46, 0x44, 0x32, 0x74, 0x3e,
	0x93, 0xaa, 0x5e, 0x99, 0x7d, 0xca, 0xc8, 0x56, 0x97, 0xec, 0x9d, 0xbf, 0x47, 0x68, 0x9c, 0xfe,
	0x1f, 0xa2, 0x8e, 0xc1, 0x63, 0xb4, 0x0e, 0x86, 0x47, 0xf0, 0x11, 0xea, 0x54, 0xf3, 0x66, 0x1f,
	0x23, 0x1d, 0x75, 0x12, 0x67, 0xe1, 0x13, 0x54, 0xab, 0xd1, 0xa5, 0x8a, 0xe0, 0x53, 0x14, 0xcd,
	0x26, 0x0a, 0x3e, 0xc3, 0x88, 0x54, 0xf0, 0x39, 0x8a, 0xdf, 0x9c, 0xd5, 0x2f, 0x30, 0xa4, 0x8d,
	0x83, 0x2f, 0x51, 0x97, 0x6a, 0xc8, 0x8f, 0x26, 0xb3, 0xa9, 0x80, 0x0c, 0x89, 0x42, 0x9c, 0x8f,
	0x84, 0x0d, 0x21, 0x47, 0xe7, 0xb0, 0x31, 0x68, 0xf0, 0xaf, 0x70, 0x9e, 0xa7, 0xc6, 0xc1, 0xd7,
	0x68, 0x5f, 0x66, 0x4b, 0xd4, 0x69, 0xcf, 0x37, 0x7d, 0xba, 0xe2, 0xa6, 0x43, 0x7f, 0x8b, 0xab,
	0x2c, 0xf3, 0x0e, 0xc7, 0x91, 0xf2, 0xfa, 0x53, 0x31, 0x42, 0xe9, 0x9b, 0x2f, 0x45, 0x88, 0x2a,
	0xad, 0xfd, 0xac, 0xab, 0x0f, 0x7d, 0x44, 0x6f, 0x11, 0xd6, 0xe2, 0xb6, 0xbe, 0x91, 0xfd, 0xcb,
	0xa4, 0xe8, 0x4d, 0xb2, 0xdb, 0xb3, 0xe9, 0xad, 0x86, 0xa6, 0x37, 0xc8, 0x4e, 0xcf, 0x04, 0xcf,
	0x6d, 0xb9, 0xc8, 0x02, 0xcd, 0xa4, 0x43, 0x8f, 0x5f, 0x89, 0xd0, 0x69, 0x03, 0x02, 0x49, 0x69,
	0xae, 0x77, 0x8c, 0xd6, 0xb0, 0x90, 0x90, 0x20, 0x47, 0x1b, 0xf2, 0x8c, 0x1b, 0x48, 0x71, 0x0f,
	0xea, 0x04, 0x92, 0xde, 0x25, 0xb7, 0xdb, 0xaf, 0x65, 0xc4, 0x0b, 0x27, 0x2b, 0xe1, 0x73, 0xe1,
	0x8c, 0x0c, 0x6d, 0x33, 0x6e, 0xa6, 0x12, 0x91, 0xdf, 0x83, 0x27, 0xaf, 0x68, 0xb9, 0x0f, 0x07,
	0xe8, 0x0a, 0xdb, 0x94, 0x9b, 0x48, 0xaa, 0xc4, 0x87, 0x5a, 0x85, 0xdc, 0xc1, 0x21, 0xfa, 0x6e,
	0xcd, 0xd9, 0xfa, 0x7c, 0x8f, 0x47, 0x8f, 0x8f, 0x4f, 0xd8, 0xe0, 0xc5, 0x09, 0x1b, 0xbc, 0x3c,
	0x61, 0xc1, 0xef, 0x53, 0x16, 0xfc, 0x35, 0x65, 0xc1, 0xdf, 0x53, 0x16, 0x1c, 0x4f, 0x59, 0xf0,
	0xcf, 0x94, 0x05, 0xff, 0x4e, 0xd9, 0xe0, 0xe5, 0x94, 0x05, 0x7f, 0x9c, 0xb2, 0xc1, 0xf1, 0x29,
	0x1b, 0xbc, 0x38, 0x65, 0x83, 0xef, 0x2f, 0x34, 0x7f, 0x70, 0x1e, 0xfd, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x76, 0x20, 0x66, 0xe4, 0xf3, 0x08, 0x00, 0x00,
}

func (x Function) String() string {
	s, ok := Function_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
