// Code generated by wiresmith. DO NOT EDIT.
// source: github.com/grafana/mimir/pkg/blockbuilder/schedulerpb/scheduler.proto

package schedulerpb

import (
	"sort"
)

// Per-message value-comparison methods (Equal + Compare) for github.com/grafana/mimir/pkg/blockbuilder/schedulerpb/scheduler.proto.
//
// Equal returns bool; Compare returns -1/0/+1 like bytes.Compare with the
// gogoproto.compare nil/wrong-type preamble. Both are emitted on every
// message; callers that don't use one can rely on Go's dead-code
// elimination to drop the body.
//
// Why a separate file? Equal/Compare are never called from Marshal/Unmarshal/
// Size, but emitting them next to those hot functions in the main .pb.go
// pushed them onto different cache sets and produced a measured ~9% geomean
// regression on OTel benchmarks (UnmarshalMap +14%, MarshalSingleSpan +13%)
// purely from icache / iTLB / BTB pressure. Splitting them into their own
// compilation unit gives the linker freedom to place the cold half away
// from the hot half — same trick the _util.pb.go split uses.
//
// See compiler/generator/emit_compare.go / emit_equal.go for the full
// rationale and the benchmark methodology. DO NOT inline this file's
// contents back into the main .pb.go without re-measuring.

func (this *JobKey) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*JobKey)
	if !ok {
		that2, ok := that.(JobKey)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Epoch != that1.Epoch {
		return false
	}
	return true
}

func (this *JobSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*JobSpec)
	if !ok {
		that2, ok := that.(JobSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Topic != that1.Topic {
		return false
	}
	if this.Partition != that1.Partition {
		return false
	}
	if this.StartOffset != that1.StartOffset {
		return false
	}
	if this.EndOffset != that1.EndOffset {
		return false
	}
	if len(this.OffsetRanges) != len(that1.OffsetRanges) {
		return false
	}
	for k, v := range this.OffsetRanges {
		v2, ok := that1.OffsetRanges[k]
		if !ok {
			return false
		}
		if !v.Equal(v2) {
			return false
		}
	}
	return true
}

func (this *OffsetRange) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*OffsetRange)
	if !ok {
		that2, ok := that.(OffsetRange)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StartOffset != that1.StartOffset {
		return false
	}
	if this.EndOffset != that1.EndOffset {
		return false
	}
	return true
}

func (this *AssignJobRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AssignJobRequest)
	if !ok {
		that2, ok := that.(AssignJobRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.WorkerId != that1.WorkerId {
		return false
	}
	return true
}

func (this *AssignJobResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AssignJobResponse)
	if !ok {
		that2, ok := that.(AssignJobResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if (this.Key == nil) != (that1.Key == nil) {
		return false
	}
	if this.Key != nil && !this.Key.Equal(that1.Key) {
		return false
	}
	if (this.Spec == nil) != (that1.Spec == nil) {
		return false
	}
	if this.Spec != nil && !this.Spec.Equal(that1.Spec) {
		return false
	}
	return true
}

func (this *UpdateJobRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpdateJobRequest)
	if !ok {
		that2, ok := that.(UpdateJobRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if (this.Key == nil) != (that1.Key == nil) {
		return false
	}
	if this.Key != nil && !this.Key.Equal(that1.Key) {
		return false
	}
	if this.WorkerId != that1.WorkerId {
		return false
	}
	if (this.Spec == nil) != (that1.Spec == nil) {
		return false
	}
	if this.Spec != nil && !this.Spec.Equal(that1.Spec) {
		return false
	}
	if this.Complete != that1.Complete {
		return false
	}
	return true
}

func (this *UpdateJobResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*UpdateJobResponse)
	if !ok {
		that2, ok := that.(UpdateJobResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}

func (this *JobKey) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*JobKey)
	if !ok {
		that2, ok := that.(JobKey)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Id != that1.Id {
		if this.Id < that1.Id {
			return -1
		}
		return 1
	}
	if this.Epoch != that1.Epoch {
		if this.Epoch < that1.Epoch {
			return -1
		}
		return 1
	}
	return 0
}

func (this *JobSpec) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*JobSpec)
	if !ok {
		that2, ok := that.(JobSpec)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Topic != that1.Topic {
		if this.Topic < that1.Topic {
			return -1
		}
		return 1
	}
	if this.Partition != that1.Partition {
		if this.Partition < that1.Partition {
			return -1
		}
		return 1
	}
	if this.StartOffset != that1.StartOffset {
		if this.StartOffset < that1.StartOffset {
			return -1
		}
		return 1
	}
	if this.EndOffset != that1.EndOffset {
		if this.EndOffset < that1.EndOffset {
			return -1
		}
		return 1
	}
	if len(this.OffsetRanges) != len(that1.OffsetRanges) {
		if len(this.OffsetRanges) < len(that1.OffsetRanges) {
			return -1
		}
		return 1
	}
	{
		ks1 := make([]int32, 0, len(this.OffsetRanges))
		for k := range this.OffsetRanges {
			ks1 = append(ks1, k)
		}
		sort.Slice(ks1, func(i, j int) bool { return ks1[i] < ks1[j] })
		ks2 := make([]int32, 0, len(that1.OffsetRanges))
		for k := range that1.OffsetRanges {
			ks2 = append(ks2, k)
		}
		sort.Slice(ks2, func(i, j int) bool { return ks2[i] < ks2[j] })
		for i := range ks1 {
			if ks1[i] != ks2[i] {
				if ks1[i] < ks2[i] {
					return -1
				}
				return 1
			}
			v1 := this.OffsetRanges[ks1[i]]
			v2 := that1.OffsetRanges[ks2[i]]
			if c := v1.Compare(v2); c != 0 {
				return c
			}
		}
	}
	return 0
}

func (this *OffsetRange) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*OffsetRange)
	if !ok {
		that2, ok := that.(OffsetRange)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.StartOffset != that1.StartOffset {
		if this.StartOffset < that1.StartOffset {
			return -1
		}
		return 1
	}
	if this.EndOffset != that1.EndOffset {
		if this.EndOffset < that1.EndOffset {
			return -1
		}
		return 1
	}
	return 0
}

func (this *AssignJobRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*AssignJobRequest)
	if !ok {
		that2, ok := that.(AssignJobRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.WorkerId != that1.WorkerId {
		if this.WorkerId < that1.WorkerId {
			return -1
		}
		return 1
	}
	return 0
}

func (this *AssignJobResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*AssignJobResponse)
	if !ok {
		that2, ok := that.(AssignJobResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if (this.Key == nil) != (that1.Key == nil) {
		if this.Key == nil {
			return -1
		}
		return 1
	}
	if this.Key != nil {
		if c := this.Key.Compare(that1.Key); c != 0 {
			return c
		}
	}
	if (this.Spec == nil) != (that1.Spec == nil) {
		if this.Spec == nil {
			return -1
		}
		return 1
	}
	if this.Spec != nil {
		if c := this.Spec.Compare(that1.Spec); c != 0 {
			return c
		}
	}
	return 0
}

func (this *UpdateJobRequest) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*UpdateJobRequest)
	if !ok {
		that2, ok := that.(UpdateJobRequest)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if (this.Key == nil) != (that1.Key == nil) {
		if this.Key == nil {
			return -1
		}
		return 1
	}
	if this.Key != nil {
		if c := this.Key.Compare(that1.Key); c != 0 {
			return c
		}
	}
	if this.WorkerId != that1.WorkerId {
		if this.WorkerId < that1.WorkerId {
			return -1
		}
		return 1
	}
	if (this.Spec == nil) != (that1.Spec == nil) {
		if this.Spec == nil {
			return -1
		}
		return 1
	}
	if this.Spec != nil {
		if c := this.Spec.Compare(that1.Spec); c != 0 {
			return c
		}
	}
	if this.Complete != that1.Complete {
		if !this.Complete && that1.Complete {
			return -1
		}
		return 1
	}
	return 0
}

func (this *UpdateJobResponse) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*UpdateJobResponse)
	if !ok {
		that2, ok := that.(UpdateJobResponse)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	return 0
}
