// Code generated by wiresmith. DO NOT EDIT.
// source: github.com/grafana/mimir/pkg/storegateway/hintspb/hints.proto

package hintspb

import (
	"fmt"
	"github.com/grafana/mimir/pkg/storegateway/storepb"
	"github.com/grafana/wiresmith/protohelpers"
	"google.golang.org/protobuf/encoding/protowire"
	"io"
	"math"
)

type SeriesRequestHints struct {
	// block_matchers is a list of label matchers that are evaluated against each single block's
	// labels to filter which blocks get queried. If the list is empty, no per-block filtering
	// is applied.
	BlockMatchers []storepb.LabelMatcher `protobuf:"bytes,1,rep,name=block_matchers,json=blockMatchers,proto3" json:"block_matchers,omitempty"`
}

type SeriesResponseHints struct {
	// queried_blocks is the list of blocks that have been queried.
	QueriedBlocks []Block `protobuf:"bytes,1,rep,name=queried_blocks,json=queriedBlocks,proto3" json:"queried_blocks,omitempty"`
}

type Block struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

type LabelNamesRequestHints struct {
	// block_matchers is a list of label matchers that are evaluated against each single block's
	// labels to filter which blocks get queried. If the list is empty, no per-block filtering
	// is applied.
	BlockMatchers []storepb.LabelMatcher `protobuf:"bytes,1,rep,name=block_matchers,json=blockMatchers,proto3" json:"block_matchers,omitempty"`
}

type LabelNamesResponseHints struct {
	// queried_blocks is the list of blocks that have been queried.
	QueriedBlocks []Block `protobuf:"bytes,1,rep,name=queried_blocks,json=queriedBlocks,proto3" json:"queried_blocks,omitempty"`
}

type LabelValuesRequestHints struct {
	// block_matchers is a list of label matchers that are evaluated against each single block's
	// labels to filter which blocks get queried. If the list is empty, no per-block filtering
	// is applied.
	BlockMatchers []storepb.LabelMatcher `protobuf:"bytes,1,rep,name=block_matchers,json=blockMatchers,proto3" json:"block_matchers,omitempty"`
}

type LabelValuesResponseHints struct {
	// queried_blocks is the list of blocks that have been queried.
	QueriedBlocks []Block `protobuf:"bytes,1,rep,name=queried_blocks,json=queriedBlocks,proto3" json:"queried_blocks,omitempty"`
}

func (m *SeriesRequestHints) Reset() {
	if m == nil {
		return
	}
	*m = SeriesRequestHints{}
}
func (*SeriesRequestHints) ProtoMessage() {}

func (m *SeriesResponseHints) Reset() {
	if m == nil {
		return
	}
	*m = SeriesResponseHints{}
}
func (*SeriesResponseHints) ProtoMessage() {}

func (m *Block) Reset() {
	if m == nil {
		return
	}
	*m = Block{}
}
func (*Block) ProtoMessage() {}

func (m *LabelNamesRequestHints) Reset() {
	if m == nil {
		return
	}
	*m = LabelNamesRequestHints{}
}
func (*LabelNamesRequestHints) ProtoMessage() {}

func (m *LabelNamesResponseHints) Reset() {
	if m == nil {
		return
	}
	*m = LabelNamesResponseHints{}
}
func (*LabelNamesResponseHints) ProtoMessage() {}

func (m *LabelValuesRequestHints) Reset() {
	if m == nil {
		return
	}
	*m = LabelValuesRequestHints{}
}
func (*LabelValuesRequestHints) ProtoMessage() {}

func (m *LabelValuesResponseHints) Reset() {
	if m == nil {
		return
	}
	*m = LabelValuesResponseHints{}
}
func (*LabelValuesResponseHints) ProtoMessage() {}

func (m *SeriesRequestHints) GetBlockMatchers() []storepb.LabelMatcher {
	if m != nil {
		return m.BlockMatchers
	}
	return nil
}

func (m *SeriesResponseHints) GetQueriedBlocks() []Block {
	if m != nil {
		return m.QueriedBlocks
	}
	return nil
}

func (m *Block) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LabelNamesRequestHints) GetBlockMatchers() []storepb.LabelMatcher {
	if m != nil {
		return m.BlockMatchers
	}
	return nil
}

func (m *LabelNamesResponseHints) GetQueriedBlocks() []Block {
	if m != nil {
		return m.QueriedBlocks
	}
	return nil
}

func (m *LabelValuesRequestHints) GetBlockMatchers() []storepb.LabelMatcher {
	if m != nil {
		return m.BlockMatchers
	}
	return nil
}

func (m *LabelValuesResponseHints) GetQueriedBlocks() []Block {
	if m != nil {
		return m.QueriedBlocks
	}
	return nil
}

func (m *SeriesRequestHints) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.BlockMatchers {
		s := m.BlockMatchers[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *SeriesResponseHints) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.QueriedBlocks {
		s := m.QueriedBlocks[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *Block) Size() int {
	if m == nil {
		return 0
	}
	var n int
	if len(m.Id) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.Id))) + len(m.Id)
	}
	return n
}

func (m *LabelNamesRequestHints) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.BlockMatchers {
		s := m.BlockMatchers[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *LabelNamesResponseHints) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.QueriedBlocks {
		s := m.QueriedBlocks[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *LabelValuesRequestHints) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.BlockMatchers {
		s := m.BlockMatchers[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *LabelValuesResponseHints) Size() int {
	if m == nil {
		return 0
	}
	var n int
	for i := range m.QueriedBlocks {
		s := m.QueriedBlocks[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *SeriesRequestHints) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SeriesRequestHints) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SeriesRequestHints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.BlockMatchers) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.BlockMatchers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		if size <= 0x7F {
			dAtA[i-1] = uint8(size)
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *SeriesResponseHints) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SeriesResponseHints) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SeriesResponseHints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.QueriedBlocks) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.QueriedBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		if size <= 0x7F {
			dAtA[i-1] = uint8(size)
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *Block) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Block) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Block) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		if len(m.Id) <= 0x7F {
			dAtA[i-1] = uint8(len(m.Id))
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Id)))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *LabelNamesRequestHints) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LabelNamesRequestHints) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LabelNamesRequestHints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.BlockMatchers) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.BlockMatchers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		if size <= 0x7F {
			dAtA[i-1] = uint8(size)
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *LabelNamesResponseHints) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LabelNamesResponseHints) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LabelNamesResponseHints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.QueriedBlocks) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.QueriedBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		if size <= 0x7F {
			dAtA[i-1] = uint8(size)
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *LabelValuesRequestHints) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LabelValuesRequestHints) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LabelValuesRequestHints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.BlockMatchers) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.BlockMatchers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		if size <= 0x7F {
			dAtA[i-1] = uint8(size)
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *LabelValuesResponseHints) Marshal() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LabelValuesResponseHints) MarshalTo(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LabelValuesResponseHints) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	for iNdEx := len(m.QueriedBlocks) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.QueriedBlocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		if size <= 0x7F {
			dAtA[i-1] = uint8(size)
			i--
		} else {
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *SeriesRequestHints) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *SeriesRequestHints) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *SeriesRequestHints) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 && depth >= 0 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			if len(m.BlockMatchers) == 0 && cap(m.BlockMatchers) < c {
				m.BlockMatchers = make([]storepb.LabelMatcher, 0, c)
			}
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // block_matchers
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockMatchers = append(m.BlockMatchers, storepb.LabelMatcher{})
			if err := m.BlockMatchers[len(m.BlockMatchers)-1].UnmarshalWithDepth(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SeriesRequestHints) UnmarshalNoPrescan(dAtA []byte) error {
	return m.unmarshal(dAtA, -1)
}

func (m *SeriesResponseHints) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *SeriesResponseHints) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *SeriesResponseHints) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 && depth >= 0 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			if len(m.QueriedBlocks) == 0 && cap(m.QueriedBlocks) < c {
				m.QueriedBlocks = make([]Block, 0, c)
			}
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // queried_blocks
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueriedBlocks = append(m.QueriedBlocks, Block{})
			if err := m.QueriedBlocks[len(m.QueriedBlocks)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *SeriesResponseHints) UnmarshalNoPrescan(dAtA []byte) error {
	return m.unmarshal(dAtA, -1)
}

func (m *Block) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *Block) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *Block) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // id
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *LabelNamesRequestHints) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *LabelNamesRequestHints) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *LabelNamesRequestHints) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 && depth >= 0 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			if len(m.BlockMatchers) == 0 && cap(m.BlockMatchers) < c {
				m.BlockMatchers = make([]storepb.LabelMatcher, 0, c)
			}
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // block_matchers
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockMatchers = append(m.BlockMatchers, storepb.LabelMatcher{})
			if err := m.BlockMatchers[len(m.BlockMatchers)-1].UnmarshalWithDepth(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *LabelNamesRequestHints) UnmarshalNoPrescan(dAtA []byte) error {
	return m.unmarshal(dAtA, -1)
}

func (m *LabelNamesResponseHints) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *LabelNamesResponseHints) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *LabelNamesResponseHints) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 && depth >= 0 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			if len(m.QueriedBlocks) == 0 && cap(m.QueriedBlocks) < c {
				m.QueriedBlocks = make([]Block, 0, c)
			}
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // queried_blocks
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueriedBlocks = append(m.QueriedBlocks, Block{})
			if err := m.QueriedBlocks[len(m.QueriedBlocks)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *LabelNamesResponseHints) UnmarshalNoPrescan(dAtA []byte) error {
	return m.unmarshal(dAtA, -1)
}

func (m *LabelValuesRequestHints) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *LabelValuesRequestHints) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *LabelValuesRequestHints) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 && depth >= 0 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			if len(m.BlockMatchers) == 0 && cap(m.BlockMatchers) < c {
				m.BlockMatchers = make([]storepb.LabelMatcher, 0, c)
			}
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // block_matchers
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockMatchers = append(m.BlockMatchers, storepb.LabelMatcher{})
			if err := m.BlockMatchers[len(m.BlockMatchers)-1].UnmarshalWithDepth(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *LabelValuesRequestHints) UnmarshalNoPrescan(dAtA []byte) error {
	return m.unmarshal(dAtA, -1)
}

func (m *LabelValuesResponseHints) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *LabelValuesResponseHints) UnmarshalWithDepth(b []byte, depth int) error {
	if depth < 0 {
		depth = 0
	}
	return m.unmarshal(b, depth)
}

func (m *LabelValuesResponseHints) unmarshal(dAtA []byte, depth int) error {
	if depth > protohelpers.MaxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 && depth >= 0 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				preIdx = -1
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		preCapMax := l / 2
		if c := field1count; c > 0 {
			if c > preCapMax {
				c = preCapMax
			}
			if len(m.QueriedBlocks) == 0 && cap(m.QueriedBlocks) < c {
				m.QueriedBlocks = make([]Block, 0, c)
			}
		}
	}
	for iNdEx < l {
		var wire uint64
		if iNdEx < l && dAtA[iNdEx] < 0x80 {
			wire = uint64(dAtA[iNdEx])
			iNdEx++
		} else {
			for shift := uint(0); ; shift += 7 {
				if shift >= 35 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // queried_blocks
			if wireType != 2 {
				n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			if iNdEx < l && dAtA[iNdEx] < 0x80 {
				byteLen = uint64(dAtA[iNdEx])
				iNdEx++
			} else {
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return fmt.Errorf("proto: integer overflow")
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						if shift == 63 && b > 1 {
							return fmt.Errorf("proto: varint overflow")
						}
						break
					}
				}
			}
			if byteLen > uint64(math.MaxInt) {
				return io.ErrUnexpectedEOF
			}
			intByteLen := int(byteLen)
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueriedBlocks = append(m.QueriedBlocks, Block{})
			if err := m.QueriedBlocks[len(m.QueriedBlocks)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := protohelpers.SkipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *LabelValuesResponseHints) UnmarshalNoPrescan(dAtA []byte) error {
	return m.unmarshal(dAtA, -1)
}
