# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.34"

volumeAttributesClasses:
  gp3-standard:
    driverName: ebs.csi.aws.com
    parameters:
      type: gp3
      iops: "3000"
      throughput: "125"

ingester:
  persistentVolume:
    volumeAttributesClassName: gp3-standard
  zoneAwareReplication:
    zones:
      - name: zone-a
        nodeSelector: null
        extraAffinity: {}
        storageClass: null
        volumeAttributesClassName: gp3-standard
        noDownscale: false
        downscaleLeader: null
        prepareDownscale: true
      - name: zone-b
        nodeSelector: null
        extraAffinity: {}
        storageClass: null
        volumeAttributesClassName: null
        noDownscale: false
        downscaleLeader: null
        prepareDownscale: true
      - name: zone-c
        nodeSelector: null
        extraAffinity: {}
        storageClass: null
        volumeAttributesClassName: null
        noDownscale: false
        downscaleLeader: null
        prepareDownscale: true

compactor:
  persistentVolume:
    volumeAttributesClass:
      create: true
      driverName: ebs.csi.aws.com
      parameters:
        type: gp3
        iops: "5000"

kafka:
  persistence:
    volumeAttributesClassName: external-vac
