# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.32"

alertmanager:
  priorityClassName: alertmanager-priority
  # ensure Deployment is used, not default StatefulSet
  statefulSet:
    enabled: false

# Reduce scope:
minio:
  enabled: false
rollout_operator:
  enabled: false
