# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.32"

# Opt the chart-managed service account out of token auto-mounting.
serviceAccount:
  create: true
  automountServiceAccountToken: false

# Create dedicated service account, and explicitly opt in to token auto-mounting.
alertmanager:
  serviceAccount:
    create: true
    automountServiceAccountToken: true

# Create dedicated service account, and verify it inherits token auto-mount opt-out.
ruler:
  serviceAccount:
    create: true

# Enable Mimir's Vault client to verify affected components get auto-mounting re-enabled.
mimir:
  structuredConfig:
    vault:
      enabled: true
      url: http://vault.citestns.svc:8200
      mount_path: secret
      auth:
        type: kubernetes
        kubernetes:
          role_name: test-role-name

# Verify an explicit per-component disable wins, even if automatic detection wants to mount.
# We explicitly document that this value will allow the user to override the safeguard.
ingester:
  automountServiceAccountToken: false

# Verify an explicit per-component enable wins, even if automatic detection does not want to mount.
kafka:
  automountServiceAccountToken: true
