// Code generated by node-gen. DO NOT EDIT.
// SPDX-License-Identifier: AGPL-3.0-only

package multiaggregation

import (
	"fmt"

	"github.com/grafana/mimir/pkg/streamingpromql/planning"
)

func (m *MultiAggregationGroup) Child(idx int) planning.Node {
	if idx != 0 {
		panic(fmt.Sprintf("node of type MultiAggregationGroup supports 1 child, but attempted to get child at index %d", idx))
	}
	return m.Inner
}

func (m *MultiAggregationGroup) ChildCount() int {
	return 1
}

func (m *MultiAggregationGroup) SetChildren(children []planning.Node) error {
	if len(children) != 1 {
		return fmt.Errorf("node of type MultiAggregationGroup expects one child, but got %d", len(children))
	}
	m.Inner = children[0]
	return nil
}

func (m *MultiAggregationInstance) Child(idx int) planning.Node {
	if idx != 0 {
		panic(fmt.Sprintf("node of type MultiAggregationInstance supports 1 child, but attempted to get child at index %d", idx))
	}
	return m.Group
}

func (m *MultiAggregationInstance) ChildCount() int {
	return 1
}

func (m *MultiAggregationInstance) SetChildren(children []planning.Node) error {
	if len(children) != 1 {
		return fmt.Errorf("node of type MultiAggregationInstance expects one child, but got %d", len(children))
	}
	child0, ok := children[0].(*MultiAggregationGroup)
	if !ok {
		return fmt.Errorf("node of type MultiAggregationInstance expects child Group to be of type *MultiAggregationGroup, but got %T", children[0])
	}
	m.Group = child0
	return nil
}
