// Code generated by wiresmith. DO NOT EDIT.
// source: ruler/ruler.proto

package ruler

import (
	"context"
	"encoding/binary"
	"fmt"
	"github.com/gogo/protobuf/proto"
	"github.com/gogo/protobuf/types"
	"github.com/grafana/mimir/pkg/mimirpb"
	"github.com/grafana/mimir/pkg/ruler/rulespb"
	"github.com/grafana/wiresmith/gen/protohelpers"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protowire"
	"math"
	"math/bits"
	"strings"
	"time"
)

type RulesRequest_RuleType int32

const (
	AnyRule       RulesRequest_RuleType = 0
	AlertingRule  RulesRequest_RuleType = 1
	RecordingRule RulesRequest_RuleType = 2
)

type RulesRequest struct {
	Filter        RulesRequest_RuleType `protobuf:"varint,1,opt,name=filter,proto3" json:"filter,omitempty"`
	RuleName      []string              `protobuf:"bytes,2,rep,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	RuleGroup     []string              `protobuf:"bytes,3,rep,name=rule_group,json=ruleGroup,proto3" json:"rule_group,omitempty"`
	File          []string              `protobuf:"bytes,4,rep,name=file,proto3" json:"file,omitempty"`
	ExcludeAlerts bool                  `protobuf:"varint,5,opt,name=exclude_alerts,json=excludeAlerts,proto3" json:"exclude_alerts,omitempty"`
	MaxGroups     int32                 `protobuf:"varint,6,opt,name=max_groups,json=maxGroups,proto3" json:"max_groups,omitempty"`
	NextToken     string                `protobuf:"bytes,7,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
}

type RulesResponse struct {
	// Keep reference to buffer for unsafe references.
	mimirpb.BufferHolder

	Groups   []*GroupStateDesc `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Warnings []string          `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
}

// SyncRulesRequest is the message sent to request a ruler to re-synchronize the rules of 1+ tenants.
type SyncRulesRequest struct {
	// The user / tenant IDs for which the rules should be synced.
	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
}

// SyncRulesResponse is the message received back for a SyncRulesRequest.
type SyncRulesResponse struct {
}

// GroupStateDesc is a proto representation of a mimir rule group
type GroupStateDesc struct {
	Group               *rulespb.RuleGroupDesc `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	ActiveRules         []*RuleStateDesc       `protobuf:"bytes,2,rep,name=active_rules,json=activeRules,proto3" json:"active_rules,omitempty"`
	EvaluationTimestamp time.Time              `protobuf:"bytes,3,opt,name=evaluationTimestamp,proto3" json:"evaluationTimestamp"`
	EvaluationDuration  time.Duration          `protobuf:"bytes,4,opt,name=evaluationDuration,proto3" json:"evaluationDuration"`
}

// RuleStateDesc is a proto representation of a Prometheus Rule
type RuleStateDesc struct {
	Rule                *rulespb.RuleDesc `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	State               string            `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Health              string            `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	LastError           string            `protobuf:"bytes,4,opt,name=lastError,proto3" json:"lastError,omitempty"`
	Alerts              []*AlertStateDesc `protobuf:"bytes,5,rep,name=alerts,proto3" json:"alerts,omitempty"`
	EvaluationTimestamp time.Time         `protobuf:"bytes,6,opt,name=evaluationTimestamp,proto3" json:"evaluationTimestamp"`
	EvaluationDuration  time.Duration     `protobuf:"bytes,7,opt,name=evaluationDuration,proto3" json:"evaluationDuration"`
}

type AlertStateDesc struct {
	State           string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Labels          []mimirpb.LabelAdapter `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels"`
	Annotations     []mimirpb.LabelAdapter `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations"`
	Value           float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	ActiveAt        time.Time              `protobuf:"bytes,5,opt,name=active_at,json=activeAt,proto3" json:"active_at"`
	FiredAt         time.Time              `protobuf:"bytes,6,opt,name=fired_at,json=firedAt,proto3" json:"fired_at"`
	ResolvedAt      time.Time              `protobuf:"bytes,7,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at"`
	LastSentAt      time.Time              `protobuf:"bytes,8,opt,name=last_sent_at,json=lastSentAt,proto3" json:"last_sent_at"`
	ValidUntil      time.Time              `protobuf:"bytes,9,opt,name=valid_until,json=validUntil,proto3" json:"valid_until"`
	KeepFiringSince time.Time              `protobuf:"bytes,10,opt,name=keep_firing_since,json=keepFiringSince,proto3" json:"keep_firing_since"`
}

func (m *RulesRequest) Size() int {
	var n int
	if m.Filter != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.Filter))
	}
	for _, v := range m.RuleName {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	for _, v := range m.RuleGroup {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	for _, v := range m.File {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	if m.ExcludeAlerts {
		n += 2
	}
	if m.MaxGroups != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.MaxGroups))
	}
	if len(m.NextToken) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.NextToken))) + len(m.NextToken)
	}
	return n
}

func (m *RulesResponse) Size() int {
	var n int
	for i := range m.Groups {
		s := m.Groups[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	for _, v := range m.Warnings {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	return n
}

func (m *SyncRulesRequest) Size() int {
	var n int
	for _, v := range m.UserIds {
		n += 1 + protowire.SizeVarint(uint64(len(v))) + len(v)
	}
	return n
}

func (m *SyncRulesResponse) Size() int {
	var n int
	return n
}

func (m *GroupStateDesc) Size() int {
	var n int
	if m.Group != nil {
		s := m.Group.Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	for i := range m.ActiveRules {
		s := m.ActiveRules[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	{
		l := types.SizeOfStdTime(m.EvaluationTimestamp)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	{
		l := types.SizeOfStdDuration(m.EvaluationDuration)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *RuleStateDesc) Size() int {
	var n int
	if m.Rule != nil {
		s := m.Rule.Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if len(m.State) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.State))) + len(m.State)
	}
	if len(m.Health) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.Health))) + len(m.Health)
	}
	if len(m.LastError) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.LastError))) + len(m.LastError)
	}
	for i := range m.Alerts {
		s := m.Alerts[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	{
		l := types.SizeOfStdTime(m.EvaluationTimestamp)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	{
		l := types.SizeOfStdDuration(m.EvaluationDuration)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *AlertStateDesc) Size() int {
	var n int
	if len(m.State) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.State))) + len(m.State)
	}
	for i := range m.Labels {
		s := m.Labels[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	for i := range m.Annotations {
		s := m.Annotations[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.Value != 0 {
		n += 9
	}
	{
		l := types.SizeOfStdTime(m.ActiveAt)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	{
		l := types.SizeOfStdTime(m.FiredAt)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	{
		l := types.SizeOfStdTime(m.ResolvedAt)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	{
		l := types.SizeOfStdTime(m.LastSentAt)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	{
		l := types.SizeOfStdTime(m.ValidUntil)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	{
		l := types.SizeOfStdTime(m.KeepFiringSince)
		n += 1 + protowire.SizeVarint(uint64(l)) + l
	}
	return n
}

func (m *RulesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RulesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RulesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if len(m.NextToken) > 0 {
		i -= len(m.NextToken)
		copy(dAtA[i:], m.NextToken)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.NextToken)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MaxGroups != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.MaxGroups))
		i--
		dAtA[i] = 0x30
	}
	if m.ExcludeAlerts {
		i--
		if m.ExcludeAlerts {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	for iNdEx := len(m.File) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.File[iNdEx])
		copy(dAtA[i:], m.File[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.File[iNdEx])))
		i--
		dAtA[i] = 0x22
	}
	for iNdEx := len(m.RuleGroup) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.RuleGroup[iNdEx])
		copy(dAtA[i:], m.RuleGroup[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.RuleGroup[iNdEx])))
		i--
		dAtA[i] = 0x1a
	}
	for iNdEx := len(m.RuleName) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.RuleName[iNdEx])
		copy(dAtA[i:], m.RuleName[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.RuleName[iNdEx])))
		i--
		dAtA[i] = 0x12
	}
	if m.Filter != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Filter))
		i--
		dAtA[i] = 0x08
	}
	return len(dAtA) - i, nil
}

func (m *RulesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RulesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RulesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	for iNdEx := len(m.Warnings) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.Warnings[iNdEx])
		copy(dAtA[i:], m.Warnings[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Warnings[iNdEx])))
		i--
		dAtA[i] = 0x12
	}
	for iNdEx := len(m.Groups) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Groups[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *SyncRulesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncRulesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncRulesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	for iNdEx := len(m.UserIds) - 1; iNdEx >= 0; iNdEx-- {
		i -= len(m.UserIds[iNdEx])
		copy(dAtA[i:], m.UserIds[iNdEx])
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.UserIds[iNdEx])))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *SyncRulesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncRulesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncRulesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	return len(dAtA) - i, nil
}

func (m *GroupStateDesc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupStateDesc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GroupStateDesc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	{
		n, err := types.StdDurationMarshalTo(m.EvaluationDuration, dAtA[i-types.SizeOfStdDuration(m.EvaluationDuration):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x22
	}
	{
		n, err := types.StdTimeMarshalTo(m.EvaluationTimestamp, dAtA[i-types.SizeOfStdTime(m.EvaluationTimestamp):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x1a
	}
	for iNdEx := len(m.ActiveRules) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.ActiveRules[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	if m.Group != nil {
		size, err := m.Group.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *RuleStateDesc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RuleStateDesc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RuleStateDesc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	{
		n, err := types.StdDurationMarshalTo(m.EvaluationDuration, dAtA[i-types.SizeOfStdDuration(m.EvaluationDuration):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x3a
	}
	{
		n, err := types.StdTimeMarshalTo(m.EvaluationTimestamp, dAtA[i-types.SizeOfStdTime(m.EvaluationTimestamp):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x32
	}
	for iNdEx := len(m.Alerts) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Alerts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.LastError) > 0 {
		i -= len(m.LastError)
		copy(dAtA[i:], m.LastError)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.LastError)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Health) > 0 {
		i -= len(m.Health)
		copy(dAtA[i:], m.Health)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Health)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x12
	}
	if m.Rule != nil {
		size, err := m.Rule.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *AlertStateDesc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AlertStateDesc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AlertStateDesc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	{
		n, err := types.StdTimeMarshalTo(m.KeepFiringSince, dAtA[i-types.SizeOfStdTime(m.KeepFiringSince):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x52
	}
	{
		n, err := types.StdTimeMarshalTo(m.ValidUntil, dAtA[i-types.SizeOfStdTime(m.ValidUntil):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x4a
	}
	{
		n, err := types.StdTimeMarshalTo(m.LastSentAt, dAtA[i-types.SizeOfStdTime(m.LastSentAt):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x42
	}
	{
		n, err := types.StdTimeMarshalTo(m.ResolvedAt, dAtA[i-types.SizeOfStdTime(m.ResolvedAt):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x3a
	}
	{
		n, err := types.StdTimeMarshalTo(m.FiredAt, dAtA[i-types.SizeOfStdTime(m.FiredAt):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x32
	}
	{
		n, err := types.StdTimeMarshalTo(m.ActiveAt, dAtA[i-types.SizeOfStdTime(m.ActiveAt):])
		if err != nil {
			return 0, err
		}
		i -= n
		i = protohelpers.EncodeVarint(dAtA, i, uint64(n))
		i--
		dAtA[i] = 0x2a
	}
	if m.Value != 0 {
		i -= 8
		binary.LittleEndian.PutUint64(dAtA[i:], math.Float64bits(m.Value))
		i--
		dAtA[i] = 0x21
	}
	for iNdEx := len(m.Annotations) - 1; iNdEx >= 0; iNdEx-- {
		{
			size := m.Annotations[iNdEx].Size()
			i -= size
			if _, err := m.Annotations[iNdEx].MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x1a
		}
	}
	for iNdEx := len(m.Labels) - 1; iNdEx >= 0; iNdEx-- {
		{
			size := m.Labels[iNdEx].Size()
			i -= size
			if _, err := m.Labels[iNdEx].MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func skipField_Ruler(b []byte, num protowire.Number, typ protowire.Type) (int, error) {
	switch typ {
	case protowire.VarintType:
		_, n := protowire.ConsumeVarint(b)
		if n < 0 {
			return 0, fmt.Errorf("invalid varint")
		}
		return n, nil
	case protowire.Fixed32Type:
		if len(b) < 4 {
			return 0, fmt.Errorf("truncated fixed32")
		}
		return 4, nil
	case protowire.Fixed64Type:
		if len(b) < 8 {
			return 0, fmt.Errorf("truncated fixed64")
		}
		return 8, nil
	case protowire.BytesType:
		_, n := protowire.ConsumeBytes(b)
		if n < 0 {
			return 0, fmt.Errorf("invalid bytes")
		}
		return n, nil
	case protowire.StartGroupType:
		_, n := protowire.ConsumeGroup(num, b)
		if n < 0 {
			return 0, fmt.Errorf("invalid group")
		}
		return n, nil
	default:
		return 0, fmt.Errorf("unknown wire type %d", typ)
	}
}

func (m *RulesRequest) Unmarshal(b []byte) error {
	if len(b) >= 256 {
		tmp := b
		var field2count int
		var field3count int
		var field4count int
		for len(tmp) > 0 {
			num, typ, tagLen := protowire.ConsumeTag(tmp)
			if tagLen < 0 {
				break
			}
			tmp = tmp[tagLen:]
			switch num {
			case 2:
				field2count++
			case 3:
				field3count++
			case 4:
				field4count++
			}
			var skip int
			switch typ {
			case protowire.VarintType:
				_, skip = protowire.ConsumeVarint(tmp)
			case protowire.Fixed32Type:
				skip = 4
			case protowire.Fixed64Type:
				skip = 8
			case protowire.BytesType:
				_, skip = protowire.ConsumeBytes(tmp)
			case protowire.StartGroupType:
				_, skip = protowire.ConsumeGroup(num, tmp)
			}
			if skip < 0 || skip > len(tmp) {
				break
			}
			tmp = tmp[skip:]
		}
		if field2count > 0 {
			m.RuleName = make([]string, 0, field2count)
		}
		if field3count > 0 {
			m.RuleGroup = make([]string, 0, field3count)
		}
		if field4count > 0 {
			m.File = make([]string, 0, field4count)
		}
	}
	for len(b) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(b)
		if tagLen < 0 {
			return fmt.Errorf("invalid tag")
		}
		b = b[tagLen:]
		switch num {
		case 1: // filter
			if typ != protowire.VarintType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("invalid varint")
			}
			m.Filter = RulesRequest_RuleType(v)
			b = b[n:]
		case 2: // rule_name
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.RuleName = append(m.RuleName, v)
			b = b[n:]
		case 3: // rule_group
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.RuleGroup = append(m.RuleGroup, v)
			b = b[n:]
		case 4: // file
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.File = append(m.File, v)
			b = b[n:]
		case 5: // exclude_alerts
			if typ != protowire.VarintType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("invalid varint")
			}
			m.ExcludeAlerts = v != 0
			b = b[n:]
		case 6: // max_groups
			if typ != protowire.VarintType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeVarint(b)
			if n < 0 {
				return fmt.Errorf("invalid varint")
			}
			m.MaxGroups = int32(v)
			b = b[n:]
		case 7: // next_token
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.NextToken = v
			b = b[n:]
		default:
			n, err := skipField_Ruler(b, num, typ)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

func (m *RulesResponse) Unmarshal(b []byte) error {
	if len(b) >= 256 {
		tmp := b
		var field1count int
		var field2count int
		for len(tmp) > 0 {
			num, typ, tagLen := protowire.ConsumeTag(tmp)
			if tagLen < 0 {
				break
			}
			tmp = tmp[tagLen:]
			switch num {
			case 1:
				field1count++
			case 2:
				field2count++
			}
			var skip int
			switch typ {
			case protowire.VarintType:
				_, skip = protowire.ConsumeVarint(tmp)
			case protowire.Fixed32Type:
				skip = 4
			case protowire.Fixed64Type:
				skip = 8
			case protowire.BytesType:
				_, skip = protowire.ConsumeBytes(tmp)
			case protowire.StartGroupType:
				_, skip = protowire.ConsumeGroup(num, tmp)
			}
			if skip < 0 || skip > len(tmp) {
				break
			}
			tmp = tmp[skip:]
		}
		if field1count > 0 {
			m.Groups = make([]*GroupStateDesc, 0, field1count)
		}
		if field2count > 0 {
			m.Warnings = make([]string, 0, field2count)
		}
	}
	for len(b) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(b)
		if tagLen < 0 {
			return fmt.Errorf("invalid tag")
		}
		b = b[tagLen:]
		switch num {
		case 1: // groups
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			m.Groups = append(m.Groups, &GroupStateDesc{})
			if err := m.Groups[len(m.Groups)-1].Unmarshal(v); err != nil {
				return err
			}
			b = b[n:]
		case 2: // warnings
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.Warnings = append(m.Warnings, v)
			b = b[n:]
		default:
			n, err := skipField_Ruler(b, num, typ)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

func (m *SyncRulesRequest) Unmarshal(b []byte) error {
	if len(b) >= 256 {
		tmp := b
		var field1count int
		for len(tmp) > 0 {
			num, typ, tagLen := protowire.ConsumeTag(tmp)
			if tagLen < 0 {
				break
			}
			tmp = tmp[tagLen:]
			switch num {
			case 1:
				field1count++
			}
			var skip int
			switch typ {
			case protowire.VarintType:
				_, skip = protowire.ConsumeVarint(tmp)
			case protowire.Fixed32Type:
				skip = 4
			case protowire.Fixed64Type:
				skip = 8
			case protowire.BytesType:
				_, skip = protowire.ConsumeBytes(tmp)
			case protowire.StartGroupType:
				_, skip = protowire.ConsumeGroup(num, tmp)
			}
			if skip < 0 || skip > len(tmp) {
				break
			}
			tmp = tmp[skip:]
		}
		if field1count > 0 {
			m.UserIds = make([]string, 0, field1count)
		}
	}
	for len(b) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(b)
		if tagLen < 0 {
			return fmt.Errorf("invalid tag")
		}
		b = b[tagLen:]
		switch num {
		case 1: // user_ids
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.UserIds = append(m.UserIds, v)
			b = b[n:]
		default:
			n, err := skipField_Ruler(b, num, typ)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

func (m *SyncRulesResponse) Unmarshal(b []byte) error {
	for len(b) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(b)
		if tagLen < 0 {
			return fmt.Errorf("invalid tag")
		}
		b = b[tagLen:]
		switch num {
		default:
			n, err := skipField_Ruler(b, num, typ)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

func (m *GroupStateDesc) Unmarshal(b []byte) error {
	if len(b) >= 256 {
		tmp := b
		var field2count int
		for len(tmp) > 0 {
			num, typ, tagLen := protowire.ConsumeTag(tmp)
			if tagLen < 0 {
				break
			}
			tmp = tmp[tagLen:]
			switch num {
			case 2:
				field2count++
			}
			var skip int
			switch typ {
			case protowire.VarintType:
				_, skip = protowire.ConsumeVarint(tmp)
			case protowire.Fixed32Type:
				skip = 4
			case protowire.Fixed64Type:
				skip = 8
			case protowire.BytesType:
				_, skip = protowire.ConsumeBytes(tmp)
			case protowire.StartGroupType:
				_, skip = protowire.ConsumeGroup(num, tmp)
			}
			if skip < 0 || skip > len(tmp) {
				break
			}
			tmp = tmp[skip:]
		}
		if field2count > 0 {
			m.ActiveRules = make([]*RuleStateDesc, 0, field2count)
		}
	}
	for len(b) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(b)
		if tagLen < 0 {
			return fmt.Errorf("invalid tag")
		}
		b = b[tagLen:]
		switch num {
		case 1: // group
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if m.Group == nil {
				m.Group = &rulespb.RuleGroupDesc{}
			}
			if err := m.Group.Unmarshal(v); err != nil {
				return err
			}
			b = b[n:]
		case 2: // active_rules
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			m.ActiveRules = append(m.ActiveRules, &RuleStateDesc{})
			if err := m.ActiveRules[len(m.ActiveRules)-1].Unmarshal(v); err != nil {
				return err
			}
			b = b[n:]
		case 3: // evaluationTimestamp
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.EvaluationTimestamp, v); err != nil {
				return err
			}
			b = b[n:]
		case 4: // evaluationDuration
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdDurationUnmarshal(&m.EvaluationDuration, v); err != nil {
				return err
			}
			b = b[n:]
		default:
			n, err := skipField_Ruler(b, num, typ)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

func (m *RuleStateDesc) Unmarshal(b []byte) error {
	if len(b) >= 256 {
		tmp := b
		var field5count int
		for len(tmp) > 0 {
			num, typ, tagLen := protowire.ConsumeTag(tmp)
			if tagLen < 0 {
				break
			}
			tmp = tmp[tagLen:]
			switch num {
			case 5:
				field5count++
			}
			var skip int
			switch typ {
			case protowire.VarintType:
				_, skip = protowire.ConsumeVarint(tmp)
			case protowire.Fixed32Type:
				skip = 4
			case protowire.Fixed64Type:
				skip = 8
			case protowire.BytesType:
				_, skip = protowire.ConsumeBytes(tmp)
			case protowire.StartGroupType:
				_, skip = protowire.ConsumeGroup(num, tmp)
			}
			if skip < 0 || skip > len(tmp) {
				break
			}
			tmp = tmp[skip:]
		}
		if field5count > 0 {
			m.Alerts = make([]*AlertStateDesc, 0, field5count)
		}
	}
	for len(b) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(b)
		if tagLen < 0 {
			return fmt.Errorf("invalid tag")
		}
		b = b[tagLen:]
		switch num {
		case 1: // rule
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if m.Rule == nil {
				m.Rule = &rulespb.RuleDesc{}
			}
			if err := m.Rule.Unmarshal(v); err != nil {
				return err
			}
			b = b[n:]
		case 2: // state
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.State = v
			b = b[n:]
		case 3: // health
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.Health = v
			b = b[n:]
		case 4: // lastError
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.LastError = v
			b = b[n:]
		case 5: // alerts
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			m.Alerts = append(m.Alerts, &AlertStateDesc{})
			if err := m.Alerts[len(m.Alerts)-1].Unmarshal(v); err != nil {
				return err
			}
			b = b[n:]
		case 6: // evaluationTimestamp
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.EvaluationTimestamp, v); err != nil {
				return err
			}
			b = b[n:]
		case 7: // evaluationDuration
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdDurationUnmarshal(&m.EvaluationDuration, v); err != nil {
				return err
			}
			b = b[n:]
		default:
			n, err := skipField_Ruler(b, num, typ)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

func (m *AlertStateDesc) Unmarshal(b []byte) error {
	if len(b) >= 256 {
		tmp := b
		var field2count int
		var field3count int
		for len(tmp) > 0 {
			num, typ, tagLen := protowire.ConsumeTag(tmp)
			if tagLen < 0 {
				break
			}
			tmp = tmp[tagLen:]
			switch num {
			case 2:
				field2count++
			case 3:
				field3count++
			}
			var skip int
			switch typ {
			case protowire.VarintType:
				_, skip = protowire.ConsumeVarint(tmp)
			case protowire.Fixed32Type:
				skip = 4
			case protowire.Fixed64Type:
				skip = 8
			case protowire.BytesType:
				_, skip = protowire.ConsumeBytes(tmp)
			case protowire.StartGroupType:
				_, skip = protowire.ConsumeGroup(num, tmp)
			}
			if skip < 0 || skip > len(tmp) {
				break
			}
			tmp = tmp[skip:]
		}
		if field2count > 0 {
			m.Labels = make([]mimirpb.LabelAdapter, 0, field2count)
		}
		if field3count > 0 {
			m.Annotations = make([]mimirpb.LabelAdapter, 0, field3count)
		}
	}
	for len(b) > 0 {
		num, typ, tagLen := protowire.ConsumeTag(b)
		if tagLen < 0 {
			return fmt.Errorf("invalid tag")
		}
		b = b[tagLen:]
		switch num {
		case 1: // state
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeString(b)
			if n < 0 {
				return fmt.Errorf("invalid string")
			}
			m.State = v
			b = b[n:]
		case 2: // labels
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			m.Labels = append(m.Labels, mimirpb.LabelAdapter{})
			if err := m.Labels[len(m.Labels)-1].Unmarshal(v); err != nil {
				return err
			}
			b = b[n:]
		case 3: // annotations
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			m.Annotations = append(m.Annotations, mimirpb.LabelAdapter{})
			if err := m.Annotations[len(m.Annotations)-1].Unmarshal(v); err != nil {
				return err
			}
			b = b[n:]
		case 4: // value
			if typ != protowire.Fixed64Type {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeFixed64(b)
			if n < 0 {
				return fmt.Errorf("invalid fixed64")
			}
			m.Value = math.Float64frombits(v)
			b = b[n:]
		case 5: // active_at
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.ActiveAt, v); err != nil {
				return err
			}
			b = b[n:]
		case 6: // fired_at
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.FiredAt, v); err != nil {
				return err
			}
			b = b[n:]
		case 7: // resolved_at
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.ResolvedAt, v); err != nil {
				return err
			}
			b = b[n:]
		case 8: // last_sent_at
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.LastSentAt, v); err != nil {
				return err
			}
			b = b[n:]
		case 9: // valid_until
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.ValidUntil, v); err != nil {
				return err
			}
			b = b[n:]
		case 10: // keep_firing_since
			if typ != protowire.BytesType {
				n, err := skipField_Ruler(b, num, typ)
				if err != nil {
					return err
				}
				b = b[n:]
				continue
			}
			v, n := protowire.ConsumeBytes(b)
			if n < 0 {
				return fmt.Errorf("invalid bytes")
			}
			if err := types.StdTimeUnmarshal(&m.KeepFiringSince, v); err != nil {
				return err
			}
			b = b[n:]
		default:
			n, err := skipField_Ruler(b, num, typ)
			if err != nil {
				return err
			}
			b = b[n:]
		}
	}
	return nil
}

// RulerClient is the client API for Ruler service.
type RulerClient interface {
	Rules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error)
	SyncRules(ctx context.Context, in *SyncRulesRequest, opts ...grpc.CallOption) (*SyncRulesResponse, error)
}

type rulerClient struct {
	cc *grpc.ClientConn
}

func NewRulerClient(cc *grpc.ClientConn) RulerClient {
	return &rulerClient{cc}
}

func (c *rulerClient) Rules(ctx context.Context, in *RulesRequest, opts ...grpc.CallOption) (*RulesResponse, error) {
	out := new(RulesResponse)
	err := c.cc.Invoke(ctx, "/ruler.Ruler/Rules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rulerClient) SyncRules(ctx context.Context, in *SyncRulesRequest, opts ...grpc.CallOption) (*SyncRulesResponse, error) {
	out := new(SyncRulesResponse)
	err := c.cc.Invoke(ctx, "/ruler.Ruler/SyncRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RulerServer is the server API for Ruler service.
type RulerServer interface {
	Rules(context.Context, *RulesRequest) (*RulesResponse, error)
	SyncRules(context.Context, *SyncRulesRequest) (*SyncRulesResponse, error)
}

// UnimplementedRulerServer can be embedded to have forward compatible implementations.
type UnimplementedRulerServer struct{}

func (*UnimplementedRulerServer) Rules(ctx context.Context, req *RulesRequest) (*RulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rules not implemented")
}

func (*UnimplementedRulerServer) SyncRules(ctx context.Context, req *SyncRulesRequest) (*SyncRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncRules not implemented")
}

func RegisterRulerServer(s *grpc.Server, srv RulerServer) {
	s.RegisterService(&_Ruler_serviceDesc, srv)
}

func _Ruler_Rules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RulerServer).Rules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ruler.Ruler/Rules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RulerServer).Rules(ctx, req.(*RulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ruler_SyncRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RulerServer).SyncRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ruler.Ruler/SyncRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RulerServer).SyncRules(ctx, req.(*SyncRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ruler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ruler.Ruler",
	HandlerType: (*RulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rules",
			Handler:    _Ruler_Rules_Handler,
		},
		{
			MethodName: "SyncRules",
			Handler:    _Ruler_SyncRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ruler.proto",
}

func (m *RulesRequest) GetFilter() RulesRequest_RuleType {
	if m != nil {
		return m.Filter
	}
	return 0
}

func (m *RulesRequest) GetRuleName() []string {
	if m != nil {
		return m.RuleName
	}
	return nil
}

func (m *RulesRequest) GetRuleGroup() []string {
	if m != nil {
		return m.RuleGroup
	}
	return nil
}

func (m *RulesRequest) GetFile() []string {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *RulesRequest) GetExcludeAlerts() bool {
	if m != nil {
		return m.ExcludeAlerts
	}
	return false
}

func (m *RulesRequest) GetMaxGroups() int32 {
	if m != nil {
		return m.MaxGroups
	}
	return 0
}

func (m *RulesRequest) GetNextToken() string {
	if m != nil {
		return m.NextToken
	}
	return ""
}

func (m *RulesResponse) GetGroups() []*GroupStateDesc {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *RulesResponse) GetWarnings() []string {
	if m != nil {
		return m.Warnings
	}
	return nil
}

func (m *SyncRulesRequest) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *GroupStateDesc) GetGroup() *rulespb.RuleGroupDesc {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *GroupStateDesc) GetActiveRules() []*RuleStateDesc {
	if m != nil {
		return m.ActiveRules
	}
	return nil
}

func (m *GroupStateDesc) GetEvaluationTimestamp() time.Time {
	if m != nil {
		return m.EvaluationTimestamp
	}
	return time.Time{}
}

func (m *GroupStateDesc) GetEvaluationDuration() time.Duration {
	if m != nil {
		return m.EvaluationDuration
	}
	return 0
}

func (m *RuleStateDesc) GetRule() *rulespb.RuleDesc {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (m *RuleStateDesc) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *RuleStateDesc) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

func (m *RuleStateDesc) GetLastError() string {
	if m != nil {
		return m.LastError
	}
	return ""
}

func (m *RuleStateDesc) GetAlerts() []*AlertStateDesc {
	if m != nil {
		return m.Alerts
	}
	return nil
}

func (m *RuleStateDesc) GetEvaluationTimestamp() time.Time {
	if m != nil {
		return m.EvaluationTimestamp
	}
	return time.Time{}
}

func (m *RuleStateDesc) GetEvaluationDuration() time.Duration {
	if m != nil {
		return m.EvaluationDuration
	}
	return 0
}

func (m *AlertStateDesc) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AlertStateDesc) GetLabels() []mimirpb.LabelAdapter {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *AlertStateDesc) GetAnnotations() []mimirpb.LabelAdapter {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *AlertStateDesc) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *AlertStateDesc) GetActiveAt() time.Time {
	if m != nil {
		return m.ActiveAt
	}
	return time.Time{}
}

func (m *AlertStateDesc) GetFiredAt() time.Time {
	if m != nil {
		return m.FiredAt
	}
	return time.Time{}
}

func (m *AlertStateDesc) GetResolvedAt() time.Time {
	if m != nil {
		return m.ResolvedAt
	}
	return time.Time{}
}

func (m *AlertStateDesc) GetLastSentAt() time.Time {
	if m != nil {
		return m.LastSentAt
	}
	return time.Time{}
}

func (m *AlertStateDesc) GetValidUntil() time.Time {
	if m != nil {
		return m.ValidUntil
	}
	return time.Time{}
}

func (m *AlertStateDesc) GetKeepFiringSince() time.Time {
	if m != nil {
		return m.KeepFiringSince
	}
	return time.Time{}
}

func (this *RulesRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RulesRequest)
	if !ok {
		that2, ok := that.(RulesRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Filter != that1.Filter {
		return false
	}
	if len(this.RuleName) != len(that1.RuleName) {
		return false
	}
	for i := range this.RuleName {
		if this.RuleName[i] != that1.RuleName[i] {
			return false
		}
	}
	if len(this.RuleGroup) != len(that1.RuleGroup) {
		return false
	}
	for i := range this.RuleGroup {
		if this.RuleGroup[i] != that1.RuleGroup[i] {
			return false
		}
	}
	if len(this.File) != len(that1.File) {
		return false
	}
	for i := range this.File {
		if this.File[i] != that1.File[i] {
			return false
		}
	}
	if this.ExcludeAlerts != that1.ExcludeAlerts {
		return false
	}
	if this.MaxGroups != that1.MaxGroups {
		return false
	}
	if this.NextToken != that1.NextToken {
		return false
	}
	return true
}

func (this *RulesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RulesResponse)
	if !ok {
		that2, ok := that.(RulesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Groups) != len(that1.Groups) {
		return false
	}
	for i := range this.Groups {
		if !this.Groups[i].Equal(that1.Groups[i]) {
			return false
		}
	}
	if len(this.Warnings) != len(that1.Warnings) {
		return false
	}
	for i := range this.Warnings {
		if this.Warnings[i] != that1.Warnings[i] {
			return false
		}
	}
	return true
}

func (this *SyncRulesRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SyncRulesRequest)
	if !ok {
		that2, ok := that.(SyncRulesRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.UserIds) != len(that1.UserIds) {
		return false
	}
	for i := range this.UserIds {
		if this.UserIds[i] != that1.UserIds[i] {
			return false
		}
	}
	return true
}

func (this *SyncRulesResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SyncRulesResponse)
	if !ok {
		that2, ok := that.(SyncRulesResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}

func (this *GroupStateDesc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GroupStateDesc)
	if !ok {
		that2, ok := that.(GroupStateDesc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Group.Equal(that1.Group) {
		return false
	}
	if len(this.ActiveRules) != len(that1.ActiveRules) {
		return false
	}
	for i := range this.ActiveRules {
		if !this.ActiveRules[i].Equal(that1.ActiveRules[i]) {
			return false
		}
	}
	if this.EvaluationTimestamp != that1.EvaluationTimestamp {
		return false
	}
	if this.EvaluationDuration != that1.EvaluationDuration {
		return false
	}
	return true
}

func (this *RuleStateDesc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RuleStateDesc)
	if !ok {
		that2, ok := that.(RuleStateDesc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Rule.Equal(that1.Rule) {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if this.Health != that1.Health {
		return false
	}
	if this.LastError != that1.LastError {
		return false
	}
	if len(this.Alerts) != len(that1.Alerts) {
		return false
	}
	for i := range this.Alerts {
		if !this.Alerts[i].Equal(that1.Alerts[i]) {
			return false
		}
	}
	if this.EvaluationTimestamp != that1.EvaluationTimestamp {
		return false
	}
	if this.EvaluationDuration != that1.EvaluationDuration {
		return false
	}
	return true
}

func (this *AlertStateDesc) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AlertStateDesc)
	if !ok {
		that2, ok := that.(AlertStateDesc)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for i := range this.Labels {
		if !this.Labels[i].Equal(that1.Labels[i]) {
			return false
		}
	}
	if len(this.Annotations) != len(that1.Annotations) {
		return false
	}
	for i := range this.Annotations {
		if !this.Annotations[i].Equal(that1.Annotations[i]) {
			return false
		}
	}
	if this.Value != that1.Value {
		return false
	}
	if this.ActiveAt != that1.ActiveAt {
		return false
	}
	if this.FiredAt != that1.FiredAt {
		return false
	}
	if this.ResolvedAt != that1.ResolvedAt {
		return false
	}
	if this.LastSentAt != that1.LastSentAt {
		return false
	}
	if this.ValidUntil != that1.ValidUntil {
		return false
	}
	if this.KeepFiringSince != that1.KeepFiringSince {
		return false
	}
	return true
}

func (this *RulesRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&ruler.RulesRequest{")
	s = append(s, "Filter: "+fmt.Sprintf("%#v", this.Filter)+",\n")
	s = append(s, "RuleName: "+fmt.Sprintf("%#v", this.RuleName)+",\n")
	s = append(s, "RuleGroup: "+fmt.Sprintf("%#v", this.RuleGroup)+",\n")
	s = append(s, "File: "+fmt.Sprintf("%#v", this.File)+",\n")
	s = append(s, "ExcludeAlerts: "+fmt.Sprintf("%#v", this.ExcludeAlerts)+",\n")
	s = append(s, "MaxGroups: "+fmt.Sprintf("%#v", this.MaxGroups)+",\n")
	s = append(s, "NextToken: "+fmt.Sprintf("%#v", this.NextToken)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}

func (this *RulesResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&ruler.RulesResponse{")
	s = append(s, "Groups: "+fmt.Sprintf("%#v", this.Groups)+",\n")
	s = append(s, "Warnings: "+fmt.Sprintf("%#v", this.Warnings)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}

func (this *SyncRulesRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&ruler.SyncRulesRequest{")
	s = append(s, "UserIds: "+fmt.Sprintf("%#v", this.UserIds)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}

func (this *SyncRulesResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&ruler.SyncRulesResponse{")
	s = append(s, "}")
	return strings.Join(s, "")
}

func (this *GroupStateDesc) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&ruler.GroupStateDesc{")
	s = append(s, "Group: "+fmt.Sprintf("%#v", this.Group)+",\n")
	s = append(s, "ActiveRules: "+fmt.Sprintf("%#v", this.ActiveRules)+",\n")
	s = append(s, "EvaluationTimestamp: "+fmt.Sprintf("%#v", this.EvaluationTimestamp)+",\n")
	s = append(s, "EvaluationDuration: "+fmt.Sprintf("%#v", this.EvaluationDuration)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}

func (this *RuleStateDesc) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&ruler.RuleStateDesc{")
	s = append(s, "Rule: "+fmt.Sprintf("%#v", this.Rule)+",\n")
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "Health: "+fmt.Sprintf("%#v", this.Health)+",\n")
	s = append(s, "LastError: "+fmt.Sprintf("%#v", this.LastError)+",\n")
	s = append(s, "Alerts: "+fmt.Sprintf("%#v", this.Alerts)+",\n")
	s = append(s, "EvaluationTimestamp: "+fmt.Sprintf("%#v", this.EvaluationTimestamp)+",\n")
	s = append(s, "EvaluationDuration: "+fmt.Sprintf("%#v", this.EvaluationDuration)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}

func (this *AlertStateDesc) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 14)
	s = append(s, "&ruler.AlertStateDesc{")
	s = append(s, "State: "+fmt.Sprintf("%#v", this.State)+",\n")
	s = append(s, "Labels: "+fmt.Sprintf("%#v", this.Labels)+",\n")
	s = append(s, "Annotations: "+fmt.Sprintf("%#v", this.Annotations)+",\n")
	s = append(s, "Value: "+fmt.Sprintf("%#v", this.Value)+",\n")
	s = append(s, "ActiveAt: "+fmt.Sprintf("%#v", this.ActiveAt)+",\n")
	s = append(s, "FiredAt: "+fmt.Sprintf("%#v", this.FiredAt)+",\n")
	s = append(s, "ResolvedAt: "+fmt.Sprintf("%#v", this.ResolvedAt)+",\n")
	s = append(s, "LastSentAt: "+fmt.Sprintf("%#v", this.LastSentAt)+",\n")
	s = append(s, "ValidUntil: "+fmt.Sprintf("%#v", this.ValidUntil)+",\n")
	s = append(s, "KeepFiringSince: "+fmt.Sprintf("%#v", this.KeepFiringSince)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}

func (m *RulesRequest) Reset()      { *m = RulesRequest{} }
func (*RulesRequest) ProtoMessage() {}
func (m *RulesRequest) String() string {
	if m == nil {
		return "nil"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RulesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *RulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RulesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *RulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RulesRequest.Merge(m, src)
}

func (m *RulesRequest) XXX_Size() int {
	return m.Size()
}

func (m *RulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RulesRequest proto.InternalMessageInfo

func (m *RulesResponse) Reset()      { *m = RulesResponse{} }
func (*RulesResponse) ProtoMessage() {}
func (m *RulesResponse) String() string {
	if m == nil {
		return "nil"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RulesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *RulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RulesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *RulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RulesResponse.Merge(m, src)
}

func (m *RulesResponse) XXX_Size() int {
	return m.Size()
}

func (m *RulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RulesResponse proto.InternalMessageInfo

func (m *SyncRulesRequest) Reset()      { *m = SyncRulesRequest{} }
func (*SyncRulesRequest) ProtoMessage() {}
func (m *SyncRulesRequest) String() string {
	if m == nil {
		return "nil"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *SyncRulesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *SyncRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncRulesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *SyncRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRulesRequest.Merge(m, src)
}

func (m *SyncRulesRequest) XXX_Size() int {
	return m.Size()
}

func (m *SyncRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRulesRequest proto.InternalMessageInfo

func (m *SyncRulesResponse) Reset()      { *m = SyncRulesResponse{} }
func (*SyncRulesResponse) ProtoMessage() {}
func (m *SyncRulesResponse) String() string {
	if m == nil {
		return "nil"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *SyncRulesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *SyncRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SyncRulesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *SyncRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncRulesResponse.Merge(m, src)
}

func (m *SyncRulesResponse) XXX_Size() int {
	return m.Size()
}

func (m *SyncRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncRulesResponse proto.InternalMessageInfo

func (m *GroupStateDesc) Reset()      { *m = GroupStateDesc{} }
func (*GroupStateDesc) ProtoMessage() {}
func (m *GroupStateDesc) String() string {
	if m == nil {
		return "nil"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *GroupStateDesc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *GroupStateDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GroupStateDesc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *GroupStateDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupStateDesc.Merge(m, src)
}

func (m *GroupStateDesc) XXX_Size() int {
	return m.Size()
}

func (m *GroupStateDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupStateDesc.DiscardUnknown(m)
}

var xxx_messageInfo_GroupStateDesc proto.InternalMessageInfo

func (m *RuleStateDesc) Reset()      { *m = RuleStateDesc{} }
func (*RuleStateDesc) ProtoMessage() {}
func (m *RuleStateDesc) String() string {
	if m == nil {
		return "nil"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *RuleStateDesc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *RuleStateDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RuleStateDesc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *RuleStateDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleStateDesc.Merge(m, src)
}

func (m *RuleStateDesc) XXX_Size() int {
	return m.Size()
}

func (m *RuleStateDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleStateDesc.DiscardUnknown(m)
}

var xxx_messageInfo_RuleStateDesc proto.InternalMessageInfo

func (m *AlertStateDesc) Reset()      { *m = AlertStateDesc{} }
func (*AlertStateDesc) ProtoMessage() {}
func (m *AlertStateDesc) String() string {
	if m == nil {
		return "nil"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *AlertStateDesc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *AlertStateDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AlertStateDesc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}

func (m *AlertStateDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertStateDesc.Merge(m, src)
}

func (m *AlertStateDesc) XXX_Size() int {
	return m.Size()
}

func (m *AlertStateDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertStateDesc.DiscardUnknown(m)
}

var xxx_messageInfo_AlertStateDesc proto.InternalMessageInfo

func sovRuler(x uint64) (n int) {
	return (bits.Len64(x|1) + 6) / 7
}

func sozRuler(x uint64) (n int) {
	return sovRuler(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func encodeVarintRuler(dAtA []byte, offset int, v uint64) int {
	offset -= sovRuler(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func skipRuler(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if iNdEx >= l {
				return 0, fmt.Errorf("proto: unexpected EOF")
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if iNdEx >= l {
					return 0, fmt.Errorf("proto: unexpected EOF")
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if iNdEx >= l {
					return 0, fmt.Errorf("proto: unexpected EOF")
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRuler
			}
			iNdEx += length
		case 3:
			for {
				var innerWire uint64
				for shift := uint(0); ; shift += 7 {
					if iNdEx >= l {
						return 0, fmt.Errorf("proto: unexpected EOF")
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if int(innerWire&0x7) == 4 {
					break
				}
				next, err := skipRuler(dAtA[iNdEx:])
				if err != nil {
					return 0, err
				}
				iNdEx += next
			}
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRuler
		}
		return iNdEx, nil
	}
	return 0, fmt.Errorf("proto: unexpected EOF")
}

var (
	ErrInvalidLengthRuler        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRuler          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRuler = fmt.Errorf("proto: unexpected end of group")
)

func init() {
	proto.RegisterType((*RulesRequest)(nil), "ruler.RulesRequest")
}

func init() {
	proto.RegisterType((*RulesResponse)(nil), "ruler.RulesResponse")
}

func init() {
	proto.RegisterType((*SyncRulesRequest)(nil), "ruler.SyncRulesRequest")
}

func init() {
	proto.RegisterType((*SyncRulesResponse)(nil), "ruler.SyncRulesResponse")
}

func init() {
	proto.RegisterType((*GroupStateDesc)(nil), "ruler.GroupStateDesc")
}

func init() {
	proto.RegisterType((*RuleStateDesc)(nil), "ruler.RuleStateDesc")
}

func init() {
	proto.RegisterType((*AlertStateDesc)(nil), "ruler.AlertStateDesc")
}

var RulesRequest_RuleType_name = map[int32]string{
	0: "AnyRule",
	1: "AlertingRule",
	2: "RecordingRule",
}

var RulesRequest_RuleType_value = map[string]int32{
	"AnyRule":       0,
	"AlertingRule":  1,
	"RecordingRule": 2,
}

func (RulesRequest_RuleType) EnumDescriptor() ([]byte, []int) {
	return nil, nil
}

func (x RulesRequest_RuleType) String() string {
	if name, ok := RulesRequest_RuleType_name[int32(x)]; ok {
		return name
	}
	return fmt.Sprintf("%d", int32(x))
}

func init() {
	proto.RegisterEnum("ruler.RulesRequest.RuleType", RulesRequest_RuleType_name, RulesRequest_RuleType_value)
}
