name: Auto-review helm-weekly-release PRs

on:
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - operations/helm/charts/**

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  auto-reviewer:
    runs-on: ubuntu-latest

    if: ${{ ! github.event.pull_request.head.repo.fork && github.event.pull_request.user.login == 'mimir-github-bot[bot]' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Approve PR
        id: pr-approve
        if: startsWith(github.event.pull_request.head.ref, 'helm-chart-weekly-')
        run: |
          gh pr review $PR_URL \
          --approve -b "**I'm approving** this pull request, since it is a helm weekly release."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Manual review is required
        if: steps.pr-approve.conclusion != 'success'
        run: |
          gh pr comment $PR_URL --body "**This PR requires manual review.**"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Retrieve GitHub App Credentials from Vault
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@get-vault-secrets-v1.0.1
        with:
          repo_secrets: |
            APP_ID=mimir-github-bot:app_id
            PRIVATE_KEY=mimir-github-bot:private_key

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          # Variables generated by the previous step get-secrets
          app-id: ${{ env.APP_ID }}
          private-key: ${{ env.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # Use mimir-github-bot to trigger auto-merge.
      # Events triggered by "github-actions bot" (secrets.GITHUB_TOKEN) don't trigger GitHub actions;
      # refer to https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # Since mimir-github-bot cannot approve its own PRs, we split the approve and merge between two bots.
      - name: Auto-merge PR
        id: pr-merge-auto
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{steps.app-token.outputs.token}}
