name: helm-release

on:
  push:
    branches:
      - main
      - "mimir-distributed-release-[0-9]+.[0-9]+"

# No default permissions.
permissions: {}

jobs:
  call-update-helm-repo:
    uses: grafana/helm-charts/.github/workflows/update-helm-repo.yaml@main
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      charts_dir: operations/helm/charts
      cr_configfile: operations/helm/cr.yaml
      ct_configfile: operations/helm/ct.yaml
      github_app: mimir-helm-release
