name: Update vendored version in grafana/backend-enterprise

on:
  push:
    branches:
      - 'r[0-9]*'
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: mimir-github-bot
          permission_set: ${{ github.ref == 'refs/heads/main' && 'main' || 'release' }}

      - name: Send repository_dispatch to grafana/backend-enterprise
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: grafana/backend-enterprise
          event-type: mimir-branch-push
          client-payload: '{"branch_name": "${{ github.ref_name }}"}'
