name: Update vendored versions in grafana/backend-enterprise weekly branches

on:
  push:
    branches:
      - 'r[0-9]*'

permissions:
  contents: read
  id-token: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@580590a644e82e79bb2598bdaba0be245a14dda0 # create-github-app-token/v0.2.2
        with:
          github_app: mimir-github-bot
          permission_set: ${{ github.ref == 'refs/heads/main' && 'main' || 'release' }}

      - name: Send repository_dispatch to grafana/backend-enterprise
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: grafana/backend-enterprise
          event-type: mimir-branch-push
          client-payload: '{"branch_name": "${{ github.ref_name }}"}'
